tenant_id: common
credentials:
    auth_method: oauth2.0
    client_id_sops: ENC[AES256_GCM,data:kk3mlYo/5fVheOcRCG3xjSnAmmz4MU96wyXy8Bb4+9Ak3voO,iv:3YEnU2IQiXju0WjxlbG764icSg5PPlRJEhegIfevZmI=,tag:m6me+UiHEsAdDoZLtQ/r8g==,type:str]
    client_secret_sops: ENC[AES256_GCM,data:siu0UNQtJ4ozeFLF9PBwv2wclC1pd7pmSL42pzZPjukb8IPDi/mJ/w==,iv:bfTna/OdsUFUY4Dq+JP5L2PFZpTmqs2t0aSgJeMBY+M=,tag:GPXewxQN9+5lCiC8d+F5Ig==,type:str]
    developer_token_sops: ENC[AES256_GCM,data:C2EhU+im,iv:1D7aq5X5yNT6Axjc7667w/EuOGmpF31vHWdZ3tPZPSA=,tag:RnaRtK+Q2+mme6IMML3j3g==,type:str]
    access_token: EwB4A8l6BAAUs5+HQn0N+h2FxWzLS31ZgQVuHsYAAXYO7cbYA0dtRDfnxVUdCjWl4jHaYLiP1kOW+JPpmHVO3Y7yZ6Icwf1DdqSchtIydeIltuZr3GKV1eajrzhn408UK1t79bU/kiZe7mkZOaj5D/darzv7hr7Cw5SMfSBEpJ1mjnRXfwN1g32Tj87kdkWKRlITIhIXinv/t0Ed1lBg2M5ebkONaBuj2zyf2IMhbBLIXtKG56wZjmpag3neWfGWTMBE0SP2wy5AB1lqW7vfqZGUslfuFOgMM8Vrbhqjd246w5E/1/98otl1QcUGVzPLv14GwSxE2h9KwI1jmFmwP2AVsXi3SK/IS5JczctFy716WJ6NpT0Hx3FAugAWsXkDZgAACDsjATQ4/PP4SALXIcdoSk24CeBiJyNXhCFFQLslIrD/hZf+69cPZToiQ401fh2s84K4P7/6TrM7Rp/ZVKA2vDqBBVccKJoUoy/APBPxv95hcff7b78zJa8GdqpR7GLoHidzM2gop8owezc6oO7Z+ei+Vd/YlkXJ/7HUYerv3En++vYB/fyQYcd6coaND14aHsbRHLnUfW30Tukddj+OgFMhTWJ9e/lGj3nviR8vBOTJ1b63JzwfSxpSwyi4uJkdz66ohyatCtdIHqPJXNVqbkCJxqfY5DvjCbuszzn6RrweQSJSfNb9ZiiWe9Fx4CNfFo/36ri5OwoxdL3W5+DBbt/R4lol3POLbSNr+zhsYEMQrdgIRIzRzWXbbtWcPvUjXwHtzgUC//pqU8Hg4PbDQ8rootUKx9CyC6S917AtkJaxT8aUd1M2fqeuGB2iDULj1cul/Dv1f9MiwbpUPK4VqeQJ0kfEhRES4bpiXfW/UWV3gqIUpvAivbgMVq8mqGkXoGFezHhKLyHOhb03tYsl92S86RrHzOwdriaEE511v5FkgJfhKBUsprGsW4Mlwx9YALbnRGEQRlNAkpnEnpIQHGKdS4Rf6q0S0bGUHWxv41L/l7EbaWYVM3KSSLQ8M2P85h6bBM3dUInLmGGtfGAs0Ht7WDaV8mFJ8oJBgYD6cCxH6+0HtQmAlMa+tb7hROIzU36DkJ9OSrKDqKDto1FXmJkVLrltVgBZ7JnpAqj2+TzEVHLrPGBwCeXSibcnByKdGWA/KLfeU22olUWR8ZbMwDeD+ZUC
    refresh_token: M.C105_SN1.-CvkeMKmoKp!THhthOIxGwUQlca1l2NSZc7Aa*W3wHqY*dFwBl6UEx42PgQeuynDix6OInR*!fYx3LjZwInULrVR0OH1Y!LM*4SyKEC87zVvuFGIvITPJeGsRFsPXXoqBxy0opATwPl*yo9e*q4Ecarx03GFJMESB17B!RQQm9FiJnHiFCnnltvgAJAhmyrLMRbT6UZKShauPG25wxag8St7CcTG7dPKQXRwvyape64AWY1yUvWXe9CGL0Ht7CDsrPhMTt0bppdEdnwyUTqLAUacYdLkPMaVRmsvpS4QW6PxajVrOD0FpEDMbPEkw*lNQKkd1ah9n4Sc11RfmqtxjCWTtEhGhXKRz1jdG0nkd3JIme4O0yQ6Jsb49q*GDxHj1TKy7LNCWskModa6a8zVWJjdVQ944GgCrjgup*SQY86FO
    token_expiry_date: "2024-01-21T14:05:25.883Z"
folder_path: estuary
driver_name: d64c92ae92ac098a
drive_name: d64c92ae92ac098a
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-01-16T14:05:27Z"
          enc: CiQAdmEdwjyuIcXz5DB37jXeox3Y+uESjgphhYoDFkZVdgk0qVoSSQCVvC1zQL/sWKLGxZrX2/U8ikU/Q/zmKtdkqjQ+oIpQd8TS9BvBP45uca1/lkz+T3yyof/qtiWlcp3tHVWQhS9/15VJl7nH+7Q=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-21T13:06:18Z"
    mac: ENC[AES256_GCM,data:zvV79gcY15w4YMTr6KfK7KDK89pmWO65jRCspFsuYkj44nF0BTXYArZdQA6yUhWr3iPuoDkl3YPVLgL0Nr64L/osgf3v4jS3SHzCW5n2+hfQaw4jqR9fLb8sJ4Eygahp4+2MG979QnRoUgA9xn8zmAMoWBQOM90ckhBofbcWVYI=,iv:HI1R0dj7JNSJSnC2ePtXlOeUkQ1J+yStmjOPPG5B0Gs=,tag:JlF4hdMfto8hmWjEIcLHEQ==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
