version: "3.7"

services:
  db:
    image: 'ghcr.io/goccy/bigquery-emulator:latest'
    command: [ "--project=emulator-testing", "--dataset=testdata" ]
    ports:
      - "9050:9050"
    networks:
      - flow-test
    cap_add:
      - SYS_NICE # Prevents 'mbind: Operation not permitted' errors. In theory those are benign but it's better to not have them.

networks:
  flow-test:
    name: flow-test
    external: true
