start_date: "2024-12-01T00:00:00Z"
credentials:
    access_token_sops: ENC[AES256_GCM,data:b2sU9rAjVbmSkNLqOuZE+Fmq844q8Ki+Iso3mu9vAuFZA6FltVVX0rTZ7+lG5EDAL/qwb8qV1MOOS33E,iv:MJckBX/Pa9mgVeNUGBcowMffUsauNWWQAMSqmGFd51w=,tag:j09n4lNLkkcE0XL9F2cgHw==,type:str]
    credentials_title: Private App Credentials
advanced:
    use_companies_list_endpoint: true
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-12-13T03:09:40Z"
          enc: CiQAdmEdwkdaHRzr2VfsclM8ePj9LLfahGvE+ZaO+zHRKzp1abUSSQCtUdBGbQ/8b9ZBYjcw4LQiVsNFVIj88rbHOa/9pcHcIzFYe7PHmzt1zAMuJV20+eoqyE1aFwr6WcJrOCLa5qmyMoluya6DSnQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-16T22:30:54Z"
    mac: ENC[AES256_GCM,data:6ARWufhNdMCoTjMkjJWO+0ANxhphNQ+LhizjhaYDwT9Yd11C4MZNMNLs7pEFe0TnsqEudVtlVzZ+KsnAMCIdue5oja9VZu4uu8F+tm7PduTd6cV1R5Z8vFAM/aVl96H5rEQ31RDby6ufhisB8Xzf+b9i/Kbn88w1Ih9c5ohKvbs=,iv:mcPRIXdxwl8CCQGOayA9OD5r+qsl1YGBZShDaUrcAtI=,tag:gA0AMLxB0bDewE60/omt9A==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.7.3
