[tool.poetry]
version = "0.1.0"
name = "source_brevo"
description = ""
authors = [ "Alex Bair <alexb@estuary.dev>"]

[tool.poetry.dependencies]
estuary-cdk = {path="../estuary-cdk", develop = true}
python = "^3.11"
pydantic = "^2"

[tool.poetry.group.dev.dependencies]
debugpy = "^1.8.0"
mypy = "^1.8.0"
pytest = "^8.4"
pytest-asyncio = "^1.4.0"
pytest-insta = "^0.3.0"

[tool.pytest.ini_options]
asyncio_mode = "strict"

[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"
