[package]
name = "materialize-iceberg-rs"
version = "0.1.0"
edition = "2024"
rust-version = "1.97"

[dependencies]
proto-flow = { git = "https://github.com/estuary/flow" }

anyhow = "1.0"
bytes = "1.11"
prost = "0.14"
schemars = "1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "json",
    "env-filter",
    "time",
] }

[dev-dependencies]
insta = { version = "1", features = ["json", "serde"] }
