version: 2
updates:
  - package-ecosystem: "pip"
    directories:
      - "/**"
    schedule:
      interval: "weekly"
    groups:
      pip-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    groups:
      go-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "/**"
    schedule:
      interval: "weekly"
    groups:
      docker-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "cargo"
    directories:
      - "/**"
    schedule:
      interval: "weekly"
    groups:
      cargo-security:
        applies-to: security-updates
        patterns:
          - "*"
