# The Python connectors that python.yaml builds, tests and deploys.
#
# Note that every entry here must specify usage_rate. We're unable to
# set a default and selectively override it with `0.0`, because GH actions
# considers zero values to be "unset" (which is bs and I'm salty about it).
- name: source-airtable
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-asana
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-gladly
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-google-ads
  type: capture
  version: v2
  usage_rate: "1.0"
- name: source-google-sheets-native
  type: capture
  version: v1
  usage_rate: "0.0"
- name: source-hubspot-native
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-hubspot
  type: capture
  version: v5
  usage_rate: "1.0"
- name: source-notion
  type: capture
  version: v2
  usage_rate: "1.0"
- name: source-linear
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-linkedin-pages
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-linkedin-ads-v2
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-klaviyo
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-recharge
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-stripe-native
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-zendesk-support
  type: capture
  version: v2
  usage_rate: "1.0"
- name: source-iterable
  type: capture
  version: v2
  usage_rate: "1.0"
- name: source-pendo
  type: capture
  version: v2
  usage_rate: "1.0"
- name: source-twilio
  type: capture
  version: v2
  usage_rate: "1.0"
- name: source-jira-legacy
  type: capture
  version: v2
  usage_rate: "1.0"
- name: source-mixpanel-native
  type: capture
  version: v2
  usage_rate: "1.0"
- name: source-brevo
  type: capture
  version: v2
  usage_rate: "1.0"
- name: source-impact-native
  type: capture
  version: v2
  usage_rate: "1.0"
- name: source-front
  type: capture
  version: v3
  usage_rate: "1.0"
- name: source-genesys
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-braintree-native
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-intercom-native
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-shopify-native
  type: capture
  version: v2
  usage_rate: "1.0"
- name: source-zendesk-support-native
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-iterate
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-google-analytics-data-api-native
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-monday
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-salesforce-native
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-gainsight-nxt
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-chargebee-native
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-sage-intacct
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-outreach
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-jira-native
  type: capture
  version: v3
  usage_rate: "1.0"
- name: source-looker
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-qualtrics
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-google-play
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-apple-app-store
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-datadog
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-klaviyo-native
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-sentry
  type: capture
  version: v2
  usage_rate: "1.0"
- name: source-dynamics-365-finance-and-operations
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-incident-io
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-navan
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-facebook-marketing-native
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-quickbooks
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-airtable-native
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-ada
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-zoho
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-iterable-native
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-ringcentral
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-posthog
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-ashby
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-gong
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-greenhouse-native
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-calendly
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-appsflyer
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-zuora
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-smartsheet
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-mailchimp-native
  type: capture
  version: v1
  usage_rate: "1.0"
- name: source-criteo
  type: capture
  version: v2
  usage_rate: "1.0"
- name: source-commercetools
  type: capture
  version: v1
  usage_rate: "1.0"
