credentials:
    client_id_sops: ENC[AES256_GCM,data:2llAUKkyKCACfkIFjpnsAuyPSULNs1afy8IhxqCf7haT+ylH,iv:uGa7YcSoxTsoQhj07pbS4gaeoOAft05TZKJdR7FZD4Q=,tag:bT7z59NzNm1nLWj+alouAg==,type:str]
    client_secret_sops: ENC[AES256_GCM,data:UJTnS4mbkaiCUKbfZOPBpPPJa3GauK0tjLvYpdAAyjj+snG8,iv:Wf66M/WdQ857WEXhXgBBtRNz4DSfgqiJXzNnWse3rpo=,tag:WsgmnH8Dmi0wEwdZm5t29Q==,type:str]
    credentials_title: OAuth Credentials
    refresh_token_sops: ENC[AES256_GCM,data:kTUyVUuNvofeZxm6+DgSAphLlHXWq5WKiloQz3Og6PHMtkPM,iv:M1xSJpdr5JC8hPF4LNkpXS1B8xkX0pCBNT6FkIYdIcU=,tag:GRd1uvS9JMREAZeSyqixRg==,type:str]
    token_expiry_date: "2024-02-01T17:01:21.703Z"
start_date: "2024-04-09T12:12:34.898765Z"
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-02-01T17:08:49Z"
          enc: CiQAdmEdwu+udGkiZbfnnE8djh5o4P8p4Rm3WeXcN0XpcDF4sewSSQCVvC1zSqNDZIN7J2EPjuvJM4ILtloOm9w/OGsE4YwB2qH+sKsDDBYuIDDXtHml6w4wG0iksPY1Yxty0casvU6v02mfM3QOvyk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-09T12:13:21Z"
    mac: ENC[AES256_GCM,data:5NdZ3gQI+wPijmW6CxkZ+txTskMqn8VJB2YTA4hEMmUCgpkM71tRGh4ZLV9f0nwVSYRcVOnYiqaQrvi5Fi3sACwMvmQxmSMIvR88Hi1THFYWfTs6040WteNXXGCKOr81puUBHl+DzAKx5nb5ov1UO38Utxnl39jeHotG2ngBtdE=,iv:wX+2pRYXIXnosiAv4Hi5st1U1rJttSPp9oXhGuww0Ro=,tag:iKlD7LdQrKtcHsDFR46bqA==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
