credentials:
    credentials_title: Username & Password
    username: ADMIN
    password: P^X9DY74e3iz7a
address: (DESCRIPTION=(RETRY_COUNT=20)(RETRY_DELAY=3)(ADDRESS=(PROTOCOL=TCPS)(PORT=1521)(HOST=ADB.EU-FRANKFURT-1.ORACLECLOUD.COM))(CONNECT_DATA=(SERVICE_NAME=GCB2A4E9E921DD0_L6TEOA4HLL74YXRA_HIGH.ADB.ORACLECLOUD.COM))(SECURITY=(SSL_SERVER_DN_MATCH=YES)))
start_date: "2024-04-09T12:12:34.898765Z"
advanced:
    skip_flashback_retention_checks: true
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-02-01T17:08:49Z"
          enc: CiQAdmEdwu+udGkiZbfnnE8djh5o4P8p4Rm3WeXcN0XpcDF4sewSSQCVvC1zSqNDZIN7J2EPjuvJM4ILtloOm9w/OGsE4YwB2qH+sKsDDBYuIDDXtHml6w4wG0iksPY1Yxty0casvU6v02mfM3QOvyk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-25T12:01:38Z"
    mac: ENC[AES256_GCM,data:4KCkxaYmlNDU5wlXVdk57cJeTfxCukXwrz1dcdbqd8NEeeWd4f3Ut7T79522dwH20Nt+uH1FDl+wNRcvE/rHLHPFdSyRktW5pU0r9sg3Odj9n67zmKMy9LGroGZmoOJRnbOZjC2wBRQOcQ9gyOndLIICOdMo02y9liCAVpptPJc=,iv:Tkgy/hI0gR9vYg4hRR1GfbCGYRwHx9QIM/ctAllQOWA=,tag:FTWb2VQKhxKla7WDlA+kzQ==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
