name: Common Setup Steps
description: Implements common setup steps of all connector workflows

inputs:
  github_token:
    description: GitHub token to use.
    required: true
  gcp_project_id:
    description: GCP Project for which to set up a service account.
    required: true
  gcp_service_account_key:
    description: GCP Service account.
    required: true

outputs:
  tag_sha:
    description: Short tag of the commit SHA1
    value: ${{ steps.determine-sha-tag.outputs.tag }}

runs:
  using: "composite"
  steps:

    - name: Determine current SHA tag.
      shell: bash
      id: determine-sha-tag
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        echo "tag=${TAG}" >> $GITHUB_OUTPUT

    - name: Download latest Flow release binaries and add them to $PATH
      shell: bash
      run: |
        ./fetch-flow.sh
        echo "${PWD}/flow-bin" >> $GITHUB_PATH
    
    - name: Login to GitHub package docker registry
      shell: bash
      run: |
        echo "${{ inputs.github_token }}" | \
          docker login --username ${{ github.actor }} --password-stdin ghcr.io

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - name: Create docker network flow-test
      shell: bash
      run: docker network create flow-test

    - name: Authenticate with GCloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.gcp_service_account_key }}

    - name: Set up GCloud SDK
      uses: google-github-actions/setup-gcloud@v2