[virtualenvs]
# This configures Poetry to create virtual environments inside each
# module (i.e connector), instead of creating one that you have to constantly
# recreate and switch between. 
in-project = true
