credentials:
    client_id: 1206051774640962
    client_secret_sops: ENC[AES256_GCM,data:Z98pdnbQnXYKgxypuTpbLjqgktpA5qLtubE943kqnHU=,iv:fNyu4eB75NuiwG4LrJvbjTmcxJb2vJ12D+T6MD0eml0=,tag:kWgL3UN09E1T8WWRwkfMmQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/helpful-kingdom-273219/locations/us-central1/keyRings/dev/cryptoKeys/CI-estuary-flow
          created_at: "2023-11-28T23:38:42Z"
          enc: CiQAW8BC2JdbMcChHEFwcOUdD3LZieScs7Ki93ea5JOYgNRE5JQSSQD00UdDcWzhjXIIPbGZ+trpVuJVsY5wpZfEu9M8VLIw8j3RdlCJHf9VtiaPaJxDsklofUjsKkZyOGcOSA/2bCh0eIHJ63zPmoM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-12T16:17:06Z"
    mac: ENC[AES256_GCM,data:1SRSC0FMK5ECu8LufxQMU2/tvR+FLbTrf2KqXFPuM0WhpSUTBsOe1BF3fDANDp7nUryF8//Gzkohjy+6L+N0Wt1ySPZ+ea0/bOFMX3ljIylg8UDcHTYQeo3m8aakOMbb0R4OVo5ageT3AHnnLDCAdnGzUAzcHuqiEy3nXbHorg4=,iv:VdUmnRnGZ5rH5BDHK5v59fPPIvhoxupbSOKDT9VcQiQ=,tag:fwuViOEQdnWFOIsc3TnxGA==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
