credentials:
    client_id: 1206051774640962
    client_secret_sops: ENC[AES256_GCM,data:0o6XBkERucbt0PvDLxg0nB+XM6Vqap+tnK3awcvPIts=,iv:z8MygzAVfx9fSyyGPNAM1MH5q1ZRydKSu3+hsGyfzsw=,tag:ApNaRqfdPCJzLMZZsQRXaA==,type:str]
    access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDMwNjk3MjgsInNjb3BlIjoiZGVmYXVsdCBpZGVudGl0eSIsInN1YiI6MTIwNTg0NjE3MTg3MDQ0NywicmVmcmVzaF90b2tlbiI6MTIwNjIxMTY5NTkzMDkwMywidmVyc2lvbiI6MiwiYXBwIjoxMjA2MDUxNzc0NjQwOTYyLCJleHAiOjE3MDMwNzMzMjh9.EF0PQEyUNmvquY4Kd1RsJ1CAlk-zM_FCe3WqrZktdzA
    refresh_token: 2/1205846171870447/1206051774640962:853855efe43e617bc61c74ecaae037b7
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2023-12-20T11:25:27Z"
          enc: CiQAdmEdwlyZioJtw43BG/YxzPGumPOhI0PX2/MlbiluWJ93wgISSQCVvC1zo1Gor0ujElAy8sLId/5cw3/yQ/XvfQOYkTxx9gB4TdqkAa7zaI3l3Xuec7rx7grnmqXgCSUCc8dNQpOqy6pD7aWsLBU=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-20T11:25:28Z"
    mac: ENC[AES256_GCM,data:/Ji5UafoosGnOUPEpQBUxIlav7yBdlzXKNMG7b7d1itl3bavL/Ux09yCsGfn0ehXTLMeb/DroCxQ87xPeK+4hWhnP/MKYb4d/Krd8FXjGtVSyUpbrkfH6WA5I9H4p+dCtOWGHMFRws9ebvH+zVaDtD/Hs9PZgFhlau8lzTCjtqk=,iv:24kGBzMgPr50YyDrdSUNd9FOsPw38dY9+3ha+YhvlOw=,tag:Am+a6Yah2uiVQ/PYR1jOwg==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.7.3
