credentials:
    client_id: 1206051774640962
    client_secret_sops: ENC[AES256_GCM,data:Z98pdnbQnXYKgxypuTpbLjqgktpA5qLtubE943kqnHU=,iv:fNyu4eB75NuiwG4LrJvbjTmcxJb2vJ12D+T6MD0eml0=,tag:kWgL3UN09E1T8WWRwkfMmQ==,type:str]
    access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDMwNjk3MjgsInNjb3BlIjoiZGVmYXVsdCBpZGVudGl0eSIsInN1YiI6MTIwNTg0NjE3MTg3MDQ0NywicmVmcmVzaF90b2tlbiI6MTIwNjIxMTY5NTkzMDkwMywidmVyc2lvbiI6MiwiYXBwIjoxMjA2MDUxNzc0NjQwOTYyLCJleHAiOjE3MDMwNzMzMjh9.EF0PQEyUNmvquY4Kd1RsJ1CAlk-zM_FCe3WqrZktdzA
    refresh_token: 2/1205846171870447/1206051774640962:853855efe43e617bc61c74ecaae037b7
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/helpful-kingdom-273219/locations/us-central1/keyRings/dev/cryptoKeys/CI-estuary-flow
          created_at: "2023-11-28T23:38:42Z"
          enc: CiQAW8BC2JdbMcChHEFwcOUdD3LZieScs7Ki93ea5JOYgNRE5JQSSQD00UdDcWzhjXIIPbGZ+trpVuJVsY5wpZfEu9M8VLIw8j3RdlCJHf9VtiaPaJxDsklofUjsKkZyOGcOSA/2bCh0eIHJ63zPmoM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-20T10:56:46Z"
    mac: ENC[AES256_GCM,data:/bOAJ6aXiZQ4fTVdWD/LRZAGKEX/POBbY4byOddK2LBQFg/TXt3KU3yXYnIUyAHwkGYsYwlOH2P/amiVA6ten5kBXNxjmLHay87O3TdP2U0Wnrs0Zfw7LR/NhyOV/jfrMCZv04gsg6Lz2V3DBtXyMObh572Yec0hjriErnt6BK0=,iv:Tnb+hNVHy8Hk+Q9AgEz8lDbyU7rOQ2mjbW+SJe1iizQ=,tag:OKPaJb3ZD2OAUwkKCGzb6A==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
