credentials:
    client_id: 1206051774640962
    client_secret_sops: ENC[AES256_GCM,data:Z98pdnbQnXYKgxypuTpbLjqgktpA5qLtubE943kqnHU=,iv:fNyu4eB75NuiwG4LrJvbjTmcxJb2vJ12D+T6MD0eml0=,tag:kWgL3UN09E1T8WWRwkfMmQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/helpful-kingdom-273219/locations/us-central1/keyRings/dev/cryptoKeys/CI-estuary-flow
          created_at: "2023-11-28T23:38:42Z"
          enc: CiQAW8BC2JdbMcChHEFwcOUdD3LZieScs7Ki93ea5JOYgNRE5JQSSQD00UdDcWzhjXIIPbGZ+trpVuJVsY5wpZfEu9M8VLIw8j3RdlCJHf9VtiaPaJxDsklofUjsKkZyOGcOSA/2bCh0eIHJ63zPmoM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-13T13:29:48Z"
    mac: ENC[AES256_GCM,data:++FAZ8ecSlMPDDXwqrWBccpbNaHYpS2jtjkogVPooRwi9sYuKG231CK6gGPohifaN3jRQIsFEmIl/t1rZK4hC/fdsqpZ9RCND/8anfNYwpHMGQd04z/iFZZqzytANSbsEaCl/7hEVEyMF3aXqV/t0sx59y/NMc5SmK2UrmhRadY=,iv:sGnyuuRfJ5kqM0EyuQHgze7dnvY4+iyLM3N1SjuPVJg=,tag:OTe77Ig5jpnavxc/7QzZ8A==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
