credentials:
    client_id: 1206051774640962
    refresh_token: 2/1205846172619387/1206051774640962:9036d277cf22eee315ad8c0cff4386b4
    client_secret_sops: ENC[AES256_GCM,data:Z98pdnbQnXYKgxypuTpbLjqgktpA5qLtubE943kqnHU=,iv:fNyu4eB75NuiwG4LrJvbjTmcxJb2vJ12D+T6MD0eml0=,tag:kWgL3UN09E1T8WWRwkfMmQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/helpful-kingdom-273219/locations/us-central1/keyRings/dev/cryptoKeys/CI-estuary-flow
          created_at: "2023-11-28T23:38:42Z"
          enc: CiQAW8BC2JdbMcChHEFwcOUdD3LZieScs7Ki93ea5JOYgNRE5JQSSQD00UdDcWzhjXIIPbGZ+trpVuJVsY5wpZfEu9M8VLIw8j3RdlCJHf9VtiaPaJxDsklofUjsKkZyOGcOSA/2bCh0eIHJ63zPmoM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-12T21:54:43Z"
    mac: ENC[AES256_GCM,data:lBAyacheeGS1WPBqIUyT3XIQJkuB9w8xyZqUguT7F4Tjv3LNxqrzxpQfGyC7X/G2PR3ILMLm+slARo2h7mKZ6W8T7o4eGVXLkY5WEl3kmtz8eVhxOF0ONUHQ/2WPPtwG0U1dTqP+CBgMVb5ADqtwomJ2IQUotfjYdEcPy4sl1sA=,iv:80a1aTdyFVXskYf0mBf3MaMmxPzLy30yvQyHWixEsck=,tag:Y90gGtxdWEdQw8QOlBHXZA==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
