credentials:
    credentials_title: OAuth Credentials
    client_id_sops: ENC[AES256_GCM,data:4zvhzqLqlrH9kfG8aOv9Z960WA==,iv:9gsrUatYhVZpHPP1u4VgOHz1Rzfc3vr8SncWC+eKJvo=,tag:bw36mJhjiO40jJ0BHtL5BQ==,type:str]
    client_secret_sops: ENC[AES256_GCM,data:BnKTBIBkoAumYyt46qCDjFo0Y9E2kvA=,iv:6dfyItaxBZ62jpNmL6L7wwpP7TWtStJTmsOltVA7PlE=,tag:FqmVRuqk8vjWSeeYUVHeEQ==,type:str]
subdomain: mylookerdomain.com
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-07-26T15:53:37Z"
          enc: CiQAdmEdwpmP0/Kcv6L1SnM3nPbsYLywIaUeOL1mz7cZjFUwWt0SSQD5lVw43Of1YI96anxUVo7d7ALi0DYnCNvxTHCgHX5ZeDBPlfXwLNpmYb6y3hJSsHG7NupwDQT/qIpUvlqQnq5IVkgJEFHPU1s=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-19T21:39:34Z"
    mac: ENC[AES256_GCM,data:5dRAJX7tKYkaEuH6AUxeaG/6s9ppxRbFCfwhVHd4iYhTmN7LiIFni3CESYRdWuIPVcaoIs9rFO9hpM59eEG3PVdyZF/yA2V50YWnrjEn4vwql7w/ED9LKkXhi/q3uU6GcyhUKCSOY+rQjOoHljiud5Zyp2Y0YeN9zR3I6XGRMD8=,iv:wNpuQUkU4JA0Rn8aBTovB1Vp/0pSNhzET4p8QR2W9Zk=,tag:3XNDU8uxhw+BiNq5Y3pA4g==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.9.0
