# credentials:
#   auth_type: basic
#   username: your-zuora-login-email@example.com
#   password: your-zuora-password
# base_url: https://rest.sandbox.eu.zuora.com
# start_date: "2025-01-01T00:00:00Z"

# credentials:
#   auth_type: client_credentials
#   client_id: your-zuora-client-id
#   client_secret: "your-zuora-client-secret"
# base_url: https://rest.sandbox.eu.zuora.com
# start_date: "2025-01-01T00:00:00Z"