services:
  cratedb:
    image: crate:6.2
    ports:
      - "4200:4200"
      - "5432:5432"
    networks:
      - flow-test
    environment:
      - CRATE_HEAP_SIZE=2g
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:4200/"]
      interval: 2s
      timeout: 5s
      retries: 30
    deploy:
      resources:
        limits:
          memory: 4g
networks:
  flow-test:
    name: flow-test
    external: true

