services:
  cratedb:
    image: crate:latest
    ports:
      - "4200:4200"
      - "5432:5432"
    networks:
      - flow-test
    environment:
      - CRATE_HEAP_SIZE=1g
networks:
  flow-test:
    name: flow-test
    external: true