//go:build ignore

// Writes tables_gen.go from tpcds.sql, the TPC-DS DDL from the dsdgen fork.
// Run with `go generate`.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strings"
)

// The sales parent's dsdgen process emits the returns tables. The DDL says
// nothing about this, so it lives here.
var parents = map[string]string{
	"store_returns":   "store_sales",
	"catalog_returns": "catalog_sales",
	"web_returns":     "web_sales",
}

// dbgen_version describes the generator run, not the benchmark schema.
var skip = map[string]bool{"dbgen_version": true}

var (
	reTable  = regexp.MustCompile(`(?is)create\s+table\s+(\w+)\s*\((.*?)\)\s*;`)
	reColumn = regexp.MustCompile(`(?i)^(\w+)\s+(integer|date|time|char|varchar|decimal)(\([\d,\s]*\))?\s*(not\s+null)?$`)
	rePK     = regexp.MustCompile(`(?i)^primary\s+key\s*\(([^)]*)\)$`)
)

var kinds = map[string]string{
	"integer": "kindInteger",
	"decimal": "kindDecimal",
	"date":    "kindDate",
	"char":    "kindString",
	"varchar": "kindString",
	"time":    "kindString",
}

type col struct {
	name, kind string
	notNull    bool
}

type table struct {
	name string
	cols []col
	key  []string
}

func main() {
	src, err := os.ReadFile("tpcds.sql")
	if err != nil {
		fail(err)
	}
	var tables []table
	for _, m := range reTable.FindAllStringSubmatch(stripComments(string(src)), -1) {
		var t = table{name: strings.ToLower(m[1])}
		if skip[t.name] {
			continue
		}
		for _, item := range splitTopLevel(m[2]) {
			if pk := rePK.FindStringSubmatch(item); pk != nil {
				for _, k := range strings.Split(pk[1], ",") {
					t.key = append(t.key, strings.ToLower(strings.TrimSpace(k)))
				}
				continue
			}
			cm := reColumn.FindStringSubmatch(item)
			if cm == nil {
				fail(fmt.Errorf("table %s: cannot parse column %q", t.name, item))
			}
			t.cols = append(t.cols, col{
				name:    strings.ToLower(cm[1]),
				kind:    kinds[strings.ToLower(cm[2])],
				notNull: cm[4] != "",
			})
		}
		if len(t.key) == 0 {
			fail(fmt.Errorf("table %s has no primary key", t.name))
		}
		tables = append(tables, t)
	}
	sort.Slice(tables, func(i, j int) bool { return tables[i].name < tables[j].name })
	if len(tables) != 24 {
		fail(fmt.Errorf("expected 24 tables, parsed %d", len(tables)))
	}
	var names = map[string]bool{}
	for _, t := range tables {
		names[t.name] = true
	}
	for child, parent := range parents {
		if !names[child] || !names[parent] {
			fail(fmt.Errorf("returns mapping %s -> %s names an unknown table", child, parent))
		}
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by gen_tables.go from tpcds.sql; DO NOT EDIT.\n\npackage main\n\n")
	b.WriteString("var tables = []*tableDef{\n")
	for _, t := range tables {
		fmt.Fprintf(&b, "\t{\n\t\tName: %q,\n\t\tColumns: []column{\n", t.name)
		for _, c := range t.cols {
			fmt.Fprintf(&b, "\t\t\t{Name: %q, Kind: %s, NotNull: %v},\n", c.name, c.kind, c.notNull)
		}
		fmt.Fprintf(&b, "\t\t},\n\t\tKey: %#v,\n", t.key)
		if p := parents[t.name]; p != "" {
			fmt.Fprintf(&b, "\t\tParent: %q,\n", p)
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	out, err := format.Source(b.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile("tables_gen.go", out, 0o644); err != nil {
		fail(err)
	}
}

func stripComments(s string) string {
	var lines = strings.Split(s, "\n")
	for i, l := range lines {
		if j := strings.Index(l, "--"); j >= 0 {
			lines[i] = l[:j]
		}
	}
	return strings.Join(lines, "\n")
}

// Splits on commas outside parentheses so decimal(p,s) and primary key (a, b)
// stay whole.
func splitTopLevel(body string) []string {
	var out []string
	var depth int
	var cur strings.Builder
	for _, r := range body {
		switch {
		case r == '(':
			depth++
		case r == ')':
			depth--
		case r == ',' && depth == 0:
			if s := strings.TrimSpace(cur.String()); s != "" {
				out = append(out, s)
			}
			cur.Reset()
			continue
		}
		cur.WriteRune(r)
	}
	if s := strings.TrimSpace(cur.String()); s != "" {
		out = append(out, s)
	}
	return out
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen_tables:", err)
	os.Exit(1)
}
