credentials:
    credentials_title: OAuth Credentials
    client_id_sops: ENC[AES256_GCM,data:U+E+Y+DvaoY6XDINrNV/X/AxaOFVKyFXZofeVXRSEH3UvZkk2GJSD48tIB0=,iv:8tmHqMd39Pv7GDXzWUl09BjIaIHmKtKPx3UAsKQU0w8=,tag:BVKjhn0qELCpROeU3fgb6A==,type:str]
    client_secret_sops: ENC[AES256_GCM,data:scw7arwrN9k+uwTiefC5PgfhLYajAy17X0Nfo/6pdZj4N1BPUuyN+KhrxQ==,iv:xjmGl6F7+6l0AN5cEbV0jiAPpM9lFjWTXODmPWq2WVM=,tag:wwPMykqXsqXq4t1Z8x/mXg==,type:str]
    refresh_token_sops: ENC[AES256_GCM,data:GbVny6jC5rYBqddf3SziSvc4aJWr/Gw6b2NHOjwe1oMIx0+pm+IXzEcaRQ==,iv:erGYfkVhzgjishsuf4FDGZvh2+BcjIrJHM/2qSi/lQA=,tag:VHh1NpbxuPH67UOVjWoPkw==,type:str]
start_date: "2025-02-01T00:00:00Z"
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-07-26T15:53:37Z"
          enc: CiQAdmEdwpmP0/Kcv6L1SnM3nPbsYLywIaUeOL1mz7cZjFUwWt0SSQD5lVw43Of1YI96anxUVo7d7ALi0DYnCNvxTHCgHX5ZeDBPlfXwLNpmYb6y3hJSsHG7NupwDQT/qIpUvlqQnq5IVkgJEFHPU1s=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T15:49:58Z"
    mac: ENC[AES256_GCM,data:zadNeDX/YqLXiS+mUOA12+yMgx2QJJ/njlv3Ntp2y8gHdqWjIOVXKBFC19xcSJepuzj1I0+DI/7qQ7tyt0xhehvcQ/2ywFbK7njTcRGQOcl8as46dY9E7hE6TaKZU6twQ+a/X02kMShktvAPgsWq+eXNh9H5tMMSjpXrlImqV5g=,iv:bjn2cxljC0pWviatLSaKZo4ekpWorRbz7XnuhA1BN5U=,tag:8lYIJtyRTWlLYddLrnoLMw==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.7.3
