[tool.poetry]
name = "source-linkedin-pages"
version = "0.1.0"
description = ""
authors = ["Pedro <pedro@z33dd.com>"]

[tool.poetry.dependencies]
python = "^3.11"
estuary-cdk = { path = "../estuary-cdk", develop = true }
airbyte-cdk = "^0.52"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-snapshot = "^0.9.0"
ruff = "^0.3.4"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
