---
$schema: "http://json-schema.org/draft-07/schema#"
type: object
properties:
  id:
    type: string
    description: The ID of the application property. The ID and key are the same.
  key:
    type: string
    description: The key of the application property. The ID and key are the same.
  value:
    type: string
    description: The new value.
  name:
    type: string
    description: The name of the application property.
  desc:
    type: string
    description: The description of the application property.
  type:
    type: string
    description: The data type of the application property.
  defaultValue:
    type: string
    description: The default value of the application property.
  example:
    type: string
  allowedValues:
    type: array
    description: "The allowed values, if applicable."
    items:
      type: string
  _meta:
    type: object
    properties:
      row_id:
        type: integer
    required:
      - row_id
additionalProperties: true
description: Details of an application property.
x-infer-schema: true
