credentials:
    credentials_title: OAuth Credentials
    client_id_sops: ENC[AES256_GCM,data:fMXpKq4TrDG9vbkRFa7EYhOsdk6FtTLLT+jU5hokrHEB2FF8h39CquHiOp0+El0Mg/4zQMTdJ5wDp90WKSPa9yxzaMAi97ExkqfNWPM2FNAK2KmAYg==,iv:8lNVaJITypPnTuUZM4kMXUMdJglGFdkDYGNGhyPsxVU=,tag:yT1ENGiQzGZKM8DCT8gS0g==,type:str]
    client_secret_sops: ENC[AES256_GCM,data:jJgwo0E280bY9JApzBDCXuFaEbnnMMhtT0zYrwybJcOtZc+6RXNkxtQSbXvw9DpAAC6jbGEXMMc6yONx4y21ww==,iv:KqFuPgJzjVgDdOdKGRrnvEda/ZUUBvvlBjUcEdiALeg=,tag:M2RoEtnWixP86GOv/uwMIw==,type:str]
    refresh_token_sops: ENC[AES256_GCM,data:98PiAbyj/foKifMeNSeWZV70de1M19iUO11tFAOzIyI4LXsQIzo1ToZXEawa5BkgJvYbkBhQ9QMgUiepDq1x2Gi9cOse7T7G5fqp5vy2BTwEu0bHHqRh,iv:3iJwqPx7JOtF7hrtIxvzGSg4jN58RWoXy+MFvGaS13E=,tag:JWXniDmarDcd1J1buil6+g==,type:str]
    instance_url: https://estuary2-dev-ed.develop.my.salesforce.com
is_sandbox: false
start_date: "2024-07-26T00:00:00Z"
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-07-26T15:53:37Z"
          enc: CiQAdmEdwpmP0/Kcv6L1SnM3nPbsYLywIaUeOL1mz7cZjFUwWt0SSQD5lVw43Of1YI96anxUVo7d7ALi0DYnCNvxTHCgHX5ZeDBPlfXwLNpmYb6y3hJSsHG7NupwDQT/qIpUvlqQnq5IVkgJEFHPU1s=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-09-16T23:06:30Z"
    mac: ENC[AES256_GCM,data:AEOzSXqcNMKbtJrgz31vQDFfMWSruPTxgja3h0X80fyWZ2CcUZGvh+4hbxhcJct7UZiG0tNMNWFiZKcAV68Peh4L4I2+Y8jrvSNrCIQ4uqMKeq2YU4CH0MVToLSRQZPJzIdIAqGhLfpG9xfn0+vwYkb2A2z/CHIttj+weSW0FYA=,iv:V+y5OcfL5jvaO3wEmM+oXFS1fZ5pJqmgyNCHp56sru8=,tag:FkFT+9CENdznKwu1QKXCOw==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.9.0
