services:
  bigtable:
    image: "google/cloud-sdk:latest"
    command: >
      gcloud beta emulators bigtable start
      --host-port=0.0.0.0:8086
    ports:
      - "8086:8086"
    networks:
      - flow-test
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/8086"]
      interval: 2s
      timeout: 2s
      retries: 30

networks:
  flow-test:
    name: flow-test
    external: true
