[tool.poetry]
version = "0.1.0"
name = "source-pendo"
description = ""
authors = [ "Alex Bair <alexb@estuary.dev>",]

[tool.poetry.dependencies]
airbyte-cdk = "^4.4.2"
estuary-cdk = {path="../estuary-cdk", develop = true}
python = "^3.11"
pydantic = "^2"
pytz = "^2024.1"
requests-futures = "^1.0.1"
setuptools = "^70.0.0"

[tool.poetry.group.dev.dependencies]
debugpy = "^1.8.0"
mypy = "^1.8.0"
pytest = "^7.4.3"
pytest-insta = "^0.3.0"
requests-mock = "^1.11.0"
pytest-mock = "^3.12.0"
freezegun = "^1.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
source-pendo = "source_pendo.run:run"