path: /test
credentials:
  refresh_token_sops: ENC[AES256_GCM,data:scYZmt6pimhyZBcFjPWBvmHYASmQe7RZSN7p/5lo/bs9lrVhJCo34ApT7QEBSINhFa4bJYZol+ryGNFHkbhrGg==,iv:AJxWexn7BlzYrwyKdAAOSTnok8Afvr8yDAYkv0WZbQM=,tag:LFbl7Oe7B5C2RlIQYQY2zQ==,type:str]
  client_id_sops: ENC[AES256_GCM,data:4McqqCG+KsUkFQG01Njz,iv:8ym+Ve1zNcIL0QT8UBPeX5LNzdEXvAS2iye7WUqCqmE=,tag:SMZEHAx/sNiGUjtb7aDV1Q==,type:str]
  client_secret_sops: ENC[AES256_GCM,data:64zwI1cEeLc4uV/oCo2t,iv:yEvf5iihXImotqX4BNTJXgmZzpjTPi3jy9pS7yK0Lgo=,tag:Vj68cAoDAmppZ/j4Wvx83g==,type:str]
sops:
  kms: []
  gcp_kms:
    - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
      created_at: "2024-05-02T13:22:36Z"
      enc: CiQAdmEdwq4EDQ8XOc33yLpeeBJcvUTS+/MGojnGkfm0E3BWMzoSSQCSobQj93XXsS2ePY3uvL1iWP/yrtQ+AAwoCbSWvvXRnMSNRE2Byo7KaFIzvTDVAWRWUnGol/KMW8Zf9NfAq/RSZNdVrVbYnaE=
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2024-05-02T13:22:40Z"
  mac: ENC[AES256_GCM,data:MIA7D3m9g+b51+0bRJwqAGSpD8Aa+Nl8KVTS7FlwZ/9y9wacjnvQ0DFcLu1pUuTvpDizCCj6eaL1IEpzXK03OypP9NhPPJdwIV+WFnGMrMo0DqZ4EBFxwkZ1vGDtM1UCta8Id87UTSz3ela5Y6qcHm/tJehDcKxb+fpx0A3LTkI=,iv:FaFrcXHGPK2gL24MMDO98NGp8ToWSS5xPcT1ZUH2Gdk=,tag:JqQG8xHjbt54beC+t6/LLg==,type:str]
  pgp: []
  encrypted_suffix: _sops
  version: 3.8.1
