credentials:
    auth_method: oauth2.0
    client_id_sops: ENC[AES256_GCM,data:3nndJkjHvaslFFHzMNO2mIARTk/eNhlCmq3oXGGMyRkz1J9O,iv:6zJ2yoxivuSqkfyEWTq1mMJsNUggroq5l1cgjuS5a80=,tag:dqV9JXRe1sV6UqqIrhwIAQ==,type:str]
    client_secret_sops: ENC[AES256_GCM,data:1Pyk8eLTm9podLQ9bBlCG7pyN9Pqj7qWB8iWrz8alAa0rXfmPVRs2Q==,iv:kkQKCsVMOyb8FTN1wnHD8sG7SoBbtdGLFvGDWniOXyo=,tag:lBwi8yEsfiQ+HZZF9ge99Q==,type:str]
    tenant_id: f8cdef31-a31e-4b4a-93e4-5f571e91255a
    developer_token: 1072JQDAYU870189
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/helpful-kingdom-273219/locations/us-central1/keyRings/dev/cryptoKeys/CI-estuary-flow
          created_at: "2023-12-08T17:37:54Z"
          enc: CiQAW8BC2Crpufkdcy4tzxq0rVLeYpjqd27n2/jZpi52WjP+RGQSSQD00UdD8hJCumY0Ftz7ZNEV+4l6/X7Z6AUG/ef9kRgna2g4BZP4vJms0a8jNu98MKBWWP6pjhRL99cgifu6l4152UMCieFjrN0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-11T15:53:47Z"
    mac: ENC[AES256_GCM,data:1hHjwan7olA3M3eg6CC5/6y/C7azaLXMRoTTl68pYLn+x5FtJf/QNRDG+5erHPQybObi4rskJxxZfF5OPHxUtxrO6Mik5/Chal+J07Xb9WtpJobYjdrBTCYf1HIlg+o9ECE4c4EfG57EgUoHq4uZXVLio1wUpo8YpJWTTl5SEjM=,iv:JEafcsj26m+9gK63RZaQ3ShNOIGtap08U+XLYUqo1jw=,tag:NmlzfZOiu6amyAAQ4apx5w==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
