address: estuary-connector-test.076183946664.us-east-2.redshift-serverless.amazonaws.com:5439
database: dev
password_sops: ENC[AES256_GCM,data:kcluRuHji9ckwA==,iv:SRE4ZtcVSFOPHikXJhXEFF5xXcMa7kTbPUCqmgBqbQ0=,tag:mjqomw4ihdngh9yzvIKTkg==,type:str]
user: estuary
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-02-01T17:08:49Z"
          enc: CiQAdmEdwu+udGkiZbfnnE8djh5o4P8p4Rm3WeXcN0XpcDF4sewSSQCVvC1zSqNDZIN7J2EPjuvJM4ILtloOm9w/OGsE4YwB2qH+sKsDDBYuIDDXtHml6w4wG0iksPY1Yxty0casvU6v02mfM3QOvyk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-21T18:27:56Z"
    mac: ENC[AES256_GCM,data:qOvbHToK149HMRCuISduRWQVRcprc1dzOABRGO6iK5NX5w2o312hCDJ4rZM1ueoR+185CTjsswpRmHoVzjIxW71CvzZlj9l0mn1kV8KLRrYM81JlNkKGbH2TqI7foMFOkcSoMJOtSLsBO8Ik/WxCt1IlswIDSnBTz+WeMpW1fiY=,iv:ff0H1pfdz5CrW+5gewMuvHdGcQf/SSYUFHMIw2iMUSM=,tag:gKda/A4lT+UO1TY1vquh7g==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.9.4
