attribution_window: 5
credentials:
    api_secret: ""
    option_title: Project Secret
date_window_size: 30
project_id: 1
project_timezone: US/Pacific
region: US
select_properties_by_default: true
start_date: "2012-07-10T00:00:00Z"