services:
  spanner:
    image: 'gcr.io/cloud-spanner-emulator/emulator:1.5.44'
    platform: linux/amd64
    networks:
      - flow-test
    ports:
      - "9010:9010"
      - "9020:9020"

networks:
  flow-test:
    name: flow-test
    external: true
