credentials:
    credentials_title: Username & Password
    username: FLOW_TEST
    password_sops: ENC[AES256_GCM,data:Srw4X8Zs+68pGvoo,iv:Ui08EAHj4P9u35TtINxZkOf+vjWmZZ8dUA5wmmpbA0Y=,tag:E3wDxkllizTG4HsyGJQSqA==,type:str]
networkTunnel:
    sshForwarding:
        sshEndpoint: ssh://ec2-user@3.145.9.217
        privateKey_sops: ENC[AES256_GCM,data:/dVvJURinrpvqZZHkfjbw2V4myN3NW5zvhaOdS6F3NMqFbJzKMX/IQprXx7oDog/6QuRlsotn+Vbh9v6uVjAOlonzlWmvNgtuaHU83FHD+Nb62aa0kWCQcZCFYsp29pn8fcEDsVQ/K16a+sRLJLbmxz12pMqn/FQBb7ylyKXrGCWcwdq4jqVYH1PLTP99QamG52P/V4ZHCbtXYwktZjvgjaaf1NhYaikdu13g+Vyld8+nG+67LjMutXSz03lpJuPF31PArz3KkiYDeMHcFYyyn51uQ6l/GAKDFLTW+L85ZdVIi9J7hWIWNNagsPoZojAZKX2/9nc/TG3HnWF5hR6riaIKjrKswXXD/uMa9NHspDLxucp2S3UyZC4GbJu3xl8ByFauCmoTotsnW0PHfIKbhZJeoXoSRdiB5ViPL0nHEKza51U3jGa8UycZj/dnTM+bJuOvWUarYKpzBkjrKnu3EAA/Okwwkl0O+aEEX3Nl8At/AGV6Bcb/mTaOT72/nn3NesMaFn3HUZeN9bo/xvAcBgGQOgbjj18zgXugy6HAZP9AW2FZRWTsVOPEUEdu+9F,iv:lT5BmCRB95q74+nGh4jvL06MthkdaaDOCc4I64nvpn0=,tag:Tit5MAN51SkmKKvmg8Emog==,type:str]
address: database-single.chqpmndqvzby.us-east-2.rds.amazonaws.com:1521/DATABASE
advanced:
    backfill_chunk_size: 100
    skip_flashback_retention_checks: true
    schemas:
        - FLOW_TEST
        - FLOW_CAPTURE
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-02-01T17:08:49Z"
          enc: CiQAdmEdwu+udGkiZbfnnE8djh5o4P8p4Rm3WeXcN0XpcDF4sewSSQCVvC1zSqNDZIN7J2EPjuvJM4ILtloOm9w/OGsE4YwB2qH+sKsDDBYuIDDXtHml6w4wG0iksPY1Yxty0casvU6v02mfM3QOvyk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-23T11:51:21Z"
    mac: ENC[AES256_GCM,data:avf26248vNH3EvD26Pp8CdFgGlV1nYJdFHrJfx450onMobO5ybOtHKToVJLUYWIno16PNUn4VUf3bLRZtTTYf1U0y8W88U9n6fP1zJEkZnUpuK/4jpFag0eqlg+vOv8l7HzA4u9ZBs9Hp39nEQBImGl9TDFb8LlBi1sip27Hmtw=,iv:566KyZ4Z+pcRldgX+ETrm1uxKA3NarGuR1P8QIZQ+1g=,tag:rUq+4JwFqr21zqEHA4XAhw==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
