credentials:
    credentials_title: Email & API Token
    username: alexb@estuary.dev
    password_sops: ENC[AES256_GCM,data:O5rJ/sJWpk8DxPQn4Q==,iv:OVelKHmeAE8GBVSr9JyQ8BUhfjQbMQhO9MrIyRXUq/E=,tag:nhNdx9dckVg3GM8M+AC1EQ==,type:str]
start_date: "2025-05-22T00:00:00Z"
domain: dontchangethisdomain.notareal.jira.domain
projects: ""
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-07-26T15:53:37Z"
          enc: CiQAdmEdwpmP0/Kcv6L1SnM3nPbsYLywIaUeOL1mz7cZjFUwWt0SSQD5lVw43Of1YI96anxUVo7d7ALi0DYnCNvxTHCgHX5ZeDBPlfXwLNpmYb6y3hJSsHG7NupwDQT/qIpUvlqQnq5IVkgJEFHPU1s=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-06-11T15:02:27Z"
    mac: ENC[AES256_GCM,data:Rh7TR3cCvcSFTxIo/BCho+gn50wv8sSQsjcfKIwXikzkhWCfCX4PVTYyg3Tde5uypvm9Mocb2okFHeGjRsY5TR3h/V8q/LG9cwmtz+TRuocizvLHGo4nn8QzTg7ODtR1nPsHgUePDSC48vQ0kA0KH2F/g27jOf9JiACaNFvgs44=,iv:sRPx4qNTQUl+TcjDv1cjLgrnVhKROT+cw1sR3D3RIvs=,tag:n68rwGJRl1p1f16tkXURNQ==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.9.0
