credentials:
    access_token_sops: ENC[AES256_GCM,data:JLPRanyakzcBb8AMFIs0I+g5D1w7obPxQXoCi6wSV5Ot66sX2phfn1pCE34LcmTxlokAS7CSDUdAyAsw36Eltb6iZGfkHBDtJ2S3BGGz2HEen8SgnkapNkfjOJfjkvOSEFzcH/af7w1OIJQ=,iv:Qt59fJGiz9JoHltxkA7EPqWHChjB+ppXMa3izz7UqBk=,tag:mYZWNrsOQJWH7Rc+rR+u2Q==,type:str]
start_date: "2010-01-01T00:00:00+00:00"
capture_connected_accounts: true
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2025-03-07T21:20:45Z"
          enc: CiQAdmEdwqj7wNLmtF7bRmbZp/HTg7GH0fyXZ/0sd+HAJylZ5Q8SSQCtUdBGNtHMe91hNh4GvgqEh8NOsOj3n8uAPVtnLmgyuetL9N7hBnXzXae6bkOaZj/OehhQjTPRJrfAjJBe/FBoTPLHxMO9gbw=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-07T21:20:45Z"
    mac: ENC[AES256_GCM,data:I3mhDLPF07sAGViAGYXSZMx//Pp3pJOoFARqrEagfoR+96evSb845q818SxqEJeUVkPF0Weue6f9FwSyuAUHpu9+LPYAZrVixHr/HeFEFLfvCe/yFf0fTXO7GhsKdGiucqzrd6nRc6/byVyka75H86MzCsdrOW5zVyfwXPr0jUM=,iv:HguMQ+BM+H2AIpdUMlWW9oDWRL4zzB+JZYTLC7xQblU=,tag:B1AV7zVrP5hQ7kMrUe6m7w==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.9.4
