---
$schema: "http://json-schema.org/draft-07/schema#"
type: object
properties:
  id:
    type:
      - "null"
      - string
  createdAt:
    type:
      - "null"
      - string
    format: date-time
  updatedAt:
    type:
      - "null"
      - string
    format: date-time
  archived:
    type:
      - "null"
      - boolean
  properties:
    type: object
    properties:
      amount:
        type:
          - "null"
          - number
      createdate:
        type:
          - "null"
          - string
        format: date-time
      description:
        type:
          - "null"
          - string
      discount:
        type:
          - "null"
          - number
      hs_all_accessible_team_ids:
        type:
          - "null"
          - string
      hs_all_assigned_business_unit_ids:
        type:
          - "null"
          - string
      hs_all_owner_ids:
        type:
          - "null"
          - string
      hs_all_team_ids:
        type:
          - "null"
          - string
      hs_avatar_filemanager_key:
        type:
          - "null"
          - string
      hs_cost_of_goods_sold:
        type:
          - "null"
          - number
      hs_created_by_user_id:
        type:
          - "null"
          - number
      hs_createdate:
        type:
          - "null"
          - string
        format: date-time
      hs_discount_percentage:
        type:
          - "null"
          - number
      hs_folder_id:
        type:
          - "null"
          - number
      hs_images:
        type:
          - "null"
          - string
      hs_lastmodifieddate:
        type:
          - "null"
          - string
        format: date-time
      hs_merged_object_ids:
        type:
          - "null"
          - string
      hs_object_id:
        type:
          - "null"
          - number
      hs_object_source:
        type:
          - "null"
          - string
      hs_object_source_id:
        type:
          - "null"
          - string
      hs_object_source_label:
        type:
          - "null"
          - string
      hs_object_source_user_id:
        type:
          - "null"
          - number
      hs_product_type:
        type:
          - "null"
          - string
      hs_read_only:
        type:
          - "null"
          - boolean
      hs_recurring_billing_period:
        type:
          - "null"
          - string
      hs_recurring_billing_start_date:
        type:
          - "null"
          - string
        format: date
      hs_sku:
        type:
          - "null"
          - string
      hs_unique_creation_key:
        type:
          - "null"
          - string
      hs_updated_by_user_id:
        type:
          - "null"
          - number
      hs_url:
        type:
          - "null"
          - string
      hs_user_ids_of_all_notification_followers:
        type:
          - "null"
          - string
      hs_user_ids_of_all_notification_unfollowers:
        type:
          - "null"
          - string
      hs_user_ids_of_all_owners:
        type:
          - "null"
          - string
      hs_was_imported:
        type:
          - "null"
          - boolean
      hubspot_owner_assigneddate:
        type:
          - "null"
          - string
        format: date-time
      hubspot_owner_id:
        type:
          - "null"
          - string
      hubspot_team_id:
        type:
          - "null"
          - string
      name:
        type:
          - "null"
          - string
      price:
        type:
          - "null"
          - number
      quantity:
        type:
          - "null"
          - number
      recurringbillingfrequency:
        type:
          - "null"
          - string
      tax:
        type:
          - "null"
          - number
  _meta:
    type: object
    properties:
      row_id:
        type: integer
    required:
      - row_id
x-infer-schema: true
