---
bucket: pubsite_prod_rev_01234567890987654321_my_bucket
start_date: "2025-07-24T00:00:00Z"
credentials:
  credentials_title: Google Service Account
  service_account: "{\n  \"type\": \"service_account\",\n  \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\n  \"token_uri\": \"https://oauth2.googleapis.com/token\",\n  \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\n  \"client_x509_cert_url\": \"some_cert_url\",\n  \"universe_domain\": \"googleapis.com\"\n}\n"
