credentials:
    client_id_sops: ENC[AES256_GCM,data:OId3D9HuY6+HC6uZgYIJu3tn7qpIC09aj9lfU0SA5/PQM8fW,iv:HYu66hbaYZsGhhd7bmnsbX17JcofDU85bT6G+gIxTyU=,tag:0kKvAOeraz85XEpLiTKnLw==,type:str]
    client_secret_sops: ENC[AES256_GCM,data:sUfbjsVC2txJG0E/DGhl91c6C2NmkUf8p/WCGFBQDVyIs+uU,iv:XmW0ZgF8i+a0p6Htjdj47FAgzAZLjhE1Grp4NFlHml4=,tag:qntEOKkL+/R5bbGuaYfgXQ==,type:str]
    credentials_title: OAuth Credentials
    refresh_token_sops: ENC[AES256_GCM,data:Yq2q9VSlWmdhyNHNWcm2E23S6YnEqZPeb3VgIJc9iUgaIvtZ,iv:r1hL40FdQxcp89vRYZPj+ecDH7sCz/xC1mDHyN2tyQ0=,tag:xdHohKfwDQF9J6KOYguGMg==,type:str]
    token_expiry_date: "2024-02-01T17:01:21.703Z"
capturePropertyHistory: true
sops:
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-02-01T17:08:49Z"
          enc: CiQAdmEdwu+udGkiZbfnnE8djh5o4P8p4Rm3WeXcN0XpcDF4sewSSQCVvC1zSqNDZIN7J2EPjuvJM4ILtloOm9w/OGsE4YwB2qH+sKsDDBYuIDDXtHml6w4wG0iksPY1Yxty0casvU6v02mfM3QOvyk=
    lastmodified: "2026-05-28T19:06:27Z"
    mac: ENC[AES256_GCM,data:hF4nk4zDgqvY4QZolUtjsJ90vJJ9Y0qCvqtUxg1o+BkeBsuWZgiyKdnqUVEA7vRSX0M8aTtu7kMuNZRZEmuCaZ7jiqrnHq/PpnQ1gjlepjQccGH0ir1o8LZSHw9OhApoYS5XR29K34cXdPRpzfTgnDfkNcU1Fsw6mq+tNFVZ5e4=,iv:eaTuOEHygGhay3mya+VsbnJpwKhpGrrT2Jn/z/GZgX4=,tag:pK94WMQshBoEs/oiCVQjYg==,type:str]
    encrypted_suffix: _sops
    version: 3.10.2
