credentials:
    auth_type: token
    token_sops: ENC[AES256_GCM,data:JLvGUfdIfvDf0qI2/Zr/EDSIP0J9gTxkZ1E7h++YdUQ2l+HYkt+jyCPxwA0ZngYgSKA=,iv:o7v32H+CNTG1m2ye/Je8EqiO3LIqayu3XjoqVMhvJJQ=,tag:if2G5KH3UdJSw6FZXae9kQ==,type:str]
start_date: "2023-04-17T00:00:00Z"
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-03-21T14:36:06Z"
          enc: CiQAdmEdwo9a6M+bUq8DMIWi5qxu279bHJSyQEzHzwjDAG8PTpMSSQCSobQjpCxFWDU3orGpaPl5eKe3slAxPYNZZofFGkHTytinGYQOLwziGp4/ImDjjoCzM0/S42sipLERThX0g6X9JTApvtEQCzI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-22T14:27:47Z"
    mac: ENC[AES256_GCM,data:NSsjfDZPN5blp2mqKaY8Ukf1vvQhh9N2otje+2j5TtqjF83OaWAztinmgq3+ofHFrs4ZGgBUEhvBvDn1L4kV3azCjCKjyKOgJRIa+T9iN8Yq9t6TIEnRN5rsAoZHX/SqzTX1uhEApW6uZWVzKULOYTN947FBEcD3cORW7svNyf0=,iv:pipPcYLzlZpyQfVFsqfEfcRjigh5efTC/gQrlzETeQ4=,tag:2/WDGLJpthMGSwMdUhWZog==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
