credentials:
    api_key_sops: ENC[AES256_GCM,data:IIURp1Gaf5+THmZF1B0AKhptbcTPCeS9/7xw+8SFxBzMi984PUOM3Nncq3acPC/RvgIWrCT4pdzSHcB1R/zNNl8ws4PEDW+ODnXUtWCBx2x6Bw==,iv:PhI5ttX1IW1AWRRs90U/M+HqbnmmXlA62JY3xznrKR4=,tag:NfuJ+ymeguV7MzZrkns5hQ==,type:str]
    auth_method: api_key
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2023-12-19T15:07:57Z"
          enc: CiQAdmEdwqyda0b+TYLkO3MQoGSlmy8yry6FvqHyPpYpQBQt9pcSSQCVvC1zYTvAhOKj0x78KcFbarVr3Q7hucNSkES9WdDQZbOEeuMKWyGunxkZZhDhdGqcc/Jenu34yluHmICLDSVSMvtpgkmFO6A=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-19T15:07:59Z"
    mac: ENC[AES256_GCM,data:8/Ax5IKxPZbU85vpz14Mu1TB/PzhnbVhrIVCAEbB4P2GQ5b3++G2V9XV461KvzasN+13GEw3lxmkpwHsJFlfHgS9Vpj469a57iWiNt4zkW5ehUJuiWRRXAFknjkaAZ/+oTyAygPJaVnncSadKzp+7LrCKeoAG7EkNBIHxfx0cuw=,iv:E7fqz4t2dD8LeReXcBOzK6lioG5TbK36+KJaTZ68PwA=,tag:p7GmQIgtNp1WgtYEu1kA9Q==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.7.3
