[package]
name = "parser"
version = "0.1.0"
authors = ["Estaury <info@estuary.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "*"
chardetng = "*"
csv = "*"
encoding_rs = {version = "*", features = ["serde"]}
schemars = "*"
serde = {version = "*", features=["derive"]}
serde_json = {version = "*", features = ["raw_value", "arbitrary_precision"]}
structopt = "*"
thiserror = "*"
tracing = "*"
tracing-subscriber = "*"
unicode-bom = "*"
url = "*"
uuid = {version = "*", features = ["v4"]}

# TODO: update this depedency spec once we publish the json crate to crates.io
json = {git = "https://github.com/estuary/flow"}
doc = {git = "https://github.com/estuary/flow"}

[dev-dependencies]
tempdir = "*"
insta = "*"
