---
$schema: "http://json-schema.org/draft-07/schema#"
additionalProperties: true
properties:
  account:
    type:
      - "null"
      - string
  amount:
    type:
      - "null"
      - number
  amount_refunded:
    type:
      - "null"
      - number
  application:
    type:
      - "null"
      - string
  balance_transaction:
    type:
      - "null"
      - string
  charge:
    type:
      - "null"
      - string
  created:
    type:
      - "null"
      - number
  currency:
    type:
      - "null"
      - string
  id:
    type: string
  livemode:
    type: boolean
  object:
    type:
      - "null"
      - string
  originating_transaction:
    type:
      - "null"
      - string
  refunded:
    type: boolean
  refunds:
    properties:
      data:
        items: {}
        type: array
      has_more:
        type: boolean
      object:
        type:
          - "null"
          - string
      url:
        type:
          - "null"
          - string
    type:
      - "null"
      - object
  source:
    properties:
      fee_type:
        type:
          - "null"
          - string
      resource:
        properties:
          charge:
            type:
              - "null"
              - string
          type:
            type:
              - "null"
              - string
        type:
          - "null"
          - object
    type:
      - "null"
      - object
required:
  - id
title: Application Fees Schema
type:
  - object
