version: "3.7"

services:
  # Not really a db, but calling it that makes it easier to incorporate into our CI system.
  db:
    image: lscr.io/linuxserver/openssh-server:version-9.1_p1-r2
    environment:
      - PASSWORD_ACCESS=true
      - USER_NAME=test
      - USER_PASSWORD=test
    ports:
      - 2222:2222
    restart: unless-stopped
    networks:
      - flow-test
    volumes:
      - type: bind
        source: ../tests/files
        target: /tests

networks:
  flow-test:
    name: flow-test
    external: true
