package main

import (
	"context"
	"errors"
	"fmt"
	"slices"
	"sort"
	"strings"

	"github.com/estuary/connectors/sqlcapture"
	"github.com/invopop/jsonschema"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/sirupsen/logrus"
)

// discoveryChunkSize is the number of tables per chunk in DiscoverTableDetails.
const discoveryChunkSize = 100

// tableIDsInClause builds a parenthesized list of pgx-style row-constructor
// placeholders and the corresponding argument slice, suitable for use in a
// query predicate of the form `WHERE (table_schema, table_name) IN (...)`.
//
// Verified empirically that PostgreSQL plans this row-constructor form as a
// BitmapOr of per-tuple index probes on the relevant catalog index, so this
// should be efficient even on massive catalogs.
func tableIDsInClause(tables []sqlcapture.TableID) (string, []any) {
	var placeholders = make([]string, len(tables))
	var args = make([]any, 0, len(tables)*2)
	for i, t := range tables {
		placeholders[i] = fmt.Sprintf("($%d, $%d)", 2*i+1, 2*i+2)
		args = append(args, t.Schema, t.Table)
	}
	return strings.Join(placeholders, ", "), args
}

// ListTables returns identifiers for all tables visible for capture after the
// connector's configured discovery filters are applied.
func (db *postgresDatabase) ListTables(ctx context.Context) ([]sqlcapture.TableID, error) {
	tables, err := listTables(ctx, db.conn, db.config.Advanced.DiscoverSchemas, db.config.Advanced.CaptureAsPartitions)
	if err != nil {
		return nil, err
	}

	// Exclude the watermarks table from discovery. The connector may write to
	// it during backfills but it should never be surfaced as a bindable source.
	var watermarks = db.WatermarksTable()
	tables = slices.DeleteFunc(tables, func(t sqlcapture.TableID) bool {
		return sqlcapture.JoinStreamID(t.Schema, t.Table) == watermarks
	})

	// Exclude tables not in the configured publication unless the user has
	// explicitly opted in to discovering them.
	if !db.config.Advanced.DiscoverUnpublishedTables {
		publicationStatus, err := listPublishedTables(ctx, db.conn, db.config.Advanced.PublicationName)
		if err != nil {
			return nil, err
		}
		tables = slices.DeleteFunc(tables, func(t sqlcapture.TableID) bool {
			return !publicationStatus[sqlcapture.JoinStreamID(t.Schema, t.Table)]
		})
	}

	return tables, nil
}

// DiscoverTableDetails queries the database for detailed schema information about
// the specified tables. The per-table metadata queries are chunked into batches.
func (db *postgresDatabase) DiscoverTableDetails(ctx context.Context, requested []sqlcapture.TableID) (map[sqlcapture.StreamID]*sqlcapture.DiscoveryInfo, error) {
	var tableMap = make(map[sqlcapture.StreamID]*sqlcapture.DiscoveryInfo, len(requested))
	for i := 0; i < len(requested); i += discoveryChunkSize {
		var end = min(i+discoveryChunkSize, len(requested))
		if err := db.extendTableDetails(ctx, tableMap, requested[i:end]); err != nil {
			return nil, err
		}
	}

	// Determine whether the database sorts the keys of each table in a
	// predictable order or not. The term "predictable" here specifically
	// means "able to be reproduced using bytewise lexicographic ordering of
	// the serialized row keys generated by this connector".
	for _, info := range tableMap {
		for _, colName := range info.PrimaryKey {
			if !predictableColumnOrder(info.Columns[colName].DataType) {
				info.UnpredictableKeyOrdering = true
			}
		}
	}

	if logrus.IsLevelEnabled(logrus.DebugLevel) {
		for id, info := range tableMap {
			logrus.WithFields(logrus.Fields{
				"stream":     id,
				"keyColumns": info.PrimaryKey,
			}).Debug("discovered table")
		}
	}

	return tableMap, nil
}

// extendTableDetails runs the per-chunk discovery queries (tables, columns,
// column descriptions, primary keys, generated columns, secondary indexes) for
// one batch of requested tables and merges the results into dst.
func (db *postgresDatabase) extendTableDetails(ctx context.Context, dst map[sqlcapture.StreamID]*sqlcapture.DiscoveryInfo, requested []sqlcapture.TableID) error {
	tables, err := getTables(ctx, db.conn, requested)
	if err != nil {
		return fmt.Errorf("unable to list database tables: %w", err)
	}
	for _, table := range tables {
		var streamID = sqlcapture.JoinStreamID(table.Schema, table.Name)
		table.UseSchemaInference = db.featureFlags["use_schema_inference"]
		table.EmitSourcedSchemas = db.featureFlags["emit_sourced_schemas"]
		dst[streamID] = table
	}

	columns, err := getColumns(ctx, db.conn, requested)
	if err != nil {
		return fmt.Errorf("unable to list database columns: %w", err)
	}
	for _, column := range columns {
		var streamID = sqlcapture.JoinStreamID(column.TableSchema, column.TableName)
		var info, ok = dst[streamID]
		if !ok {
			continue
		}
		if info.Columns == nil {
			info.Columns = make(map[string]sqlcapture.ColumnInfo)
		}
		info.Columns[column.Name] = column
		info.ColumnNames = append(info.ColumnNames, column.Name)
		dst[streamID] = info
	}

	// Column descriptions just add a bit of user-friendliness. They're so unimportant
	// that failure to list them shouldn't even be a fatal error.
	columnDescriptions, err := getColumnDescriptions(ctx, db.conn, requested)
	if err != nil {
		logrus.WithField("err", err).Warn("error fetching column descriptions")
	}
	for _, desc := range columnDescriptions {
		var streamID = sqlcapture.JoinStreamID(desc.TableSchema, desc.TableName)
		if info, ok := dst[streamID]; ok {
			if column, ok := info.Columns[desc.ColumnName]; ok {
				logrus.WithFields(logrus.Fields{
					"table":  streamID,
					"column": desc.ColumnName,
					"desc":   desc.Description,
				}).Trace("got column description")
				var description = desc.Description
				column.Description = &description
				info.Columns[desc.ColumnName] = column
			}
			dst[streamID] = info
		}
	}

	primaryKeys, err := getPrimaryKeys(ctx, db.conn, requested)
	if err != nil {
		return fmt.Errorf("unable to list database primary keys: %w", err)
	}
	for streamID, key := range primaryKeys {
		var info, ok = dst[streamID]
		if !ok {
			continue
		}
		logrus.WithFields(logrus.Fields{
			"table": streamID,
			"key":   key,
		}).Trace("queried primary key")
		info.PrimaryKey = key
		dst[streamID] = info
	}

	generatedColumns, err := getGeneratedColumns(ctx, db.conn, requested)
	if err != nil {
		var pgErr *pgconn.PgError
		if !errors.As(err, &pgErr) || pgErr.Code != "42703" {
			// Failure is expected on pre-12 versions of PostgreSQL which don't have
			// the 'attgenerated' column. Other errors should still be logged but
			// also probably don't warrant a fatal error.
			logrus.WithError(err).Warn("unable to list database generated columns")
		}
		generatedColumns = nil
	}
	for streamID, columnNames := range generatedColumns {
		var table, ok = dst[streamID]
		if !ok {
			continue
		}
		if details, ok := table.ExtraDetails.(*postgresTableDiscoveryDetails); ok {
			details.GeneratedColumns = columnNames
		}
		for _, columnName := range columnNames {
			logrus.WithFields(logrus.Fields{
				"table":  streamID,
				"column": columnName,
			}).Debug("omitting generated column from schema generation")
			var info = table.Columns[columnName]
			info.OmitColumn = true
			table.Columns[columnName] = info
		}
	}

	// For tables which have no primary key but have a valid secondary index,
	// fill in that secondary index as the 'primary key' for our purposes.
	secondaryIndexes, err := getSecondaryIndexes(ctx, db.conn, requested)
	if err != nil {
		return fmt.Errorf("unable to list database secondary indexes: %w", err)
	}
	for streamID, indexColumns := range secondaryIndexes {
		var info, ok = dst[streamID]
		if !ok || info.PrimaryKey != nil {
			continue
		}

		// Make a list of all usable indexes.
		logrus.WithFields(logrus.Fields{
			"table":   streamID,
			"indices": len(indexColumns),
		}).Debug("checking for suitable secondary indexes")
		var suitableIndexes []string
		for indexName, columns := range indexColumns {
			if columnsNonNullable(info.Columns, columns) {
				logrus.WithFields(logrus.Fields{
					"table":   streamID,
					"index":   indexName,
					"columns": columns,
				}).Debug("secondary index could be used as primary key")
				suitableIndexes = append(suitableIndexes, indexName)
			}
		}

		// Sort the list by index name and pick the first one, if there are multiple.
		// This helps ensure stable selection, although it could still change due to
		// the creation of a new secondary index.
		sort.Strings(suitableIndexes)
		if len(suitableIndexes) > 0 {
			var selectedIndex = suitableIndexes[0]
			logrus.WithFields(logrus.Fields{
				"table": streamID,
				"index": selectedIndex,
			}).Debug("selected secondary index as table key")
			info.PrimaryKey = indexColumns[selectedIndex]
			info.FallbackKey = true
		} else {
			logrus.WithField("table", streamID).Debug("no secondary index is suitable")
		}
	}

	return nil
}

// Returns true if the bytewise lexicographic ordering of serialized row keys for
// this column type matches the database backfill ordering.
func predictableColumnOrder(colType any) bool {
	// Currently all textual primary key columns are considered to be 'unpredictable' so that backfills
	// will default to using the 'imprecise' ordering semantics which avoids full-table sorts. Refer to
	// https://github.com/estuary/connectors/issues/1343 for more details.
	if t, ok := colType.(postgresTypeDescription); ok {
		switch t.TypeName() {
		case "varchar", "bpchar", "text", "citext":
			return false
		}
	}

	if _, ok := colType.(postgresEnumType); ok {
		return false
	}

	return true
}

func columnsNonNullable(columnsInfo map[string]sqlcapture.ColumnInfo, columnNames []string) bool {
	for _, columnName := range columnNames {
		if columnsInfo[columnName].IsNullable {
			return false
		}
	}
	return true
}

// TranslateDBToJSONType returns JSON schema information about the provided database column type.
func (db *postgresDatabase) TranslateDBToJSONType(column sqlcapture.ColumnInfo, isPrimaryKey bool) (*jsonschema.Schema, error) {
	if !db.featureFlags["date_as_date"] {
		// Historically DATE columns were captured as RFC3339 timestamps.
		postgresTypeToJSON["date"] = columnSchema{jsonTypes: []string{"string"}, format: "date-time"}
	}
	if !db.featureFlags["time_as_time"] {
		// Historically TIME columns were captured as Unix seconds.
		postgresTypeToJSON["time"] = columnSchema{jsonTypes: []string{"integer"}}
	}

	var jsonSchema *jsonschema.Schema
	if dataType, ok := column.DataType.(postgresTypeDescription); ok {
		var err error
		jsonSchema, err = dataType.JSONSchema(column.IsNullable, isPrimaryKey, db.featureFlags)
		if err != nil {
			return nil, err
		}
	} else {
		return nil, fmt.Errorf("unable to translate PostgreSQL type %q into JSON schema", column.DataType)
	}

	// Pass-through a postgres column description.
	if column.Description != nil {
		jsonSchema.Description = *column.Description
	}
	return jsonSchema, nil
}

type columnSchema struct {
	contentEncoding  string
	contentMediaType string
	format           string
	nullable         bool
	jsonTypes        []string
}

func (s columnSchema) toType() *jsonschema.Schema {
	var out = &jsonschema.Schema{
		Format: s.format,
		Extras: make(map[string]any),
	}

	if s.contentEncoding != "" {
		out.Extras["contentEncoding"] = s.contentEncoding // New in 2019-09.
	}

	if s.contentMediaType != "" {
		out.Extras["contentMediaType"] = s.contentMediaType // New in 2019-09.
	}

	if s.jsonTypes != nil {
		var types = append([]string(nil), s.jsonTypes...)
		if s.nullable {
			types = append(types, "null")
		}
		if len(types) == 1 {
			out.Type = types[0]
		} else {
			out.Extras["type"] = types
		}
	}
	return out
}

func lookupColumnSchema(isPrimaryKey bool, typeName string) (columnSchema, error) {
	// If the column is a primary key and there's a special-case for this type as a primary
	// key (as in the case of floatN columns which always get stringified when used as keys),
	// then we use that instead of the normal-value type mapping.
	if s, ok := postgresPrimaryKeyTypes[typeName]; ok && isPrimaryKey {
		return s, nil
	}

	if s, ok := postgresTypeToJSON[typeName]; ok {
		return s, nil
	}

	return columnSchema{}, fmt.Errorf("unable to translate PostgreSQL type %q into JSON schema", typeName)
}

var postgresPrimaryKeyTypes = map[string]columnSchema{
	"float4": {jsonTypes: []string{"string"}, format: "number"},
	"float8": {jsonTypes: []string{"string"}, format: "number"},
}

var postgresTypeToJSON = map[string]columnSchema{
	"bool": {jsonTypes: []string{"boolean"}},

	"int2": {jsonTypes: []string{"integer"}},
	"int4": {jsonTypes: []string{"integer"}},
	"int8": {jsonTypes: []string{"integer"}},
	"oid":  {jsonTypes: []string{"integer"}},

	"numeric": {jsonTypes: []string{"string"}, format: "number"},
	"float4":  {jsonTypes: []string{"number", "string"}, format: "number"},
	"float8":  {jsonTypes: []string{"number", "string"}, format: "number"},

	"varchar": {jsonTypes: []string{"string"}},
	"bpchar":  {jsonTypes: []string{"string"}},
	"text":    {jsonTypes: []string{"string"}},
	"citext":  {jsonTypes: []string{"string"}}, // From the 'citext' extension, but common enough we ought to support it properly
	"bytea":   {jsonTypes: []string{"string"}, contentEncoding: "base64"},
	"xml":     {jsonTypes: []string{"string"}},
	"bit":     {jsonTypes: []string{"string"}},
	"varbit":  {jsonTypes: []string{"string"}},

	// json and jsonb columns capture arbitrary JSON values, so we don't constrain
	// the JSON Schema type. The contentMediaType annotation distinguishes the two
	// at the wire so downstream connectors (e.g. materialize-postgres) can
	// recreate the original column type instead of collapsing both onto json.
	"json":     {contentMediaType: "application/json"},
	"jsonb":    {contentMediaType: "application/vnd.estuary.postgresql.jsonb+json"},
	"jsonpath": {jsonTypes: []string{"string"}},

	// Domain-Specific Types
	"date":        {jsonTypes: []string{"string"}, format: "date"},
	"timestamp":   {jsonTypes: []string{"string"}, format: "date-time"},
	"timestamptz": {jsonTypes: []string{"string"}, format: "date-time"},
	"time":        {jsonTypes: []string{"string"}, format: "time"},
	"timetz":      {jsonTypes: []string{"string"}, format: "time"},
	"interval":    {jsonTypes: []string{"string"}},
	"money":       {jsonTypes: []string{"string"}},
	"point":       {jsonTypes: []string{"string"}},
	"line":        {jsonTypes: []string{"string"}},
	"lseg":        {jsonTypes: []string{"string"}},
	"box":         {jsonTypes: []string{"string"}},
	"path":        {jsonTypes: []string{"string"}},
	"polygon":     {jsonTypes: []string{"string"}},
	"circle":      {jsonTypes: []string{"string"}},
	"inet":        {jsonTypes: []string{"string"}},
	"cidr":        {jsonTypes: []string{"string"}},
	"macaddr":     {jsonTypes: []string{"string"}},
	"macaddr8":    {jsonTypes: []string{"string"}},
	"tsvector":    {jsonTypes: []string{"string"}},
	"tsquery":     {jsonTypes: []string{"string"}},
	"uuid":        {jsonTypes: []string{"string"}, format: "uuid"},
}

type postgresTableDiscoveryDetails struct {
	GeneratedColumns []string // List of the names of generated columns in this table, in no particular order.
}

// listTables performs the raw enumeration query of all tables in the database,
// optionally restricted to a list of specified schemas. System schemas and
// temporary or unlogged tables are always excluded.
func listTables(ctx context.Context, conn *pgxpool.Pool, selectedSchemas []string, captureAsPartitions bool) ([]sqlcapture.TableID, error) {
	logrus.Debug("listing all tables in the database")

	var query = new(strings.Builder)
	var args []any
	fmt.Fprintf(query, "SELECT n.nspname, c.relname")
	fmt.Fprintf(query, "  FROM pg_catalog.pg_class c")
	fmt.Fprintf(query, "  JOIN pg_catalog.pg_namespace n ON (n.oid = c.relnamespace)")
	fmt.Fprintf(query, "  WHERE n.nspname NOT IN ('pg_catalog', 'pg_internal', 'information_schema', 'catalog_history', 'cron', 'pglogical')")
	fmt.Fprintf(query, "    AND c.relpersistence = 'p'") // exclude temporary tables ('t') and unlogged tables ('u')
	if captureAsPartitions {
		// When capturing as partitions, we want partition leaves and regular
		// non-partitioned tables, but not partitioned root tables.
		fmt.Fprintf(query, "    AND c.relkind = 'r'")
	} else {
		// Default behavior: exclude partitions and include root tables
		fmt.Fprintf(query, "    AND NOT c.relispartition")
		fmt.Fprintf(query, "    AND c.relkind IN ('r', 'p')") // Both ordinary and partitioned tables
	}
	if len(selectedSchemas) > 0 {
		args = append(args, selectedSchemas)
		fmt.Fprintf(query, "    AND n.nspname = ANY($%d)", len(args))
	}
	fmt.Fprintf(query, ";")

	var rows, err = conn.Query(ctx, query.String(), args...)
	if err != nil {
		return nil, fmt.Errorf("error executing query: %w", err)
	}
	defer rows.Close()
	var tables []sqlcapture.TableID
	for rows.Next() {
		var tableSchema, tableName string
		if err := rows.Scan(&tableSchema, &tableName); err != nil {
			return nil, fmt.Errorf("error scanning result row: %w", err)
		}
		tables = append(tables, sqlcapture.TableID{Schema: tableSchema, Table: tableName})
	}
	return tables, rows.Err()
}

// getTables fetches table-level discovery metadata for a specific set of
// tables.
func getTables(ctx context.Context, conn *pgxpool.Pool, requested []sqlcapture.TableID) ([]*sqlcapture.DiscoveryInfo, error) {
	if len(requested) == 0 {
		return nil, nil
	}
	var inClause, args = tableIDsInClause(requested)
	var query = fmt.Sprintf(
		`SELECT n.nspname, c.relname`+
			`  FROM pg_catalog.pg_class c`+
			`  JOIN pg_catalog.pg_namespace n ON (n.oid = c.relnamespace)`+
			`  WHERE (n.nspname, c.relname) IN (%s);`, inClause)

	var rows, err = conn.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error executing query: %w", err)
	}
	defer rows.Close()
	var tables []*sqlcapture.DiscoveryInfo
	for rows.Next() {
		var tableSchema, tableName string
		if err := rows.Scan(&tableSchema, &tableName); err != nil {
			return nil, fmt.Errorf("error scanning result row: %w", err)
		}
		tables = append(tables, &sqlcapture.DiscoveryInfo{
			Schema:       tableSchema,
			Name:         tableName,
			BaseTable:    true, // PostgreSQL discovery queries only ever list 'BASE TABLE' entities
			ExtraDetails: &postgresTableDiscoveryDetails{},
		})
	}
	return tables, rows.Err()
}

func getColumns(ctx context.Context, conn *pgxpool.Pool, requested []sqlcapture.TableID) ([]sqlcapture.ColumnInfo, error) {
	if len(requested) == 0 {
		return nil, nil
	}
	var inClause, args = tableIDsInClause(requested)
	var query = fmt.Sprintf(`
	  SELECT nc.nspname as table_schema,
	         c.relname as table_name,
			 a.attnum as ordinal_position,
			 a.attname as column_name,
			 NOT (a.attnotnull OR (t.typtype = 'd' AND t.typnotnull)) AS is_nullable,
			 COALESCE(bt.typname, t.typname) AS udt_name,
			 t.typtype::text AS typtype,
			 a.atttypmod-4 as char_max_length
		FROM pg_catalog.pg_attribute a
		JOIN pg_catalog.pg_type t ON a.atttypid = t.oid
		JOIN pg_catalog.pg_class c ON a.attrelid = c.oid
		JOIN pg_catalog.pg_namespace nc ON c.relnamespace = nc.oid
		LEFT JOIN (pg_catalog.pg_type bt JOIN pg_namespace nbt ON bt.typnamespace = nbt.oid)
		       ON t.typtype = 'd'::"char" AND t.typbasetype = bt.oid
	    WHERE (nc.nspname, c.relname) IN (%s)
	      AND a.attnum > 0
		  AND NOT a.attisdropped
		ORDER BY nc.nspname, c.relname, a.attnum;`, inClause)

	var columns []sqlcapture.ColumnInfo
	var rows, err = conn.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error executing query: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var col sqlcapture.ColumnInfo
		var columnType string
		var typtype string
		var charMaxLength *int64
		if err := rows.Scan(&col.TableSchema, &col.TableName, &col.Index, &col.Name, &col.IsNullable, &columnType, &typtype, &charMaxLength); err != nil {
			return nil, fmt.Errorf("error scanning result row: %w", err)
		}

		// Decode the column type information into useful structs
		var typeDescription postgresTypeDescription
		switch typtype {
		case "c": // composite
			// TODO(whb): We don't currently do any kind of special handling for composite
			// (tuple) types and just output whatever we get from from pgx's GenericText
			// decoder. The generated text for these isn't very usable and we may be able to
			// improve this by discovering composite types, building decoders for them, and
			// registering the decoders with the pgx connection. pgx v5 has new utility methods
			// specifically for doing this.
			typeDescription = postgresCompositeType{}
		case "e": // enum
			// Enum values are always strings corresponding to an enum label.
			typeDescription = postgresEnumType{}
		case "r", "m": // range, multirange
			// Capture ranges in their text form to retain inclusive (like `[`) & exclusive
			// (like `(`) bounds information. For example, the text form of a range representing
			// "integers greater than or equal to 1 but less than 5" is '[1,5)'
			typeDescription = postgresRangeType{multirange: typtype == "m"}
		default: // All others
			// Strip array prefix so we can decode the element type, then wrap it in an array type later
			var isArrayType bool
			columnType, isArrayType = strings.CutPrefix(columnType, "_")

			typeDescription = postgresBasicType{Name: columnType}

			if charMaxLength != nil && *charMaxLength > 0 {
				switch columnType {
				case "bpchar": // CHAR(n) - fixed-length, blank-padded
					// For fixed-length character types, set both minLength and maxLength
					var length = uint64(*charMaxLength)
					typeDescription = postgresSizedTextType{Inner: typeDescription, MinLength: &length, MaxLength: &length}
				case "varchar": // VARCHAR(n) - variable-length with limit
					// For variable-length character types, only set maxLength
					var length = uint64(*charMaxLength)
					typeDescription = postgresSizedTextType{Inner: typeDescription, MaxLength: &length}
				}
			}

			if isArrayType {
				typeDescription = postgresArrayType{Items: typeDescription}
			}
		}

		col.DataType = typeDescription
		columns = append(columns, col)
	}
	return columns, rows.Err()
}

type postgresTypeDescription interface {
	TypeName() string
	String() string
	JSONSchema(isColumnNullable, isPrimaryKey bool, featureFlags map[string]bool) (*jsonschema.Schema, error)
}

type postgresBasicType struct {
	Name string
}

func (t postgresBasicType) String() string { return t.Name }

func (t postgresBasicType) TypeName() string { return t.Name }

func (t postgresBasicType) JSONSchema(isColumnNullable, isPrimaryKey bool, featureFlags map[string]bool) (*jsonschema.Schema, error) {
	var colSchema, err = lookupColumnSchema(isPrimaryKey, t.Name)
	if err != nil {
		return nil, err
	}
	colSchema.nullable = isColumnNullable
	return colSchema.toType(), nil
}

type postgresSizedTextType struct {
	Inner     postgresTypeDescription
	MinLength *uint64
	MaxLength *uint64
}

func (t postgresSizedTextType) String() string {
	return t.Inner.String()
}

func (t postgresSizedTextType) TypeName() string { return t.Inner.TypeName() }

func (t postgresSizedTextType) JSONSchema(isColumnNullable, isPrimaryKey bool, featureFlags map[string]bool) (*jsonschema.Schema, error) {
	var jsonSchema, err = t.Inner.JSONSchema(isColumnNullable, isPrimaryKey, featureFlags)
	if err != nil {
		return nil, err
	}
	jsonSchema.MinLength = t.MinLength
	jsonSchema.MaxLength = t.MaxLength
	return jsonSchema, nil
}

type postgresArrayType struct {
	Items postgresTypeDescription
}

func (t postgresArrayType) String() string { return "_" + t.Items.String() }

func (t postgresArrayType) TypeName() string { return "_" + t.Items.TypeName() }

func (t postgresArrayType) JSONSchema(isColumnNullable, isPrimaryKey bool, featureFlags map[string]bool) (*jsonschema.Schema, error) {
	if featureFlags["multidimensional_arrays"] {
		// When 'multidimensional_arrays' is enabled, we don't specify an element type
		// in order to avoid the mess of trying to describe the recursive scalar-or-self
		// nature of the array elements. It's just an array of unspecified values.
		var jsonType = &jsonschema.Schema{
			Extras: map[string]any{"type": "array"},
		}
		if isColumnNullable {
			// The column value itself may be null if the column is nullable.
			jsonType.Extras["type"] = []string{"array", "null"}
		}
		return jsonType, nil
	}

	// Generate the column schema, with the understanding that the element type is always
	// nullable inside an array column regardless of column nullability.
	var colSchema, err = t.Items.JSONSchema(true, isPrimaryKey, featureFlags)
	if err != nil {
		return nil, err
	}

	// Legacy behavior: represent array values as an object with {elements,dimensions} fields.
	if !featureFlags["flatten_arrays"] {
		var jsonType = &jsonschema.Schema{
			Extras: map[string]any{
				"properties": map[string]*jsonschema.Schema{
					"dimensions": {
						Type:  "array",
						Items: &jsonschema.Schema{Type: "integer"},
					},
					"elements": {
						Type:  "array",
						Items: colSchema,
					},
				},
				"additionalProperties": false,
			},
			Required: []string{"dimensions", "elements"},
		}

		if isColumnNullable {
			jsonType.Extras["type"] = []string{"object", "null"}
		} else {
			jsonType.Type = "object"
		}
		return jsonType, nil
	}

	// Default behavior: flatten_arrays=true and multidimensional_arrays=false
	// Arrays are captured as just their flattened elements, without dimensionality.
	var jsonType = &jsonschema.Schema{
		Items:  colSchema,
		Extras: map[string]any{"type": "array"},
	}
	if isColumnNullable {
		jsonType.Extras["type"] = []string{"array", "null"}
	}
	return jsonType, nil
}

type postgresEnumType struct{}

func (t postgresEnumType) String() string { return "enum" }

func (t postgresEnumType) TypeName() string { return t.String() }

func (t postgresEnumType) JSONSchema(isColumnNullable, isPrimaryKey bool, featureFlags map[string]bool) (*jsonschema.Schema, error) {
	var colSchema = columnSchema{
		jsonTypes: []string{"string"},
		nullable:  isColumnNullable,
	}
	return colSchema.toType(), nil
}

type postgresRangeType struct {
	multirange bool
}

func (t postgresRangeType) String() string {
	if t.multirange {
		return "multirange"
	}
	return "range"
}

func (t postgresRangeType) TypeName() string { return t.String() }

func (t postgresRangeType) JSONSchema(isColumnNullable, isPrimaryKey bool, featureFlags map[string]bool) (*jsonschema.Schema, error) {
	var colSchema = columnSchema{
		jsonTypes: []string{"string"},
		nullable:  isColumnNullable,
	}
	return colSchema.toType(), nil
}

type postgresCompositeType struct{}

func (t postgresCompositeType) String() string { return "composite" }

func (t postgresCompositeType) TypeName() string { return t.String() }

func (t postgresCompositeType) JSONSchema(isColumnNullable, isPrimaryKey bool, featureFlags map[string]bool) (*jsonschema.Schema, error) {
	var colSchema = columnSchema{nullable: isColumnNullable}
	return colSchema.toType(), nil
}

// getPrimaryKeys queries the database to produce a map from table names to
// primary keys. Table names are fully qualified as "<schema>.<name>", and
// primary keys are represented as a list of column names, in the order that
// they form the table's primary key.
//
// Query adapted from pgjdbc's method PgDatabaseMetaData.getPrimaryKeys() with
// the always-NULL `TABLE_CAT` column omitted and a (schema, table) IN-clause
// added to keep per-chunk response size bounded.
//
// See: https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java#L2134
func getPrimaryKeys(ctx context.Context, conn *pgxpool.Pool, requested []sqlcapture.TableID) (map[sqlcapture.StreamID][]string, error) {
	if len(requested) == 0 {
		return nil, nil
	}
	var inClause, args = tableIDsInClause(requested)
	var query = fmt.Sprintf(`
	  SELECT result.TABLE_SCHEM, result.TABLE_NAME, result.COLUMN_NAME, result.KEY_SEQ
	  FROM (
	    SELECT n.nspname AS TABLE_SCHEM,
	      ct.relname AS TABLE_NAME, a.attname AS COLUMN_NAME,
	      (information_schema._pg_expandarray(i.indkey)).n AS KEY_SEQ, ci.relname AS PK_NAME,
	      information_schema._pg_expandarray(i.indkey) AS KEYS, a.attnum AS A_ATTNUM
	    FROM pg_catalog.pg_class ct
	      JOIN pg_catalog.pg_attribute a ON (ct.oid = a.attrelid)
	      JOIN pg_catalog.pg_namespace n ON (ct.relnamespace = n.oid)
	      JOIN pg_catalog.pg_index i ON (a.attrelid = i.indrelid)
	      JOIN pg_catalog.pg_class ci ON (ci.oid = i.indexrelid)
	    WHERE i.indisprimary AND (n.nspname, ct.relname) IN (%s)
	  ) result
	  WHERE result.A_ATTNUM = (result.KEYS).x
	  ORDER BY result.table_name, result.pk_name, result.key_seq;
	`, inClause)

	var keys = make(map[sqlcapture.StreamID][]string)
	var rows, err = conn.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error executing query: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var tableSchema, tableName, columnName string
		var columnIndex int
		if err := rows.Scan(&tableSchema, &tableName, &columnName, &columnIndex); err != nil {
			return nil, fmt.Errorf("error scanning result row: %w", err)
		}
		var streamID = sqlcapture.JoinStreamID(tableSchema, tableName)
		keys[streamID] = append(keys[streamID], columnName)
		if columnIndex != len(keys[streamID]) {
			return nil, fmt.Errorf("primary key column %q of table %q appears out of order (expected index %d, in context %q)", columnName, streamID, columnIndex, keys[streamID])
		}
	}
	return keys, rows.Err()
}

func getSecondaryIndexes(ctx context.Context, conn *pgxpool.Pool, requested []sqlcapture.TableID) (map[sqlcapture.StreamID]map[string][]string, error) {
	if len(requested) == 0 {
		return nil, nil
	}
	var inClause, args = tableIDsInClause(requested)
	var query = fmt.Sprintf(`
	SELECT r.table_schema, r.table_name, r.index_name, (r.index_keys).n, r.column_name
	FROM (
	  SELECT tn.nspname AS table_schema,
	         tc.relname AS table_name,
		     ic.relname AS index_name,
		     information_schema._pg_expandarray(ix.indkey) AS index_keys,
			 a.attnum AS column_number,
			 a.attname AS column_name
	  FROM pg_catalog.pg_index ix
	       JOIN pg_catalog.pg_class ic ON (ic.oid = ix.indexrelid)
		   JOIN pg_catalog.pg_class tc ON (tc.oid = ix.indrelid)
		   JOIN pg_catalog.pg_namespace tn ON (tn.oid = tc.relnamespace)
		   JOIN pg_catalog.pg_attribute a ON (a.attrelid = tc.oid)
	  WHERE ix.indisunique AND ix.indexprs IS NULL AND tc.relkind = 'r'
	    AND NOT ix.indisprimary
	    AND (tn.nspname, tc.relname) IN (%s)
	  ORDER BY tc.relname, ic.relname
	) r
	WHERE r.column_number = (r.index_keys).x
	ORDER BY r.table_schema, r.table_name, r.index_name, (r.index_keys).n
	`, inClause)

	// Aggregate results into a `map[StreamID]map[IndexName][]ColumnName`.
	var streamIndexColumns = make(map[sqlcapture.StreamID]map[string][]string)
	var rows, err = conn.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error executing query: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var tableSchema, tableName, indexName, columnName string
		var keySequence int
		if err := rows.Scan(&tableSchema, &tableName, &indexName, &keySequence, &columnName); err != nil {
			return nil, fmt.Errorf("error scanning result row: %w", err)
		}
		var streamID = sqlcapture.JoinStreamID(tableSchema, tableName)
		var indexColumns = streamIndexColumns[streamID]
		if indexColumns == nil {
			indexColumns = make(map[string][]string)
			streamIndexColumns[streamID] = indexColumns
		}
		indexColumns[indexName] = append(indexColumns[indexName], columnName)
		if len(indexColumns[indexName]) != keySequence {
			return nil, fmt.Errorf("internal error: secondary index key ordering failure: index %q on stream %q: column %q appears out of order", indexName, streamID, columnName)
		}
	}

	return streamIndexColumns, rows.Err()
}

func getGeneratedColumns(ctx context.Context, conn *pgxpool.Pool, requested []sqlcapture.TableID) (map[sqlcapture.StreamID][]string, error) {
	if len(requested) == 0 {
		return nil, nil
	}
	var inClause, args = tableIDsInClause(requested)
	var query = fmt.Sprintf(`
		SELECT n.nspname AS table_schema,
	       c.relname AS table_name,
	       a.attname AS column_name
		FROM pg_catalog.pg_attribute a
		JOIN pg_catalog.pg_class c ON a.attrelid = c.oid
		JOIN pg_catalog.pg_namespace n ON c.relnamespace = n.oid
		WHERE a.attgenerated = 's' AND (n.nspname, c.relname) IN (%s)
		ORDER BY n.nspname, c.relname, a.attname;
	`, inClause)

	var rows, err = conn.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error querying generated columns: %w", err)
	}
	defer rows.Close()

	var generatedColumns = make(map[sqlcapture.StreamID][]string)
	for rows.Next() {
		var tableSchema, tableName, columnName string
		if err := rows.Scan(&tableSchema, &tableName, &columnName); err != nil {
			return nil, fmt.Errorf("error scanning result row: %w", err)
		}
		var streamID = sqlcapture.JoinStreamID(tableSchema, tableName)
		generatedColumns[streamID] = append(generatedColumns[streamID], columnName)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating generated columns: %w", err)
	}
	return generatedColumns, nil
}

type columnDescription struct {
	TableSchema string
	TableName   string
	ColumnName  string
	Description string
}

func getColumnDescriptions(ctx context.Context, conn *pgxpool.Pool, requested []sqlcapture.TableID) ([]columnDescription, error) {
	if len(requested) == 0 {
		return nil, nil
	}
	var inClause, args = tableIDsInClause(requested)
	var query = fmt.Sprintf(`
	    SELECT * FROM (
			SELECT
			    isc.table_schema,
				isc.table_name,
				isc.column_name,
				pg_catalog.col_description(format('"%%s"."%%s"',isc.table_schema,isc.table_name)::regclass::oid,isc.ordinal_position) description
			FROM information_schema.columns isc
			WHERE (isc.table_schema, isc.table_name) IN (%s)
		) as descriptions WHERE description != '';
	`, inClause)

	var descriptions []columnDescription
	var rows, err = conn.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("error executing query: %w", err)
	}
	defer rows.Close()
	for rows.Next() {
		var desc columnDescription
		if err := rows.Scan(&desc.TableSchema, &desc.TableName, &desc.ColumnName, &desc.Description); err != nil {
			return nil, fmt.Errorf("error scanning result row: %w", err)
		}
		descriptions = append(descriptions, desc)
	}
	return descriptions, rows.Err()
}
