[tool.poetry]
name = "source-netsuite"
version = "0.1.0"
description = ""
authors = ["Johnny Graettinger <johnny@estuary.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
jsonlines = "^4.0.0"
mypy = "^1.5"
orjson = "^3.9.7"
python = ">=3.11,<3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
