version: "3.7"

services:
  db:
    image: 'mysql:latest'
    command: ["--binlog-row-metadata=FULL"]
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./docker-entrypoint-initdb.d/init-user-db.sh
        target: /docker-entrypoint-initdb.d/init-user-db.sh
      - type: bind
        source: ../tests/files/b.csv
        target: /b.csv
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: flow
      MYSQL_USER: flow
      MYSQL_PASSWORD: flow
    networks:
      - flow-test
    cap_add:
      - SYS_NICE  # Prevents 'mbind: Operation not permitted' errors. In theory those are benign but it's better to not have them.

networks:
  flow-test:
    name: flow-test
    external: true

volumes:
  mysql_data: {}
