version: "3.7"

services:
  db:
    image: 'mysql:latest'
    command: ["--binlog-row-metadata=FULL"]
    volumes:
      - type: bind
        source: ./docker-entrypoint-initdb.d/init-user-db.sh
        target: /docker-entrypoint-initdb.d/init-user-db.sh
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: flow
      MYSQL_USER: flow
      MYSQL_PASSWORD: flow
    network_mode: "host"
    cap_add:
      - SYS_NICE  # Prevents 'mbind: Operation not permitted' errors. In theory those are benign but it's better to not have them.

volumes:
  mysql_data: {}
