services:
  storage:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    networks:
      flow-test:
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://127.0.0.1:4566/_localstack/health"
        ]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 5s


networks:
  flow-test:
    external: true
