version: "3.7"

services:
  mongo:
    image: 'mongo:latest'
    environment: {"MONGO_INITDB_ROOT_USERNAME": "flow", "MONGO_INITDB_ROOT_PASSWORD": "flow"}
    command: ["--replSet", "rs0", "--keyFile", "/etc/ssl/sample.key"]
    networks:
      - flow-test

networks:
  flow-test:
    name: flow-test
    external: true
