---
$schema: "http://json-schema.org/draft-07/schema#"
additionalProperties: true
description: Details of an application role.
properties:
  defaultGroups:
    description: The groups that are granted default access for this application role.
    items:
      type: string
    type: array
    uniqueItems: true
  defaultGroupsDetails:
    items:
      properties:
        groupId:
          type:
            - "null"
            - string
        name:
          type:
            - "null"
            - string
        self:
          type:
            - "null"
            - string
      type:
        - "null"
        - object
    type:
      - "null"
      - array
  defined:
    description: Deprecated.
    type: boolean
  groupDetails:
    description: Group Details
    items:
      type:
        - "null"
        - object
    type:
      - "null"
      - array
  groups:
    description: The groups associated with the application role.
    items:
      type: string
    type: array
    uniqueItems: true
  hasUnlimitedSeats:
    type: boolean
  key:
    description: The key of the application role.
    type: string
  name:
    description: The display name of the application role.
    type: string
  numberOfSeats:
    description: The maximum count of users on your license.
    type: integer
  platform:
    description: "Indicates if the application role belongs to Jira platform (`jira-core`)."
    type: boolean
  remainingSeats:
    description: The count of users remaining on your license.
    type: integer
  selectedByDefault:
    description: Determines whether this application role should be selected by default on user creation.
    type: boolean
  userCount:
    description: The number of users counting against your license.
    type: integer
  userCountDescription:
    description: "The [type of users](https://confluence.atlassian.com/x/lRW3Ng) being counted against your license."
    type: string
required:
  - key
type: object
