---
$schema: "http://json-schema.org/draft-07/schema#"
type: object
properties:
  label:
    description: The label representing the data displayed in the issue navigator column.
    type: string
  value:
    description: The actual value/data associated with the label in the issue navigator column.
    type: string
  _meta:
    type: object
    properties:
      row_id:
        type: integer
    required:
      - row_id
additionalProperties: true
description: Details of an issue navigator column item.
x-infer-schema: true
