---
$schema: "http://json-schema.org/draft-07/schema#"
additionalProperties: true
description: Details of a field configuration.
properties:
  description:
    description: The description of the field configuration.
    type: string
  id:
    description: The ID of the field configuration.
    type: integer
  isDefault:
    description: Whether the field configuration is the default.
    type: boolean
  name:
    description: The name of the field configuration.
    type: string
required:
  - id
type: object
