version: "3.7"

services:
  db:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    environment:
      SA_PASSWORD: "gf6w6dkD"
      ACCEPT_EULA: "Y"
    networks:
      - flow-test

networks:
  flow-test:
    name: flow-test
    external: true

volumes:
  sqlserver_data: {}
