account_id: "196765372540622"
credentials:
    access_token_sops: ENC[AES256_GCM,data:t1SY+JBKZv42/6Xdy1bXO0ljoS3mVUjJW44P9t8DuFzbcfV/RseGkNpnzVeEDU49hy29H80w6RhY3lhlJXsHiSUXkT7owjlJNrC0sLAy/n1FPMpwS1MT8s+Svs43OxirEdSCE7Y9dKXKZlG2iVgxQ7xSxCIL0USmPffpfNyY1xg578zmp3f/iZgDX7S2LCc8M3nIv/alrEfidYt765t4mI7m4+kVXR5fkY6alSS4mnf40LazTH4z1yUBh+iHOIL4U79TAYVSxFH30f8Dmzc2LjkvB6rojEFNa1wLH79eAWSAT560O+g78tjpe/48jUZdWlua7JzLmDjqtrLZpqbwIXybIk4=,iv:1EhErzXV0QWnQ5XeeJHWA5GTK3x5CYYnGSfqZoVdKYI=,tag:0IbLNbEHy/Z5GGkO7aYkvA==,type:str]
    auth_type: OAuth Credentials
    client_id_sops: ENC[AES256_GCM,data:rnUN2/VIkKTmA7w4WQ4s,iv:AqdXloHWTk8Fo7H1kXHfXnU2NAzD8vDtlUTfuK/QveU=,tag:Ei/vLmTEukl/GsTDSLfurw==,type:str]
    client_secret_sops: ENC[AES256_GCM,data:o7/PMj0z7CdP6Bd9bWmbnrfYYMHDzRmUwDbHdRJ9uWc=,iv:hofsqlUfk9wK9Ujx9X8z8D2QnHvii3XHVH0Ftd4YbiY=,tag:zWV71dJM+j8tZGWx7Byscw==,type:str]
custom_insights:
    - action_breakdowns: []
      breakdowns:
        - publisher_platform
      fields:
        - ad_id
        - ad_name
        - account_id
        - account_name
        - adset_id
        - adset_name
        - campaign_id
        - campaign_name
        - date_start
        - date_stop
        - clicks
        - impressions
        - reach
        - inline_link_clicks
        - outbound_clicks
      insights_lookback_window: 28
      level: ad
      name: ads_insights_publisher_platform
      start_date: "2021-11-01T00:00:00Z"
      time_increment: 1
fetch_thumbnail_images: false
include_deleted: true
insights_lookback_window: 28
max_batch_size: 50
page_size: 100
start_date: "2021-11-01T00:00:00Z"
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/helpful-kingdom-273219/locations/us-central1/keyRings/dev/cryptoKeys/CI-estuary-flow
          created_at: "2024-01-29T21:56:19Z"
          enc: CiQAW8BC2KAYkL/QeH7rAo90G3cGBs4NxAnefadqPZKJ9BUGpcoSSAD00UdDo6JlcTVLVvMILSggKQSWQvUEV98CPSKBU85+oX8UOUPk8VgS39kjlL8ckVe6zY4+hijBM6rWEaa7odnTXJ+OqW1U5A==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-29T21:56:20Z"
    mac: ENC[AES256_GCM,data:4TnWNr6EU1ziJ30BzmF4VvmsLtjciOwUedwqH5e3tfnNPJmTrBqGVSO0mXqP+sGJcnaGowfH0xXgG+LZQsKxgG5mnUU0AAf2Sdg65yd/fEuMesROWcFmzyiCaxa0YhT1+eGHAlKL1Kr67JcP3EMRva6H+Hr47neyX1fX8VYvG74=,iv:qdC97Gyc34/uRKBdrhsa9iVnVee9QZgOCIaNHlceAb8=,tag:c08ebesq600gpAws7on/lw==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1