account_id: "196765372540622"
start_date: "2022-01-01T00:00:00Z"
credentials:
    access_token_sops: ENC[AES256_GCM,data:hgDiLwzCKcO/7nScU1IQGXkdPi5xYIqyAO8f8+EVA29ASpE4QeN6p++Mag8q7lyslgjgIqnjY0459EYq5H5GV7lCPWWNrS9pSc4WQ2Of77/mYTCAWKPjfz4CL3b272Zyh6YPa59j7CKcZCtGj1GRd5anUfWiZQ4IJGNax3ooLCpmLQaeeJiNUMrkn17t/rUpgVD5LNwDJFeZWxNrtAV/RoIW2EkykPV40vG+r9WkPczmO7+cJZZP9y7E7blWVLtVvY0sGDFPC2ivZmngdMKjjz/GcVgHQ/IJNppPZAa8/NZteVSdmprf+oZDIqnzYFJy8fmBbWCDgJ64SDb4UbrzS+LrJiQ=,iv:TaWPvk3DlezW1kP7KahGrCqwylRJrVnjSLC67Jfxkns=,tag:7jzXDbC2a2RJvu+TfxL9LQ==,type:str]
    auth_type: OAuth Credentials
    client_id_sops: ENC[AES256_GCM,data:m0dFDR0846ScHEqT8meM,iv:uiQelyvp7DXVekE32gQ2LoEd2e9jmgtaywCJnD6O3+w=,tag:yxtHWcJZWXN1wZQPk24WdA==,type:int]
    client_secret_sops: ENC[AES256_GCM,data:oaHFT7csjNoGicMDyqgDkq8VzfFmPsgPwzacRV4M7B8=,iv:8sucaAx7PiOoo5U/dTXrEEvu0ES3Wi+5M1MC021nqR4=,tag:k+Ho//us6i5X3Llq6xtCAw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/helpful-kingdom-273219/locations/us-central1/keyRings/dev/cryptoKeys/CI-estuary-flow
          created_at: "2024-01-29T20:50:05Z"
          enc: CiQAW8BC2IR0nm8MO9lroLUNNyjcO4Tf4l7iJ63U841ARBMndywSSQD00UdDvmSdlOcOaU14thfhY9vPrDs2uEZMlKpY3SeqKpsOquxGOCxPBAiUJKxZ60aFdVyQkwMSDK7uq9Nbnkvm1IU9caal4Vo=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-29T20:50:06Z"
    mac: ENC[AES256_GCM,data:XQlVWsaiJ1asEswBQZzZyeLCvEc4Cls8vKlb59ldvR0IiVpDN6d+Sv8ijrzDM7eFJNFWmFjbxf9hhoVkgpyXVp2I7gXhd6pKKk/u12LzTEvECosi+DSs3gtGVogt0oDa/kTtR04mFXpZFZP+WPOfgvz/Sy7gq8qE61O5vxQds0g=,iv:9xYdVuaHnR5TjirUbbU5nfA4/cwePcobIrXlftx6EY4=,tag:JVsUWE9tLO4oFyMxaKd8rw==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1