# Each key in SUPPORTED_STANDARD_OBJECTS represents a standard Salesforce Object that
# the connector supports. This was generated by transforming the resources listed in an existing
# source-salesforce specification.

# If an object has a 'cursor_field', that means it is an incremental stream. Not having a 'cursor_field' means it is a full refresh stream.
# Example:
#      {
#        "ApexPageInfo": {}
#      }
#   ApexPageInfo is a full refresh stream since it does not have a cursor_field property.

from typing import TypedDict, Optional

from source_salesforce_native.models import CursorFields

class ObjectDetails(TypedDict, total=False):
    cursor_field: Optional[CursorFields] # If absent, the object is full refresh. If present, the object is incremental.
    enabled_by_default: Optional[bool] # If absent, the object is not enabled by default. If present and True, the object is enabled by default.
    is_supported_by_bulk_api: Optional[bool] # If absent, the object is supported by the Bulk API. If present and False, the object is not supported by the Bulk API.


CUSTOM_OBJECT_WITH_SYSTEM_MODSTAMP_DETAILS: ObjectDetails = {
    "cursor_field": CursorFields.SYSTEM_MODSTAMP,
}

CUSTOM_OBJECT_WITH_CREATED_DATE_DETAILS: ObjectDetails = {
    "cursor_field": CursorFields.CREATED_DATE,
}

CUSTOM_OBJECT_WITH_LAST_MODIFIED_DATE_DETAILS: ObjectDetails = {
    "cursor_field": CursorFields.LAST_MODIFIED_DATE,
}


SUPPORTED_STANDARD_OBJECTS: dict[str, ObjectDetails] = {
    "AIApplication": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AIApplicationConfig": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AIInsightAction": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AIInsightFeedback": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AIInsightReason": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AIInsightValue": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AIRecordInsight": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AcceptedEventRelation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "is_supported_by_bulk_api": False,
    },
    "Account": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "AccountBrand": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AccountCleanInfo": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AccountContactRelation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
    },
    "AccountContactRole": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AccountFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AccountHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "AccountPartner": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AccountShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "AccountTeamMember": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ActionLinkGroupTemplate": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ActionLinkTemplate": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ActiveFeatureLicenseMetric": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ActivePermSetLicenseMetric": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ActiveProfileMetric": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AdditionalNumber": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Address": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AgentWork": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AlternativePaymentMethod": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AlternativePaymentMethodShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ApexClass": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ApexComponent": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ApexEmailNotification": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ApexLog": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ApexPage": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ApexPageInfo": {},
    "ApexTestQueueItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ApexTestResult": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ApexTestResultLimits": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ApexTestRunResult": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ApexTestSuite": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ApexTrigger": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ApiAnomalyEventStore": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ApiAnomalyEventStoreFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AppAnalyticsQueryRequest": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AppDefinition": {},
    "AppMenuItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AppUsageAssignment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AppointmentAssignmentPolicy": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AppointmentScheduleAggr": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AppointmentScheduleLog": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AppointmentSchedulingPolicy": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AppointmentTopicTimeSlot": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AppointmentTopicTimeSlotFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AppointmentTopicTimeSlotHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "Approval": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Asset": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AssetAction": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AssetActionSource": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AssetFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AssetHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "AssetRelationship": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AssetRelationshipFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AssetRelationshipHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "AssetShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "AssetStatePeriod": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AssignedResource": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AssignedResourceFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AssignmentRule": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AssociatedLocation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AssociatedLocationHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "AsyncApexJob": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "AsyncOperationLog": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Attachment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AuraDefinition": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AuraDefinitionBundle": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AuraDefinitionBundleInfo": {},
    "AuraDefinitionInfo": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "AuthConfig": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AuthConfigProviders": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AuthProvider": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "AuthSession": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "AuthorizationForm": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AuthorizationFormConsent": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AuthorizationFormConsentHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "AuthorizationFormConsentShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "AuthorizationFormDataUse": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AuthorizationFormDataUseHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "AuthorizationFormDataUseShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "AuthorizationFormHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "AuthorizationFormShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "AuthorizationFormText": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AuthorizationFormTextFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "AuthorizationFormTextHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "BackgroundOperation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "BrandTemplate": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "BrandingSet": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "BrandingSetProperty": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "BriefcaseAssignment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "BriefcaseDefinition": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "BriefcaseRule": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "BriefcaseRuleFilter": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "BusinessHours": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "BusinessProcess": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "BuyerGroup": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "BuyerGroupFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "BuyerGroupHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "BuyerGroupShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "Calendar": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CalendarView": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CalendarViewShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "CallCenter": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CallCenterRoutingMap": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CallCoachingMediaProvider": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Campaign": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "CampaignFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CampaignHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "CampaignInfluence": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
    },
    "CampaignInfluenceModel": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
    },
    "CampaignMember": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CampaignMemberStatus": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CampaignShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "CardPaymentMethod": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CartCheckoutSession": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CartDeliveryGroup": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CartDeliveryGroupMethod": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CartItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CartItemPriceAdjustment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CartRelatedItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CartTax": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CartValidationOutput": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Case": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "CaseComment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CaseContactRole": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CaseFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CaseHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "CaseMilestone": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CaseShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "CaseSolution": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CaseStatus": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "is_supported_by_bulk_api": False,
    },
    "CaseSubjectParticle": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CaseTeamMember": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CaseTeamRole": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CaseTeamTemplate": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CaseTeamTemplateMember": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CaseTeamTemplateRecord": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CategoryData": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CategoryNode": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ChannelProgram": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ChannelProgramFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ChannelProgramHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ChannelProgramLevel": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ChannelProgramLevelFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ChannelProgramLevelHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ChannelProgramMember": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ChannelProgramMemberFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ChannelProgramMemberHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ChatRetirementRdyMetrics": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ChatterActivity": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ChatterExtension": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ChatterExtensionConfig": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ClientBrowser": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "CollaborationGroup": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CollaborationGroupFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CollaborationGroupMember": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CollaborationGroupMemberRequest": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CollaborationInvitation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CommSubscription": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CommSubscriptionChannelType": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CommSubscriptionChannelTypeFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CommSubscriptionChannelTypeHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "CommSubscriptionChannelTypeShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "CommSubscriptionConsent": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CommSubscriptionConsentFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CommSubscriptionConsentHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "CommSubscriptionConsentShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "CommSubscriptionFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CommSubscriptionHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "CommSubscriptionShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "CommSubscriptionTiming": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CommSubscriptionTimingFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CommSubscriptionTimingHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "Community": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ConferenceNumber": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ConnectedApplication": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ConsumptionRate": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ConsumptionRateHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ConsumptionSchedule": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ConsumptionScheduleFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ConsumptionScheduleHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ConsumptionScheduleShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "Contact": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "ContactCleanInfo": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContactFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContactHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ContactPointAddress": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContactPointAddressHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ContactPointAddressShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ContactPointConsent": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContactPointConsentHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ContactPointConsentShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ContactPointEmail": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContactPointEmailHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ContactPointEmailShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ContactPointPhone": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContactPointPhoneHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ContactPointPhoneShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ContactPointTypeConsent": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContactPointTypeConsentHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ContactPointTypeConsentShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ContactRequest": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContactRequestShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ContactShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ContentAsset": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContentDistribution": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContentDistributionView": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContentDocument": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContentDocumentFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContentDocumentHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ContentDocumentSubscription": {},
    "ContentFolder": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContentFolderLink": {},
    "ContentNote": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ContentNotification": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ContentTagSubscription": {},
    "ContentUserSubscription": {},
    "ContentVersion": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContentVersionComment": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ContentVersionHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ContentVersionRating": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ContentWorkspace": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContentWorkspaceDoc": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContentWorkspaceMember": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ContentWorkspacePermission": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContentWorkspaceSubscription": {},
    "Contract": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContractContactRole": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContractFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContractHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ContractLineItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ContractLineItemHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ContractStatus": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "is_supported_by_bulk_api": False,
    },
    "Conversation": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ConversationEntry": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ConversationParticipant": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ConversationVendorInfo": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CorsWhitelistEntry": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Coupon": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CouponHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "CouponShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "CredentialStuffingEventStore": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CredentialStuffingEventStoreFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CreditMemo": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CreditMemoFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CreditMemoHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "CreditMemoInvApplication": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CreditMemoInvApplicationFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CreditMemoInvApplicationHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "CreditMemoLine": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CreditMemoLineFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CreditMemoLineHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "CreditMemoShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "CronJobDetail": {},
    "CronTrigger": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "CspTrustedSite": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CurrencyType": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CustomBrand": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "CustomBrandAsset": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "CustomHelpMenuItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CustomHelpMenuSection": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CustomHttpHeader": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CustomNotificationType": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CustomObjectUserLicenseMetrics": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CustomPermission": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "CustomPermissionDependency": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DandBCompany": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Dashboard": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DashboardComponent": {},
    "DashboardComponentFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DashboardFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DataAssessmentFieldMetric": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DataAssessmentMetric": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DataAssessmentValueMetric": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DataIntegrationRecordPurchasePermission": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DataKitDeploymentLog": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DataKitDeploymentLogShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "DataUseLegalBasis": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DataUseLegalBasisHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "DataUseLegalBasisShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "DataUsePurpose": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DataUsePurposeHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "DataUsePurposeShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "DatacloudCompany": {},
    "DatacloudContact": {},
    "DatacloudOwnedEntity": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DatacloudPurchaseUsage": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DatedConversionRate": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DeclinedEventRelation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "is_supported_by_bulk_api": False,
    },
    "DelegatedAccount": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DelegatedAccountFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DelegatedAccountHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "DeleteEvent": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DigitalWallet": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Document": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DocumentAttachmentMap": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "Domain": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DomainSite": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DuplicateRecordItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DuplicateJob": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DuplicateJobMatchingRule": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DuplicateRecordSet": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "DuplicateRule": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EmailCapture": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EmailDomainFilter": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EmailDomainKey": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EmailMessage": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EmailMessageRelation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EmailRelay": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EmailServicesAddress": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EmailServicesFunction": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EmailTemplate": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EmbeddedServiceDetail": {},
    "EmbeddedServiceLabel": {},
    "EmpUserProvisionProcessErr": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EmpUserProvisioningProcess": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EngagementChannelType": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EngagementChannelTypeFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EngagementChannelTypeHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "EngagementChannelTypeShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "EnhancedLetterhead": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EnhancedLetterheadFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Entitlement": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "EntitlementContact": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EntitlementFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EntitlementHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "EntitlementTemplate": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EntityMilestone": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EntityMilestoneFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EntityMilestoneHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "EntitySubscription": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "Event": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EventBusSubscriber": {},
    "EventFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EventLogFile": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EventRecurrenceException": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EventRelation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "EventWhoRelation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ExpressionFilter": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ExpressionFilterCriteria": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ExternalDataSource": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ExternalDataUserAuth": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ExternalEvent": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ExternalEventMapping": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ExternalEventMappingShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ExternalSocialAccount": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FeedAttachment": {},
    "FeedComment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FeedItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FeedPollChoice": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "FeedPollVote": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "FeedRevision": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FieldPermissions": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FieldSecurityClassification": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "is_supported_by_bulk_api": False,
    },
    "FileSearchActivity": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FinanceBalanceSnapshot": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FinanceBalanceSnapshotShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "FinanceTransaction": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FinanceTransactionShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "FiscalYearSettings": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FlowDefinitionView": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "FlowInterview": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FlowInterviewLog": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FlowInterviewLogEntry": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FlowInterviewLogShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "FlowInterviewShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "FlowRecordRelation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FlowStageRelation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Folder": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ForecastingAdjustment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ForecastingItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ForecastingOwnerAdjustment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ForecastingQuota": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FormulaFunction": {},
    "FormulaFunctionAllowedType": {},
    "FormulaFunctionCategory": {},
    "FulfillmentOrder": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FulfillmentOrderFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FulfillmentOrderItemAdjustment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FulfillmentOrderItemAdjustmentFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FulfillmentOrderItemTax": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FulfillmentOrderItemTaxFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FulfillmentOrderLineItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FulfillmentOrderLineItemFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "FulfillmentOrderShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "GrantedByLicense": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Group": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "GroupMember": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "GtwyProvPaymentMethodType": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Holiday": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "IPAddressRange": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Idea": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "IdeaTheme": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "IframeWhiteListUrl": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Image": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ImageFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ImageHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ImageShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "Individual": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "IndividualHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "IndividualShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "InstalledMobileApp": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Invoice": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "InvoiceFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "InvoiceHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "InvoiceLine": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "InvoiceLineFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "InvoiceLineHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "InvoiceShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "KnowledgeableUser": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Lead": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "LeadCleanInfo": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LeadFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LeadHistory": {
        "cursor_field": CursorFields.CREATED_DATE,
        "enabled_by_default": True,
    },
    "LeadShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "LeadStatus": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LearningItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LearningItemShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "LegalEntity": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LegalEntityFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LegalEntityHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "LegalEntityShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "LightningExitByPageMetrics": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LightningExperienceTheme": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LightningOnboardingConfig": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LightningToggleMetrics": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LightningUsageByAppTypeMetrics": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LightningUsageByBrowserMetrics": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LightningUsageByFlexiPageMetrics": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LightningUsageByPageMetrics": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ListEmail": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ListEmailIndividualRecipient": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ListEmailRecipientSource": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ListEmailShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ListView": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ListViewChart": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LiveChatTranscript": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "LiveChatSensitiveDataRule": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Location": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LocationFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LocationGroup": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LocationGroupAssignment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LocationGroupFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LocationGroupHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "LocationGroupShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "LocationHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "LocationTrustMeasure": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LocationShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "LoginGeo": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "LoginHistory": {
        "cursor_field": CursorFields.LOGIN_TIME
    },
    "LoginIp": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "MLPredictionDefinition": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Macro": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MacroHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "MacroInstruction": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MacroShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "MacroUsage": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MacroUsageShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "MailmergeTemplate": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MatchingInformation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MatchingRule": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MatchingRuleItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MessagingChannel": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MessagingChannelSkill": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MessagingConfiguration": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MessagingDeliveryError": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MessagingEndUser": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MessagingEndUserHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "MessagingEndUserShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "MessagingLink": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MessagingSession": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "MessagingSessionFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MessagingSessionHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "MessagingSessionShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "MessagingTemplate": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MilestoneType": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MlFeatureValueMetric": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MobileApplicationDetail": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MsgChannelLanguageKeyword": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MutingPermissionSet": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "MyDomainDiscoverableLogin": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "NamedCredential": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "NetworkActivityAudit": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "NetworkDiscoverableLogin": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "NetworkFeedResponseMetric": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "NetworkMember": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "NetworkSelfRegistration": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Note": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OauthCustomScope": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OauthCustomScopeApp": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OauthToken": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ObjectPermissions": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OnboardingMetrics": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OperatingHours": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OperatingHoursFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OperatingHoursHoliday": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OperatingHoursHolidayFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OperatingHoursShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "Opportunity": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "OpportunityCompetitor": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OpportunityContactRole": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OpportunityFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OpportunityFieldHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "OpportunityHistory": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OpportunityLineItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OpportunityLineItemSchedule": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OpportunityPartner": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OpportunityShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "OpportunitySplit": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OpportunitySplitHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "OpportunitySplitType": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OpportunityStage": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OpportunityTeamMember": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OpportunityTeamMemberHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "Order": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OrderFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OrderHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "OrderItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OrderItemFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OrderItemHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "OrderShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "OrderStatus": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "is_supported_by_bulk_api": False,
    },
    "OrgDeleteRequest": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OrgDeleteRequestShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "OrgMetric": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OrgMetricScanResult": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OrgMetricScanSummary": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OrgWideEmailAddress": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Organization": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "OutOfOffice": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PackageLicense": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Partner": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PartnerFundAllocation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PartnerFundAllocationFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PartnerFundAllocationHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "PartnerFundClaim": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PartnerFundClaimFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PartnerFundClaimHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "PartnerFundRequest": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PartnerFundRequestFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PartnerFundRequestHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "PartnerMarketingBudget": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PartnerMarketingBudgetFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PartnerMarketingBudgetHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "PartnerRole": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "is_supported_by_bulk_api": False,
    },
    "PartyConsent": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PartyConsentFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PartyConsentHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "PartyConsentShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "Payment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PaymentAuthAdjustment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PaymentAuthorization": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PaymentGateway": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PaymentGatewayLog": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PaymentGatewayProvider": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PaymentGroup": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PaymentLineInvoice": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PaymentMethod": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Period": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PermissionSet": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PermissionSetAssignment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PermissionSetEventStore": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "PermissionSetGroup": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PermissionSetGroupComponent": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PermissionSetLicense": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PermissionSetLicenseAssign": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PermissionSetTabSetting": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PlatformCachePartition": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PlatformCachePartitionType": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Pricebook2": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Pricebook2History": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "PricebookEntry": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PricebookEntryHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ProcessDefinition": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProcessException": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProcessExceptionShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ProcessInstance": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProcessInstanceNode": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProcessInstanceStep": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProcessInstanceWorkitem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProcessNode": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Product2": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Product2Feed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Product2History": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ProductAttribute": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProductAttributeSet": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProductAttributeSetItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProductAttributeSetProduct": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProductCatalog": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProductCatalogFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProductCatalogHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ProductCatalogShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ProductCategory": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProductCategoryFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProductCategoryHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ProductCategoryProduct": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProductCategoryProductHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ProductConsumptionSchedule": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ProductEntitlementTemplate": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Profile": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Promotion": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PromotionFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PromotionHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "PromotionMarketSegment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PromotionMarketSegmentFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PromotionMarketSegmentHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "PromotionQualifier": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PromotionQualifierHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "PromotionSegment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PromotionSegmentBuyerGroup": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PromotionSegmentBuyerGroupHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "PromotionSegmentHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "PromotionSegmentSalesStore": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PromotionSegmentSalesStoreHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "PromotionSegmentShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "PromotionShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "PromotionTarget": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PromotionTargetHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "Prompt": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PromptAction": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PromptActionShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "PromptError": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "PromptErrorShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "PromptVersion": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Publisher": {},
    "PushTopic": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "QueueSobject": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "QuickText": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "QuickTextHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "QuickTextShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "QuickTextUsage": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "QuickTextUsageShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "Quote": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
    },
    "QuoteLineItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
    },
    "Recommendation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "RecommendationResponse": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "RecordAction": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "RecordType": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "RedirectWhitelistUrl": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Refund": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "RefundLinePayment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Report": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ReportAnomalyEventStore": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ReportAnomalyEventStoreFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ReportFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ResourceAbsence": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ResourceAbsenceFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ResourceAbsenceHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ResourcePreference": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ResourcePreferenceFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ResourcePreferenceHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ReturnOrder": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ReturnOrderFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ReturnOrderHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ReturnOrderItemAdjustment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ReturnOrderItemTax": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ReturnOrderLineItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ReturnOrderLineItemFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ReturnOrderLineItemHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ReturnOrderShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "SPSamlAttributes": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SalesStore": {},
    "SamlSsoConfig": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Scontrol": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SearchPromotionRule": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SecurityCustomBaseline": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ServiceAppointment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "ServiceAppointmentFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ServiceAppointmentHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ServiceAppointmentShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ServiceAppointmentStatus": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "is_supported_by_bulk_api": False,
    },
    "ServiceContract": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "ServiceContractFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ServiceContractHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ServiceContractShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ServiceResource": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ServiceResourceFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ServiceResourceHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ServiceResourceShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ServiceResourceSkill": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ServiceResourceSkillFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ServiceResourceSkillHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ServiceSetupProvisioning": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ServiceTerritory": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ServiceTerritoryFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ServiceTerritoryHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ServiceTerritoryMember": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ServiceTerritoryMemberFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ServiceTerritoryMemberHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ServiceTerritoryShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ServiceTerritoryWorkType": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ServiceTerritoryWorkTypeFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ServiceTerritoryWorkTypeHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "SessionHijackingEventStore": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SessionHijackingEventStoreFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SessionPermSetActivation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SetupAssistantStep": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SetupAuditTrail": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "SetupEntityAccess": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SharingRecordCollection": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Shift": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ShiftFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ShiftHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ShiftShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "ShiftStatus": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "is_supported_by_bulk_api": False,
    },
    "Shipment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ShipmentFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ShipmentHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ShipmentItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ShipmentItemFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ShipmentItemHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "ShipmentShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "Site": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SiteFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SiteHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "SiteIframeWhiteListUrl": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SiteRedirectMapping": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Skill": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SkillRequirement": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SkillRequirementFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SkillRequirementHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "SlaProcess": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SocialPersona": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SocialPersonaHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "SocialPost": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SocialPostFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SocialPostHistory": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Solution": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SolutionFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SolutionHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "SolutionStatus": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "is_supported_by_bulk_api": False,
    },
    "Stamp": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "StampAssignment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "StaticResource": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "StreamingChannel": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "StreamingChannelShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "Survey": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SurveyEngagementContext": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "SurveyEngagementContextShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "SurveyInvitation": {

    },
    "SurveyQuestionScore": {

    },
    "TabDefinition": {},
    "Task": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "TaskFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "TaskRecurrenceException": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "TaskRelation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "TaskWhoRelation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "TaskPriority": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "is_supported_by_bulk_api": False,
    },
    "TaskStatus": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "is_supported_by_bulk_api": False,
    },
    "TenantUsageEntitlement": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "TestSuiteMembership": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ThirdPartyAccountLink": {},
    "ThreatDetectionFeedback": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "ThreatDetectionFeedbackFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "TimeSlot": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "TodayGoal": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "TodayGoalShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "Topic": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "TopicAssignment": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "TopicFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "TopicUserEvent": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "TransactionSecurityPolicy": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "Translation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UiFormulaCriterion": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UiFormulaRule": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UndecidedEventRelation": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "is_supported_by_bulk_api": False,
    },
    "User": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "UserAccountTeamMember": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserAppInfo": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserAppMenuCustomization": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserAppMenuCustomizationShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "UserAppMenuItem": {},
    "UserEmailPreferredPerson": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserEmailPreferredPersonShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "UserFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserLicense": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserListView": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserListViewCriterion": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserLogin": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "UserPackageLicense": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserPreference": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserProvAccount": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserProvAccountStaging": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserProvMockTarget": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserProvisioningConfig": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserProvisioningLog": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserProvisioningRequest": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserProvisioningRequestShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "UserRole": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "UserServicePresence": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "UserShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "UserTeamMember": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "VerificationHistory": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "VideoCall": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "VideoCallFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "VideoCallParticipant": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "VideoCallRecording": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "VideoCallShare": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "VisualforceAccessMetrics": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "VoiceCall": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "VoiceCallFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "VoiceCallRecording": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "VoiceCallShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "VoiceVendorInfo": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WaveAutoInstallRequest": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WaveCompatibilityCheckItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WebCart": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WebCartAdjustmentGroup": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WebCartHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "WebCartShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "WebLink": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WebStore": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WebStoreBuyerGroup": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WebStoreCatalog": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WebStoreCatalogHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "WebStoreShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "WorkAccess": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkAccessShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "WorkBadge": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkBadgeDefinition": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkBadgeDefinitionFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkBadgeDefinitionHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "WorkBadgeDefinitionShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "WorkOrder": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "WorkOrderFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkOrderHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "WorkOrderLineItem": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
        "enabled_by_default": True,
    },
    "WorkOrderLineItemFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkOrderLineItemHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "WorkOrderLineItemStatus": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
    },
    "WorkOrderShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "WorkOrderStatus": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP,
    },
    "WorkPlan": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkPlanFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkPlanHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "WorkPlanShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "WorkPlanTemplate": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkPlanTemplateEntry": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkPlanTemplateEntryFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkPlanTemplateEntryHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "WorkPlanTemplateFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkPlanTemplateHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "WorkPlanTemplateShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "WorkStep": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkStepFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkStepHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "WorkStepStatus": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkStepTemplate": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkStepTemplateFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkStepTemplateHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "WorkStepTemplateShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "WorkThanks": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkThanksShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "WorkType": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkTypeFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkTypeGroup": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkTypeGroupFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkTypeGroupHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "WorkTypeGroupMember": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkTypeGroupMemberFeed": {
        "cursor_field": CursorFields.SYSTEM_MODSTAMP
    },
    "WorkTypeGroupMemberHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "WorkTypeGroupShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
    "WorkTypeHistory": {
        "cursor_field": CursorFields.CREATED_DATE
    },
    "WorkTypeShare": {
        "cursor_field": CursorFields.LAST_MODIFIED_DATE
    },
}
