[tool.poetry]
name = "source-jira"
version = "0.1.0"
description = ""
authors = ["Luishfs <luish1980@hotmail.com>"]

[tool.poetry.dependencies]
airbyte-cdk = "^0.52"
estuary-cdk = {path="../estuary-cdk", develop = true}
pydantic = "==1.10.14"
python = "^3.12"
types-requests = "^2.31"
responses = "^0.25.3"

[tool.poetry.group.dev.dependencies]
debugpy = "^1.8.0"
mypy = "^1.8.0"
pytest = "^7.4.3"
pytest-insta = "^0.3.0"
requests-mock = "^1.11.0"
pytest-mock = "^3.12.0"
mock = "^5.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
