credentials:
    client_id_sops: ENC[AES256_GCM,data:cN4R7R7ixwd0QiX9uanxOSx9xsGmTi4oEHX6vNbTAdY6VFiU,iv:2fvIsHIOv4YtAgWb0P777akB5LZyRNXXpRU9IJp2q5Y=,tag:VqxBHJO6I21yMiHpw6nHBg==,type:str]
    client_secret_sops: ENC[AES256_GCM,data:UlJR+XVn0rgji2eoxy6pe0xUFa3QqrfGyxsGDwo3ntRR4z0/,iv:zn0YVI1gE5vOKzfeaCw1qYe76375RhRBJdPDL/mO90k=,tag:P0ziOgenDQKUUdZyFp8sZA==,type:str]
    credentials_title: OAuth Credentials
    refresh_token_sops: ENC[AES256_GCM,data:XPQZka/ecPGbVEC2vW5p0c9ogQnTo1s/gM3+qED4o364fL/e,iv:fDoSfNULUVXY7G/w7pvkiiTHykZnsKfK99F3lUZxU08=,tag:48VDYM6CzYXvbhwPZNjOLw==,type:str]
    access_token_sops: ""
    token_expiry_date: "2024-02-01T17:01:21.703Z"
start_date: "2024-01-01T12:00:00Z"
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-02-01T17:08:49Z"
          enc: CiQAdmEdwu+udGkiZbfnnE8djh5o4P8p4Rm3WeXcN0XpcDF4sewSSQCVvC1zSqNDZIN7J2EPjuvJM4ILtloOm9w/OGsE4YwB2qH+sKsDDBYuIDDXtHml6w4wG0iksPY1Yxty0casvU6v02mfM3QOvyk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-15T21:12:36Z"
    mac: ENC[AES256_GCM,data:4RO1xaK3t+d0okl0FGpcXbaxH/j0wuJ5IAXT+t8qreUd0qfTDTWIJdcI27/x7oO3k13q15Ri8SKJ/rSUOHPSPtbmjVPUqQyBLaM2BO0zqrEJcSINhNkW9ldqMYet/QhUVZ+fY56rv1p1amCw70+jvpHFjaoLaiwww3jaJeofb5I=,iv:J2YUq8ceQ+Edrl9KGtiXgHUTha5MoyA4L8GCAI5aHbE=,tag:OexGNsQXRZFmwddX6nAf3g==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
