credentials:
    client_id_sops: ENC[AES256_GCM,data:cN4R7R7ixwd0QiX9uanxOSx9xsGmTi4oEHX6vNbTAdY6VFiU,iv:2fvIsHIOv4YtAgWb0P777akB5LZyRNXXpRU9IJp2q5Y=,tag:VqxBHJO6I21yMiHpw6nHBg==,type:str]
    client_secret_sops: ENC[AES256_GCM,data:UlJR+XVn0rgji2eoxy6pe0xUFa3QqrfGyxsGDwo3ntRR4z0/,iv:zn0YVI1gE5vOKzfeaCw1qYe76375RhRBJdPDL/mO90k=,tag:P0ziOgenDQKUUdZyFp8sZA==,type:str]
    credentials_title: OAuth Credentials
    refresh_token_sops: ENC[AES256_GCM,data:zq5LHlFXlTI6EuTarSJDcyM4pwsWWRBWOaVpOoZ0pPAeoYQg,iv:VTrLzsVGL4hUdX1fWOmYBFRo3Zflj5zZoXeEQRGGxMg=,tag:hBYD+mg6S1aM7AVRDUZBLg==,type:str]
start_date: "2024-10-01T00:00:00Z"
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-02-01T17:08:49Z"
          enc: CiQAdmEdwu+udGkiZbfnnE8djh5o4P8p4Rm3WeXcN0XpcDF4sewSSQCVvC1zSqNDZIN7J2EPjuvJM4ILtloOm9w/OGsE4YwB2qH+sKsDDBYuIDDXtHml6w4wG0iksPY1Yxty0casvU6v02mfM3QOvyk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-03T13:11:02Z"
    mac: ENC[AES256_GCM,data:+0RyCU1JotX4Bx9nATMaWpvCa7YG2cdHC8PnmPvCHEfnLtVNanE9WmiDin3oEpxkchmp8LDHscseSo5E1qg0Eu/m9OZDTnq7uAHtFlDt3oXVCSP3Z7Ou2BgPkpAcl4IBduIQSLoRFwiD6mjHvfn2gI91JPvl2eBLPf1cgHbZX1g=,iv:pyHZOOx0I3eVraEikHELh390BEsIileI/LUam9xAoOc=,tag:TYehKkeKoiPxuMpXwocX+g==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
