[tool.poetry]
name = "source-hubspot-estuary"
version = "0.1.0"
description = ""
authors = ["Flavio Riper <flavio@estuary.dev>"]

[tool.poetry.dependencies]
airbyte-cdk = "0.51.14"
mypy = "^1.5"
python = ">=3.11,<3.12"
debugpy = "^1.8.0"
source_hubspot = { path = "source_hubspot", develop = true }
flow-sdk = { path = "../python", develop = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"