version: "3.7"

services:
  postgres:
    image: 'postgres:latest'
    command: [ "postgres" ]
    environment:
      {
        "POSTGRES_DB": "flow",
        "POSTGRES_USER": "flow",
        "POSTGRES_PASSWORD": "flow"
      }
    networks:
      - flow-test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flow -d flow"]
      interval: 1s
      timeout: 5s
      retries: 20

networks:
  flow-test:
    name: flow-test
    external: true

volumes:
  postgres_data: {}
