version: "3.7"

services:
  postgres:
    image: 'postgres:latest'
    command: ["postgres"]
    environment: {"POSTGRES_DB": "flow", "POSTGRES_USER": "flow", "POSTGRES_PASSWORD": "flow"}
    networks:
      - flow-test
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  flow-test:
    name: flow-test
    external: true

volumes:
  postgres_data: {}
