credentials:
    credentials_title: Username & Password
    username: ADMIN
    password_sops: ENC[AES256_GCM,data:FGSxnL3s/ypQxYknguk=,iv:ZzTG15FBc2PomenS3tDZ2W3z2Er//GlQEjmir+mLQps=,tag:pdg/a4+f1qiDQuJagq8+Sg==,type:str]
address: (DESCRIPTION=(RETRY_COUNT=20)(RETRY_DELAY=3)(ADDRESS=(PROTOCOL=TCPS)(PORT=1521)(HOST=ADB.EU-FRANKFURT-1.ORACLECLOUD.COM))(CONNECT_DATA=(SERVICE_NAME=GCB2A4E9E921DD0_L6TEOA4HLL74YXRA_HIGH.ADB.ORACLECLOUD.COM))(SECURITY=(SSL_SERVER_DN_MATCH=YES)))
advanced:
    skip_flashback_retention_checks: true
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-02-01T17:08:49Z"
          enc: CiQAdmEdwu+udGkiZbfnnE8djh5o4P8p4Rm3WeXcN0XpcDF4sewSSQCVvC1zSqNDZIN7J2EPjuvJM4ILtloOm9w/OGsE4YwB2qH+sKsDDBYuIDDXtHml6w4wG0iksPY1Yxty0casvU6v02mfM3QOvyk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-25T16:28:08Z"
    mac: ENC[AES256_GCM,data:VCdKGGpVyrKsbh1JSqTA5VlCiB5y1DSMvyfQInf8yFycP0w2zGUKmy2+9r91R6bJFQanDGXxfLoFsUr+S6nacqBpYgwXqwCqyFIm0ivzb5iXwAsPTpwRZepC3szwnmaOfjCvXU1MfxduNaoyUwhz16e+fzubMDtKKnjImwLbBIk=,iv:w2jm7vtxutA0l5mjdoMe6nnbg1Kk+1ch+z2k3jS/xzU=,tag:mPUDWquta/KqRfcwlp3WRA==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
