user: flow_test_logminer
password_sops: ENC[AES256_GCM,data:MxI1FtGMMpYuoR+7,iv:v6suIe32GeqrD+eK6OXlCuVwCzsfD+DdH2wP8yugNqI=,tag:hvZzQV0jC/JKBtEwqdiarA==,type:str]
address: database-single.chqpmndqvzby.us-east-2.rds.amazonaws.com:1521
database: DATABASE
advanced:
    discover_schemas:
        - FLOW_TEST_LOGMINER
networkTunnel:
    sshForwarding:
        sshEndpoint: ssh://ec2-user@3.145.9.217:22
        privateKey_sops: ENC[AES256_GCM,data:G8wqtUbI323ziZ0sfI2TkV5siD8nuGeaHzgGyNJCDD3HePBCsEOVN+GcHyEyYU1yb2IsmIQ0MRnVEaouWSrXOd2ErnJIV8iZ1P2bkZk0NLQ0u2cpCqLDzR/nSnIemsg7LDrt2FmOJX72PzBkd8FnQ6VTFU6z0tvvQeCMAdtzMV0hO3J92LU0aoGnbHKG9HpcJCxFtDyV6bbO7SU758jMks0SA0lDSF6tBvb+MAVcIn9Ab3Qe7961vEVbx5SNVWNcB53rfhDrHtuIyT4NK5TO3DUs0yU+aj8BcXiIErtexpeQRxH4WDTYIaY2s6wpO54H4sQn6M1/2dqt+fsm1zqU922HXqLNQykfix7GZo9gKi0PEBXGYXB3+N1R6Q8H12l+QEOiAuY6KEcTfyTvVEJrhJXFmwYhuSPb04OQyFsYEXnEtmrjGiJWNz886cArZ8AyhAgmasaIsGgM4SeIsNsPIBf0MH7gfgj6d6BrScNz9+LOTLDlPzAHbJtW7Pv4Ny7/YiXPL3cxMlEhTqQUOTV+ZIiQYn6j4fCNmVgpxmpSAcEelDJuuKeFHBsV+hmDVdQo,iv:c32TVJf9H3DQWoSEkNjCe6TMf0Q0pVUx1+0P9b8GVV8=,tag:m0WKpdCnGZylByUNzdLdfg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-02-01T17:08:49Z"
          enc: CiQAdmEdwu+udGkiZbfnnE8djh5o4P8p4Rm3WeXcN0XpcDF4sewSSQCVvC1zSqNDZIN7J2EPjuvJM4ILtloOm9w/OGsE4YwB2qH+sKsDDBYuIDDXtHml6w4wG0iksPY1Yxty0casvU6v02mfM3QOvyk=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-19T10:19:16Z"
    mac: ENC[AES256_GCM,data:/Sy14+i/YZF5dVlHJQrV8gPA07/i0byKPPWYlGQIRZ/uLrleLjqr/SApcBuzr4gqi2xF/XhNUMtvz5TN8mJDFlilQdoMfL30Jv6DcbDWRd7RSW0kmd3H1sD0wwyc57qRmvHDQZatt8GUbLLVB1B974FWmYpoDb0egcHPnA2pPJg=,iv:+1Zr0dlumv+tZYdPKhegOtA2VeHS8cQ/XBIZTKXeqg4=,tag:I5jepukS4HKFSAkAUTE2hg==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
