-- Initialization script for source-oracle test database
-- This runs automatically when the container is first created

-- Enable ARCHIVELOG mode (required for dictionary_mode: extract)
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

-- Enable supplemental logging (required for LogMiner CDC)
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Create common user for LogMiner (must use C## prefix for common users in CDB)
CREATE USER C##FLOW_TEST_LOGMINER IDENTIFIED BY "secret1234" CONTAINER=ALL;

-- Grant privileges for LogMiner CDC
GRANT CREATE SESSION TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT SET CONTAINER TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT SELECT ON V_$INSTANCE TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT SELECT ON V_$LOG TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT SELECT ANY TABLE TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT LOGMINING TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT CREATE TABLE TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT CREATE VIEW TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT UNLIMITED TABLESPACE TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_LOGMNR TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_LOGMNR_D TO C##FLOW_TEST_LOGMINER CONTAINER=ALL;

-- Create watermarks table for backfill synchronization
CREATE TABLE C##FLOW_TEST_LOGMINER.FLOW_WATERMARKS (slot NUMBER PRIMARY KEY, watermark VARCHAR2(256));
