[tool.poetry]
name = "source_oracle"
version = "0.1.0"
description = ""
authors = ["Mahdi <mahdi@estuary.dev>"]

[tool.poetry.dependencies]
estuary-cdk = {path="../estuary-cdk", develop = true}
pydantic = "^2"
python = "^3.12"
pytz = "^2024.1"
Jinja2 = "^3.1.3"
oracledb = "^2.1.2"

[tool.poetry.group.dev.dependencies]
debugpy = "^1.8.0"
mypy = "^1.8.0"
pytest = "^7.4.3"
pytest-insta = "^0.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
