credentials:
    account_id: ZO9F-j1DRwey_9r4TjgA5A
    client_id: 3MvKFWg8QMKee0rrcPOMMg
    client_secret: 5Apr8xAo81M1rqGn7IDI3MnYgws7ERVl
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/helpful-kingdom-273219/locations/us-central1/keyRings/dev/cryptoKeys/CI-estuary-flow
          created_at: "2023-12-12T20:14:02Z"
          enc: CiQAW8BC2OzDaKKtm8zMjItUBjJQtYqREnBYSfylkxcHo5G+bQkSSQD00UdDsXRuXWefsumfRSQcy5hCrs20m+X9aE7yMmfBQJRWesgghg9f0RmablDPAZqn8iuIsx4xpu/tl4LY1Se2qHKTr7ZyZTg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-21T19:27:54Z"
    mac: ENC[AES256_GCM,data:fB67i0dnosE4TucBIGB+kOoN4Cxkry3qCgARdwoM+0JImRMMrKZi+orRT87kJxw4AbJiCbmfN/q+7+fwOqOzmWbtR9A/iT4jtTsATtUmF0CNWb+hYiZmVP+u1MmM1wnsuAaoqfY4RTqSlHtEYrl7H93Wff/dHISFzC5SqMALocw=,iv:+pJLxudtTo/T12ZeI3XW91c8ZJfPqcIGFlXwdK/oAtc=,tag:9HT3A9wJMXWsGxIO8lnK4g==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
