credentials:
    account_id: MqzG6aYDS_eTYHwEUYW7Hw
    client_id: aF1_kb6YR3iNp5HkhRV23A
    client_secret: QyzSOZ1oFFqU9pz3zxacaJglw7t13L3Q
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/helpful-kingdom-273219/locations/us-central1/keyRings/dev/cryptoKeys/CI-estuary-flow
          created_at: "2023-12-12T20:14:02Z"
          enc: CiQAW8BC2OzDaKKtm8zMjItUBjJQtYqREnBYSfylkxcHo5G+bQkSSQD00UdDsXRuXWefsumfRSQcy5hCrs20m+X9aE7yMmfBQJRWesgghg9f0RmablDPAZqn8iuIsx4xpu/tl4LY1Se2qHKTr7ZyZTg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-22T13:50:44Z"
    mac: ENC[AES256_GCM,data:kMRUIO+wgrXSXG3UEBwFWu33ghB8WU3ZFsCr2GQ9nlahQPYVlLMnsHa4U1H2eXV+DsjB4seO6oQJmwU9lURXJfo4GRT4FY0P5clbsdcynOP5AUHMVyGUewKuUs5lP28fk8ZmzhK3M14YiHlCdflxDomPbUwic9eVsxeccrVuSFU=,iv:8imN7e++b323+I2Bz3VGwudsw/OgsUsiL4hc4X9dOnU=,tag:12EAVxXbe4aXX4uFLPeziA==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
