client_secret_sops: ENC[AES256_GCM,data:CL324TemvkVDjN4ZwI8DVR08AGBkzK6ICpPlQD+oJO0=,iv:GI8+vFXvTw7t8pF2ci07Ig1vqWZ8op0SsJYWM8kHBRY=,tag:ZTWwt5DaPiLnbyntPf/Fcw==,type:str]
authorization_endpoint: https://zoom.us/oauth/token
client_id: aF1_kb6YR3iNp5HkhRV23A
account_id: afdsaf
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/helpful-kingdom-273219/locations/us-central1/keyRings/dev/cryptoKeys/CI-estuary-flow
          created_at: "2023-12-12T20:14:02Z"
          enc: CiQAW8BC2OzDaKKtm8zMjItUBjJQtYqREnBYSfylkxcHo5G+bQkSSQD00UdDsXRuXWefsumfRSQcy5hCrs20m+X9aE7yMmfBQJRWesgghg9f0RmablDPAZqn8iuIsx4xpu/tl4LY1Se2qHKTr7ZyZTg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-14T17:41:48Z"
    mac: ENC[AES256_GCM,data:WLVvAdC0UOWDJ74bWr4WQa6s+0iDmFiLE1/1mxfUwRZ4OBqs3bfwTCKoyz+jRSIcHC2nAISKbRmsJFduyL827n8VUS1K2EJ0DXOxrhfdO5a01MQF7DByJK1TpGeEIKnka7VKwyz0Of0knDw3r/RYSRSTwgJsR0OGZm/7WnM6oi8=,iv:cjzi2d3xVFzkSmHLreieKWMMHBRsDf0kkKjvzYxZF64=,tag:C1sT8/9XkozuH55SnqG7wQ==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
