credentials:
    auth_type: oauth
    client_id_sops: ENC[AES256_GCM,data:TYpI2zbgebstHaUBAqmoOaUqahD/EnRD0Mza55i4iFc=,iv:X23td6UI3hainbTpjKmo25rL/ExDHgWeVGbREMExX28=,tag:+XatenQ5Yby83j9wduaRsQ==,type:str]
    client_secret_sops: ENC[AES256_GCM,data:UcWJ65O2VCwGcMwMSoyHveuLlCqXpMf7ueqL/U97VCU=,iv:QSjAMN0wdOUST2E+FS9RmSKGdSzjsufADFDikFxmq3A=,tag:NEFWT1iYDHA9oxZLO0PY0Q==,type:str]
    access_token_sops: ENC[AES256_GCM,data:EPVCi5YC19AeARCu4Y4I35m30hNJBTo3OWpHC28665Z81p2BTz8=,iv:i77FhRiunj98TGw6oHk+7iaDdLqOCLdEr4IFfdfTfkA=,tag:RZ25vUDNiVbPGQkXDE02Cg==,type:str]
store: estuary-testing-1
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2023-12-19T13:25:05Z"
          enc: CiQAdmEdwmjDSn1NNdMUXMUGzrNlxb+PmRnwO3SlDl7ECE2TEj8SSQCVvC1zgeSluXBB2sK8SHPxU5VLUcCcAoMUAYjww/YYhqowBhINH4xi+cC9zJaOZxU8Oq/jrGCzO0o1Kxr1HMKv4C3tyc6/4ck=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-19T13:25:06Z"
    mac: ENC[AES256_GCM,data:4Q4TmQjE1sz8aUZoEYZVZ1YgrIMfvoE5EE25BgQkhfidYcga+l3f8m8477d/ttK+QIOXitt4lbfor8rVcHRISbSvbY7E7tNCe42HCmJ7ZJ/b1u0PJaLn49eEM8i1Ck9VexTmRBqG6LgeYs56fVEoAg5XgVR6AfSRNXfmU3pWM7g=,iv:nYUss5MuYnPE2cq30N2ZB7mJ/35UL6KOYkUfRuA9Bus=,tag:PdmhRIxJH1eUfecwP4RD2g==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.7.3
