credentials:
    auth_type: oauth
    client_id_sops: ENC[AES256_GCM,data:th4bA5vmEOeij1OdYBO+KgL7YnpBOQOT4KR4E5t+NxA=,iv:8ETc1D93AvAcoYbjqog4CTvq51znj1dF8hG4DRwfMnk=,tag:tBOQ24wIYyucWhX5fsR65A==,type:str]
    client_secret_sops: ENC[AES256_GCM,data:40lB5n+kfple9tQOiNkvCQTa4VzeKq6Y21F11YVWj6c=,iv:5NNEL56+Hs8S5Y4dRoaa8zygrcCTH0ppbTuQEzKESms=,tag:+fOcS0m6Ii4M7J6SEaDumg==,type:str]
    access_token_sops: ENC[AES256_GCM,data:sgQspKJjwgzJGJFCEe9qJKrqmGtexNjXx6HKsZ40RZYTs9ZE1g8=,iv:nqWGZquM6nM0/7H+QX08G4N00v2e03J6GXNGajNlSVE=,tag:QnAUNo47EWl12lEb7g6tCQ==,type:str]
store: estuary-testing-1
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/helpful-kingdom-273219/locations/us-central1/keyRings/dev/cryptoKeys/CI-estuary-flow
          created_at: "2023-11-06T22:06:28Z"
          enc: CiQAW8BC2KWrtYhS2NB5azHyfI6skjH7GmNx2uiBnofwuaoQL1kSSQBgR/fK40ekUfW6PPnjNr+kE5JQaKNhnChZKW+/OOiakO4Lva1OTZo/b1HKcJzG8ZhaiAmGXhEwnXkzHYbTUuG8GEV1cyWscuI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-15T22:16:10Z"
    mac: ENC[AES256_GCM,data:+lMIjMuBGsrN6NGlKROjdbOMdRTeDtjdqqiibKezFw2/Hizm/s11N2M9pNu2E4zMUwwi7yOQUTYjtBXedVVJijuCmjkN/vGuikvxWUHkvyurWcfCmxNGRnt7uJKi1b4vSDgozxbVJeyw9LT9wzJlBAUm63EKSXssstW1JEF8yDA=,iv:a6mO2jNIZw5hpasIvTM3yadzfBI8kq4tVkHWTm0Uu0o=,tag:TnU+QkOSuN1rmauWd095Ag==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.7.3
