[tool.poetry]
name = "source-shopify-estuary"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "<3.12,>=3.11"
singer-sdk = "^0.33.0"
flow-sdk = {path="../python", develop=true}
tap-shopify = { path = "source_shopify", develop=true }
debugpy = "^1.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
