[tool.poetry]
name = "source_shopify"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "<3.12,>=3.11"
singer-sdk = "^0.33.0"
flow-sdk = { path = "../python", develop = true }
tap-shopify = { path = "source_shopify", develop = true }
debugpy = "^1.8.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-insta = "^0.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
