---
tap_stream_id: discount_code
replication_method: FULL_TABLE
key_properties:
  - id
stream: discount_code
metadata:
  - breadcrumb:
      - properties
      - code
    metadata:
      inclusion: available
      selected: true
  - breadcrumb:
      - properties
      - created_at
    metadata:
      inclusion: available
      selected: true
  - breadcrumb:
      - properties
      - updated_at
    metadata:
      inclusion: available
      selected: true
  - breadcrumb:
      - properties
      - id
    metadata:
      inclusion: automatic
  - breadcrumb:
      - properties
      - price_rule_id
    metadata:
      inclusion: available
      selected: true
  - breadcrumb:
      - properties
      - usage_count
    metadata:
      inclusion: available
      selected: true
  - breadcrumb:
      - properties
      - errors
    metadata:
      inclusion: available
      selected: true
  - breadcrumb: []
    metadata:
      inclusion: available
      selected: true
      selected-by-default: true
      table-key-properties:
        - id
