credentials:
    auth_type: apikey
    apikey_sops: ENC[AES256_GCM,data:4B/VTwYCkB2uc3QM0DBRk757/eqaJ1FzAdwbwbgkVzpCtgv3tQ==,iv:CleHnlAI6iCB6oRxIoYVJ4Oaw6QBOBlB8RgwDrDzeSU=,tag:+pdWVoiHyOHh1uczEMGJxg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2024-04-26T02:11:51Z"
          enc: CiQAdmEdwpe7go7loWHFoP1QD0mqsGfqLq1/3jJuZSlmkJmPhmASSQCSobQjpuhj0SICJqn2EBxhNXDcndy4FOOhsMoxDwj7BbazTokCBtTFI1AA2jjllh0LxVoOa8+C2KJpQxGAQayZ2kq2XIzldCI=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-26T02:11:52Z"
    mac: ENC[AES256_GCM,data:l2QNjQI5oHC4T93MqB9LQCPkInF4sf2X1CjYTbmIcUgQnniHHNFAHMwT0SbYg0IcQwMJEJoItEoVqhA1dpc9M4n9TbIios2PFPUvdYPeiJb1B9NXGaMQDZ25H7GSG1SQ12Dw4fjGjyGYvyuAgo5Ok/kXuhTsQYE0VWY8vd0gBmM=,iv:y0JMPEGuUcyRS99GSK2qfAwFNCXGdm22xUcplyaLMoY=,tag:L1Gby/By5gJ1DluYUNOg5g==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.8.1
