[tool.poetry]
name = "source-mailchimp"
version = "0.1.0"
description = ""
authors = ["Luishfs <luish1980@hotmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
airbyte-cdk = "^0.52"
estuary-cdk = {path="../estuary-cdk", develop = true}
pydantic = "==1.10.14"

[tool.poetry.group.dev.dependencies]
debugpy = "^1.8.0"
mypy = "^1.8.0"
pytest = "^7.4.3"
pytest-insta = "^0.3.0"
mock = "^5.1.0"
pytest-mock = "^3.6.1"
requests-mock = "^1.9.3"
freezegun = "^1.4.0"
responses = "==0.25"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
