# Facebook Marketing API Field Type Registry
# Derived from Airbyte connector schemas to ensure 1:1 type matching
# Common fields have consistent types across all resources

from .enums import ActionBreakdown, Breakdown, DeliveryStatus, Field

# Field type registry
# - Simple types: str, int, float, bool, list
# - Untyped nested: dict (the type itself means any dict, no field coercion)
# - Typed nested: dict instance like {"id": str, "name": str} enables recursive field coercion
FIELD_TYPES: dict[Field, type | dict[str, type | dict]] = {
    Field.ACCOUNT_ID: str,
    Field.ACCOUNT_STATUS: int,
    Field.ACTOR_ID: str,
    Field.ACTOR_NAME: str,
    Field.AD_BREAKS: list,
    Field.ADLABELS: list,
    Field.ADSET_ID: str,
    Field.AGE: float,
    Field.APPLICATION_ID: str,
    Field.APPLICATION_NAME: str,
    Field.AMOUNT_SPENT: str,
    Field.APPLINK_TREATMENT: str,
    # Nested typed object - inline schema with recursive field type coercion
    Field.ASSET_FEED_SPEC: {
        "ad_formats": list,
        "autotranslate": str,
        "bodies": list,
        "call_to_action_types": list,
        "call_to_actions": list,
        "captions": list,
        "descriptions": list,
        "groups": list,
        "images": list,
        "link_urls": list,
        "titles": list,
        "videos": list,
        # Note: additional_data and asset_customization_rules kept as dict/list
    },
    Field.BACKDATED_TIME: str,
    Field.BACKDATED_TIME_GRANULARITY: str,
    Field.BALANCE: str,
    Field.BID_AMOUNT: float,
    # Nested typed object
    Field.BID_CONSTRAINTS: {
        "roas_average_floor": int,
    },
    # Nested typed object
    Field.BID_INFO: {
        "CLICKS": int,
        "ACTIONS": int,
        "IMPRESSIONS": int,
        "REACH": int,
        "SOCIAL": int,  # Only in ads, not in ad_sets
    },
    Field.BID_STRATEGY: str,
    Field.BID_TYPE: str,
    Field.BODY: str,
    Field.BUDGET_REBALANCE_FLAG: bool,
    Field.BUDGET_REMAINING: float,
    # Nested typed object
    Field.BUSINESS: {
        "id": str,
        "name": str,
    },
    Field.BUSINESS_CITY: str,
    Field.BUSINESS_COUNTRY_CODE: str,
    Field.BUSINESS_NAME: str,
    Field.BUSINESS_STATE: str,
    Field.BUSINESS_STREET: str,
    Field.BUSINESS_STREET2: str,
    Field.BUSINESS_ZIP: str,
    Field.BUYING_TYPE: str,
    Field.CALL_TO_ACTION_TYPE: str,
    Field.CAMPAIGN_ID: str,
    Field.CAN_CREATE_BRAND_LIFT_STUDY: bool,
    Field.CAPABILITIES: list,
    Field.CONTENT_CATEGORY: str,
    Field.CONTENT_TAGS: list,
    Field.CONVERSION_SPECS: list,
    Field.CREATED_TIME: str,
    Field.CREATION_TIME: str,
    # Nested typed object
    Field.CREATIVE: {
        "creative_id": str,
        "id": str,
    },
    Field.CREATIVES: list,
    Field.CURRENCY: str,
    Field.CUSTOM_EVENT_TYPE: str,
    Field.CUSTOM_LABELS: list,
    Field.DAILY_BUDGET: float,
    Field.DATA_SOURCES: list,
    Field.DATE_TIME_IN_TIMEZONE: str,
    Field.DEFAULT_CONVERSION_VALUE: float,
    Field.DESCRIPTION: str,
    Field.DISABLE_REASON: float,
    Field.EFFECTIVE_INSTAGRAM_STORY_ID: str,
    Field.EFFECTIVE_OBJECT_STORY_ID: str,
    Field.EFFECTIVE_STATUS: str,
    Field.EMBED_HTML: str,
    Field.EMBEDDABLE: bool,
    Field.END_ADVERTISER: float,
    Field.END_ADVERTISER_NAME: str,
    Field.END_TIME: str,
    Field.EVENT_SOURCE_TYPE: str,
    Field.EVENT_TIME: str,
    Field.EVENT_TYPE: str,
    Field.EXTRA_DATA: str,
    # Nested typed object
    Field.EXTENDED_CREDIT_INVOICE_GROUP: {
        "id": str,
        "auto_enroll": bool,
        "customer_po_number": str,
        "email": str,
        "emails": list,
        "name": str,
    },
    Field.FAILED_DELIVERY_CHECKS: list,
    Field.FB_ENTITY: float,
    Field.FILENAME: str,
    Field.FIRST_FIRED_TIME: str,
    Field.FORMAT: list,
    Field.FUNDING_SOURCE: float,
    # Nested typed object
    Field.FUNDING_SOURCE_DETAILS: {
        "display_string": str,
        "id": str,
        "type": int,
    },
    Field.HASH: str,
    Field.HAS_MIGRATED_PERMISSIONS: bool,
    Field.HEIGHT: int,
    Field.ICON: str,
    Field.ID: str,
    Field.IMAGE_CROPS: dict,
    Field.IMAGE_HASH: str,
    Field.IMAGE_URL: str,
    Field.INSTAGRAM_ACTOR_ID: str,
    Field.INSTAGRAM_PERMALINK_URL: str,
    Field.INSTAGRAM_STORY_ID: str,
    Field.IO_NUMBER: float,
    Field.IS_ARCHIVED: bool,
    Field.IS_ASSOCIATED_CREATIVES_IN_ADGROUPS: bool,
    Field.IS_ATTRIBUTION_SPEC_SYSTEM_DEFAULT: bool,
    Field.IS_CROSSPOST_VIDEO: bool,
    Field.IS_CROSSPOSTING_ELIGIBLE: bool,
    Field.IS_DIRECT_DEALS_ENABLED: bool,
    Field.IS_EPISODE: bool,
    Field.IS_IN_3DS_AUTHORIZATION_ENABLED_MARKET: bool,
    Field.IS_INSTAGRAM_ELIGIBLE: bool,
    Field.IS_NOTIFICATIONS_ENABLED: bool,
    Field.IS_PERSONAL: float,
    Field.IS_PREPAY_ACCOUNT: bool,
    Field.IS_TAX_ID_REQUIRED: bool,
    Field.IS_UNAVAILABLE: bool,
    Field.ISSUES_INFO: list,
    Field.LAST_FIRED_TIME: str,
    Field.LAST_UPDATED_BY_APP_ID: str,
    Field.LENGTH: float,
    Field.LIFETIME_BUDGET: float,
    Field.LINE_NUMBERS: float,
    Field.LINK_OG_ID: str,
    Field.LINK_URL: str,
    Field.LIVE_STATUS: str,
    Field.MEDIA_AGENCY: float,
    Field.MIN_CAMPAIGN_GROUP_SPEND_CAP: float,
    Field.MIN_DAILY_BUDGET: float,
    Field.NAME: str,
    Field.OBJECT_ID: str,
    Field.OBJECT_NAME: str,
    Field.OBJECT_STORY_ID: str,
    # Nested typed object
    Field.OBJECT_STORY_SPEC: {
        "page_id": str,
        "instagram_actor_id": str,
        # Note: link_data, photo_data, etc. are deeply nested, kept as dict
    },
    Field.OBJECT_TYPE: str,
    Field.OBJECT_URL: str,
    Field.OBJECTIVE: str,
    Field.OFFLINE_CONVERSION_DATA_SET: str,
    Field.OFFSITE_PIXELS_TOS_ACCEPTED: bool,
    Field.ORIGINAL_HEIGHT: int,
    Field.ORIGINAL_WIDTH: int,
    Field.OWNER: float,
    Field.PARTNER: float,
    Field.PERMALINK_URL: str,
    Field.POST_VIEWS: int,
    Field.PREMIERE_LIVING_ROOM_STATUS: bool,
    Field.PRODUCT_SET_ID: str,
    # Nested typed object
    Field.PROMOTED_OBJECT: {
        "custom_event_type": str,
        "pixel_id": str,
        "pixel_rule": str,
        "page_id": str,
        "object_store_url": str,
        "application_id": str,
        "product_set_id": str,
        "offer_id": str,
    },
    Field.PUBLISHED: bool,
    Field.RECOMMENDATIONS: list,
    Field.RETENTION_DAYS: float,
    # Nested typed object
    Field.RF_SPEC: {
        "countries": list,
        "global_io_max_campaign_duration": int,
        # Note: Deeper nested fields (max_campaign_duration, etc.) kept as dict
    },
    Field.RULE: str,
    Field.SCHEDULED_PUBLISH_TIME: str,
    Field.SMART_PROMOTION_TYPE: str,
    Field.SOURCE: str,
    Field.SOURCE_AD_ID: str,
    Field.SOURCE_CAMPAIGN_ID: float,
    Field.SPECIAL_AD_CATEGORY: str,
    Field.SPECIAL_AD_CATEGORY_COUNTRY: list,
    Field.START_TIME: str,
    Field.STATUS: str,
    Field.STOP_TIME: str,
    Field.TARGETING: dict,
    Field.TAX_ID: str,
    Field.TAX_ID_STATUS: float,
    Field.TAX_ID_TYPE: str,
    Field.TEMPLATE_URL: str,
    # Nested typed object (empty schema, deeper nesting kept as dict)
    Field.TEMPLATE_URL_SPEC: dict,
    Field.THUMBNAIL_DATA_URL: str,
    Field.THUMBNAIL_URL: str,
    Field.TIMEZONE_ID: float,
    Field.TIMEZONE_NAME: str,
    Field.TIMEZONE_OFFSET_HOURS_UTC: float,
    Field.TITLE: str,
    # Nested typed object
    Field.TOS_ACCEPTED: {
        "web_custom_audience_tos": int,
    },
    Field.TRACKING_SPECS: list,
    Field.TRANSLATED_EVENT_TYPE: str,
    Field.UNIVERSAL_VIDEO_ID: str,
    Field.UPDATED_TIME: str,
    Field.URL: str,
    Field.URL_128: str,
    Field.URL_TAGS: str,
    Field.USER_TASKS: list,
    # Nested typed object
    Field.USER_TOS_ACCEPTED: {
        "web_custom_audience_tos": int,
    },
    Field.VIDEO_ID: str,
    Field.VIEWS: int,
    Field.WIDTH: int,
}

# Resource-specific field type overrides
# Handle cases where same field name has different types in different resources
RESOURCE_OVERRIDES: dict[str, dict[Field, type | dict[str, type | dict]]] = {
    "ad_account": {
        Field.BUSINESS: dict,  # Override: untyped dict in ad_account (vs typed nested in common)
        Field.SPEND_CAP: str,
    },
    "ads": {
        Field.BID_AMOUNT: int,  # Override: int in ads, float in common
    },
    "campaigns": {
        Field.SPEND_CAP: float,
    },
    "custom_conversions": {
        Field.BUSINESS: str,  # Override: string in custom_conversions (vs typed nested in common)
    },
    "ads_insights": {
        Field.AGE: str,
        Field.GENDER: str,
    },
}

AD_INSIGHTS_VALID_FIELDS: list[str] = [
    Field.ACCOUNT_CURRENCY,
    Field.ACCOUNT_ID,
    Field.ACCOUNT_NAME,
    Field.ACTION_VALUES,
    Field.ACTIONS,
    Field.AD_CLICK_ACTIONS,
    Field.AD_ID,
    Field.AD_IMPRESSION_ACTIONS,
    Field.AD_NAME,
    Field.ADSET_END,
    Field.ADSET_ID,
    Field.ADSET_NAME,
    Field.ADSET_START,
    Field.AGE_TARGETING,
    Field.ATTRIBUTION_SETTING,
    Field.AUCTION_BID,
    Field.AUCTION_COMPETITIVENESS,
    Field.AUCTION_MAX_COMPETITOR_BID,
    Field.AVERAGE_PURCHASES_CONVERSION_VALUE,
    Field.BUYING_TYPE,
    Field.CAMPAIGN_ID,
    Field.CAMPAIGN_NAME,
    Field.CANVAS_AVG_VIEW_PERCENT,
    Field.CANVAS_AVG_VIEW_TIME,
    Field.CATALOG_SEGMENT_ACTIONS,
    Field.CATALOG_SEGMENT_VALUE,
    Field.CATALOG_SEGMENT_VALUE_MOBILE_PURCHASE_ROAS,
    Field.CATALOG_SEGMENT_VALUE_OMNI_PURCHASE_ROAS,
    Field.CATALOG_SEGMENT_VALUE_WEBSITE_PURCHASE_ROAS,
    Field.CLICKS,
    Field.CONVERSION_LEAD_RATE,
    Field.CONVERSION_LEADS,
    Field.CONVERSION_RATE_RANKING,
    Field.CONVERSION_VALUES,
    Field.CONVERSIONS,
    Field.CONVERTED_PRODUCT_APP_CUSTOM_EVENT_FB_MOBILE_PURCHASE,
    Field.CONVERTED_PRODUCT_APP_CUSTOM_EVENT_FB_MOBILE_PURCHASE_VALUE,
    Field.CONVERTED_PRODUCT_OFFLINE_PURCHASE,
    Field.CONVERTED_PRODUCT_OFFLINE_PURCHASE_VALUE,
    Field.CONVERTED_PRODUCT_OMNI_PURCHASE,
    Field.CONVERTED_PRODUCT_OMNI_PURCHASE_VALUES,
    Field.CONVERTED_PRODUCT_QUANTITY,
    Field.CONVERTED_PRODUCT_VALUE,
    Field.CONVERTED_PRODUCT_WEBSITE_PIXEL_PURCHASE,
    Field.CONVERTED_PRODUCT_WEBSITE_PIXEL_PURCHASE_VALUE,
    Field.CONVERTED_PROMOTED_PRODUCT_APP_CUSTOM_EVENT_FB_MOBILE_PURCHASE,
    Field.CONVERTED_PROMOTED_PRODUCT_APP_CUSTOM_EVENT_FB_MOBILE_PURCHASE_VALUE,
    Field.CONVERTED_PROMOTED_PRODUCT_OFFLINE_PURCHASE,
    Field.CONVERTED_PROMOTED_PRODUCT_OFFLINE_PURCHASE_VALUE,
    Field.CONVERTED_PROMOTED_PRODUCT_OMNI_PURCHASE,
    Field.CONVERTED_PROMOTED_PRODUCT_OMNI_PURCHASE_VALUES,
    Field.CONVERTED_PROMOTED_PRODUCT_QUANTITY,
    Field.CONVERTED_PROMOTED_PRODUCT_VALUE,
    Field.CONVERTED_PROMOTED_PRODUCT_WEBSITE_PIXEL_PURCHASE,
    Field.CONVERTED_PROMOTED_PRODUCT_WEBSITE_PIXEL_PURCHASE_VALUE,
    Field.COST_PER_15_SEC_VIDEO_VIEW,
    Field.COST_PER_2_SEC_CONTINUOUS_VIDEO_VIEW,
    Field.COST_PER_ACTION_TYPE,
    Field.COST_PER_AD_CLICK,
    Field.COST_PER_CONVERSION,
    Field.COST_PER_CONVERSION_LEAD,
    Field.COST_PER_DDA_COUNTBY_CONVS,
    Field.COST_PER_ESTIMATED_AD_RECALLERS,
    Field.COST_PER_INLINE_LINK_CLICK,
    Field.COST_PER_INLINE_POST_ENGAGEMENT,
    Field.COST_PER_OBJECTIVE_RESULT,
    Field.COST_PER_ONE_THOUSAND_AD_IMPRESSION,
    Field.COST_PER_OUTBOUND_CLICK,
    Field.COST_PER_RESULT,
    Field.COST_PER_THRUPLAY,
    Field.COST_PER_UNIQUE_ACTION_TYPE,
    Field.COST_PER_UNIQUE_CLICK,
    Field.COST_PER_UNIQUE_CONVERSION,
    Field.COST_PER_UNIQUE_INLINE_LINK_CLICK,
    Field.COST_PER_UNIQUE_OUTBOUND_CLICK,
    Field.CPC,
    Field.CPM,
    Field.CPP,
    Field.CREATED_TIME,
    Field.CREATIVE_MEDIA_TYPE,
    Field.CTR,
    Field.DATE_START,
    Field.DATE_STOP,
    Field.DDA_COUNTBY_CONVS,
    Field.DDA_RESULTS,
    Field.ENGAGEMENT_RATE_RANKING,
    Field.ESTIMATED_AD_RECALL_RATE,
    Field.ESTIMATED_AD_RECALL_RATE_LOWER_BOUND,
    Field.ESTIMATED_AD_RECALL_RATE_UPPER_BOUND,
    Field.ESTIMATED_AD_RECALLERS,
    Field.ESTIMATED_AD_RECALLERS_LOWER_BOUND,
    Field.ESTIMATED_AD_RECALLERS_UPPER_BOUND,
    Field.FREQUENCY,
    Field.FULL_VIEW_IMPRESSIONS,
    Field.FULL_VIEW_REACH,
    Field.GENDER_TARGETING,
    Field.IMPRESSIONS,
    Field.INLINE_LINK_CLICK_CTR,
    Field.INLINE_LINK_CLICKS,
    Field.INLINE_POST_ENGAGEMENT,
    Field.INSTAGRAM_UPCOMING_EVENT_REMINDERS_SET,
    Field.INSTANT_EXPERIENCE_CLICKS_TO_OPEN,
    Field.INSTANT_EXPERIENCE_CLICKS_TO_START,
    Field.INSTANT_EXPERIENCE_OUTBOUND_CLICKS,
    Field.INTERACTIVE_COMPONENT_TAP,
    Field.LABELS,
    Field.LANDING_PAGE_VIEW_ACTIONS_PER_LINK_CLICK,
    Field.LANDING_PAGE_VIEW_PER_LINK_CLICK,
    Field.LANDING_PAGE_VIEW_PER_PURCHASE_RATE,
    Field.LOCATION,
    Field.MARKETING_MESSAGES_CLICK_RATE_BENCHMARK,
    Field.MARKETING_MESSAGES_COST_PER_DELIVERED,
    Field.MARKETING_MESSAGES_COST_PER_LINK_BTN_CLICK,
    Field.MARKETING_MESSAGES_DELIVERED,
    Field.MARKETING_MESSAGES_DELIVERY_RATE,
    Field.MARKETING_MESSAGES_LINK_BTN_CLICK,
    Field.MARKETING_MESSAGES_LINK_BTN_CLICK_RATE,
    Field.MARKETING_MESSAGES_MEDIA_VIEW_RATE,
    Field.MARKETING_MESSAGES_PHONE_CALL_BTN_CLICK_RATE,
    Field.MARKETING_MESSAGES_QUICK_REPLY_BTN_CLICK,
    Field.MARKETING_MESSAGES_QUICK_REPLY_BTN_CLICK_RATE,
    Field.MARKETING_MESSAGES_READ,
    Field.MARKETING_MESSAGES_READ_RATE,
    Field.MARKETING_MESSAGES_READ_RATE_BENCHMARK,
    Field.MARKETING_MESSAGES_SENT,
    Field.MARKETING_MESSAGES_SPEND,
    Field.MARKETING_MESSAGES_SPEND_CURRENCY,
    Field.MARKETING_MESSAGES_WEBSITE_ADD_TO_CART,
    Field.MARKETING_MESSAGES_WEBSITE_INITIATE_CHECKOUT,
    Field.MARKETING_MESSAGES_WEBSITE_PURCHASE,
    Field.MARKETING_MESSAGES_WEBSITE_PURCHASE_VALUES,
    Field.MOBILE_APP_PURCHASE_ROAS,
    Field.OBJECTIVE,
    Field.OBJECTIVE_RESULT_RATE,
    Field.OBJECTIVE_RESULTS,
    Field.ONSITE_CONVERSION_MESSAGING_DETECTED_PURCHASE_DEDUPED,
    Field.OPTIMIZATION_GOAL,
    Field.OUTBOUND_CLICKS,
    Field.OUTBOUND_CLICKS_CTR,
    Field.PLACE_PAGE_NAME,
    Field.PRODUCT_BRAND,
    Field.PRODUCT_CATEGORY,
    Field.PRODUCT_CONTENT_ID,
    Field.PRODUCT_CUSTOM_LABEL_0,
    Field.PRODUCT_CUSTOM_LABEL_1,
    Field.PRODUCT_CUSTOM_LABEL_2,
    Field.PRODUCT_CUSTOM_LABEL_3,
    Field.PRODUCT_CUSTOM_LABEL_4,
    Field.PRODUCT_GROUP_CONTENT_ID,
    Field.PRODUCT_GROUP_RETAILER_ID,
    Field.PRODUCT_NAME,
    Field.PRODUCT_RETAILER_ID,
    Field.PURCHASE_PER_LANDING_PAGE_VIEW,
    Field.PURCHASE_ROAS,
    Field.PURCHASES_PER_LINK_CLICK,
    Field.QUALIFYING_QUESTION_QUALIFY_ANSWER_RATE,
    Field.QUALITY_RANKING,
    Field.REACH,
    Field.RESULT_RATE,
    Field.RESULT_VALUES_PERFORMANCE_INDICATOR,
    Field.RESULTS,
    Field.SHOPS_ASSISTED_PURCHASES,
    Field.SOCIAL_SPEND,
    Field.SPEND,
    Field.TOTAL_POSTBACKS,
    Field.TOTAL_POSTBACKS_DETAILED,
    Field.TOTAL_POSTBACKS_DETAILED_V4,
    Field.UNIQUE_ACTIONS,
    Field.UNIQUE_CLICKS,
    Field.UNIQUE_CONVERSIONS,
    Field.UNIQUE_CTR,
    Field.UNIQUE_INLINE_LINK_CLICK_CTR,
    Field.UNIQUE_INLINE_LINK_CLICKS,
    Field.UNIQUE_LINK_CLICKS_CTR,
    Field.UNIQUE_OUTBOUND_CLICKS,
    Field.UNIQUE_OUTBOUND_CLICKS_CTR,
    Field.UNIQUE_VIDEO_CONTINUOUS_2_SEC_WATCHED_ACTIONS,
    Field.UNIQUE_VIDEO_VIEW_15_SEC,
    Field.UPDATED_TIME,
    Field.VIDEO_15_SEC_WATCHED_ACTIONS,
    Field.VIDEO_30_SEC_WATCHED_ACTIONS,
    Field.VIDEO_AVG_TIME_WATCHED_ACTIONS,
    Field.VIDEO_CONTINUOUS_2_SEC_WATCHED_ACTIONS,
    Field.VIDEO_P100_WATCHED_ACTIONS,
    Field.VIDEO_P25_WATCHED_ACTIONS,
    Field.VIDEO_P50_WATCHED_ACTIONS,
    Field.VIDEO_P75_WATCHED_ACTIONS,
    Field.VIDEO_P95_WATCHED_ACTIONS,
    Field.VIDEO_PLAY_ACTIONS,
    Field.VIDEO_PLAY_CURVE_ACTIONS,
    Field.VIDEO_PLAY_RETENTION_0_TO_15S_ACTIONS,
    Field.VIDEO_PLAY_RETENTION_20_TO_60S_ACTIONS,
    Field.VIDEO_PLAY_RETENTION_GRAPH_ACTIONS,
    Field.VIDEO_THRUPLAY_WATCHED_ACTIONS,
    Field.VIDEO_TIME_WATCHED_ACTIONS,
    Field.VIDEO_VIEW_PER_IMPRESSION,
    Field.WEBSITE_CTR,
    Field.WEBSITE_PURCHASE_ROAS,
]

AD_INSIGHTS_VALID_BREAKDOWNS: list[str] = [
    Breakdown.AD_EXTENSION_DOMAIN,
    Breakdown.AD_EXTENSION_URL,
    Breakdown.AD_FORMAT_ASSET,
    Breakdown.AGE,
    Breakdown.APP_ID,
    Breakdown.BODY_ASSET,
    Breakdown.BREAKDOWN_AD_OBJECTIVE,
    Breakdown.BREAKDOWN_REPORTING_AD_ID,
    Breakdown.CALL_TO_ACTION_ASSET,
    Breakdown.COARSE_CONVERSION_VALUE,
    Breakdown.COMSCORE_MARKET,
    Breakdown.COMSCORE_MARKET_CODE,
    Breakdown.CONVERSION_DESTINATION,
    Breakdown.COUNTRY,
    Breakdown.CREATIVE_RELAXATION_ASSET_TYPE,
    Breakdown.DESCRIPTION_ASSET,
    Breakdown.DEVICE_PLATFORM,
    Breakdown.DMA,
    Breakdown.FIDELITY_TYPE,
    Breakdown.FLEXIBLE_FORMAT_ASSET_TYPE,
    Breakdown.FREQUENCY_VALUE,
    Breakdown.GEN_AI_ASSET_TYPE,
    Breakdown.GENDER,
    Breakdown.HOURLY_STATS_AGGREGATED_BY_ADVERTISER_TIME_ZONE,
    Breakdown.HOURLY_STATS_AGGREGATED_BY_AUDIENCE_TIME_ZONE,
    Breakdown.HSID,
    Breakdown.IMAGE_ASSET,
    Breakdown.IMPRESSION_DEVICE,
    Breakdown.IMPRESSION_VIEW_TIME_ADVERTISER_HOUR_V2,
    Breakdown.IS_AUTO_ADVANCE,
    Breakdown.IS_CONVERSION_ID_MODELED,
    Breakdown.IS_RENDERED_AS_DELAYED_SKIP_AD,
    Breakdown.LANDING_DESTINATION,
    Breakdown.LINK_URL_ASSET,
    Breakdown.MARKETING_MESSAGES_BTN_NAME,
    Breakdown.MDSA_LANDING_DESTINATION,
    Breakdown.MEDIA_ASSET_URL,
    Breakdown.MEDIA_CREATOR,
    Breakdown.MEDIA_DESTINATION_URL,
    Breakdown.MEDIA_FORMAT,
    Breakdown.MEDIA_ORIGIN_URL,
    Breakdown.MEDIA_TEXT_CONTENT,
    Breakdown.MEDIA_TYPE,
    Breakdown.MMM,
    Breakdown.PLACE_PAGE_ID,
    Breakdown.PLATFORM_POSITION,
    Breakdown.POSTBACK_SEQUENCE_INDEX,
    Breakdown.PRODUCT_ID,
    Breakdown.PUBLISHER_PLATFORM,
    Breakdown.REDOWNLOAD,
    Breakdown.REGION,
    Breakdown.SIGNAL_SOURCE_BUCKET,
    Breakdown.SKAN_CAMPAIGN_ID,
    Breakdown.SKAN_CONVERSION_ID,
    Breakdown.SKAN_VERSION,
    Breakdown.SOT_ATTRIBUTION_MODEL_TYPE,
    Breakdown.SOT_ATTRIBUTION_WINDOW,
    Breakdown.SOT_CHANNEL,
    Breakdown.SOT_EVENT_TYPE,
    Breakdown.SOT_SOURCE,
    Breakdown.STANDARD_EVENT_CONTENT_TYPE,
    Breakdown.TITLE_ASSET,
    Breakdown.USER_PERSONA_ID,
    Breakdown.USER_PERSONA_NAME,
    Breakdown.VIDEO_ASSET,
]

AD_INSIGHTS_VALID_ACTION_BREAKDOWNS: list[str] = [
    ActionBreakdown.ACTION_CANVAS_COMPONENT_NAME,
    ActionBreakdown.ACTION_CAROUSEL_CARD_ID,
    ActionBreakdown.ACTION_CAROUSEL_CARD_NAME,
    ActionBreakdown.ACTION_DESTINATION,
    ActionBreakdown.ACTION_DEVICE,
    ActionBreakdown.ACTION_REACTION,
    ActionBreakdown.ACTION_TARGET_ID,
    ActionBreakdown.ACTION_TYPE,
    ActionBreakdown.ACTION_VIDEO_SOUND,
    ActionBreakdown.ACTION_VIDEO_TYPE,
    ActionBreakdown.CONVERSION_DESTINATION,
    ActionBreakdown.MATCHED_PERSONA_ID,
    ActionBreakdown.MATCHED_PERSONA_NAME,
    ActionBreakdown.SIGNAL_SOURCE_BUCKET,
    ActionBreakdown.STANDARD_EVENT_CONTENT_TYPE,
]

DELIVERY_INFO_FIELDS: list[str] = [
    DeliveryStatus.ACTIVE,
    DeliveryStatus.ARCHIVED,
    DeliveryStatus.COMPLETED,
    DeliveryStatus.LIMITED,
    DeliveryStatus.NOT_DELIVERING,
    DeliveryStatus.DELETED,
    DeliveryStatus.NOT_PUBLISHED,
    DeliveryStatus.PENDING_REVIEW,
    DeliveryStatus.PERMANENTLY_DELETED,
    DeliveryStatus.RECENTLY_COMPLETED,
    DeliveryStatus.RECENTLY_REJECTED,
    DeliveryStatus.REJECTED,
    DeliveryStatus.SCHEDULED,
    DeliveryStatus.INACTIVE,
]


def get_field_type(
    field: Field, resource_name: str | None = None
) -> type | dict[str, type | dict] | None:
    """
    Get the type for a field, considering resource-specific overrides.
    
    Type discrimination:
        - dict (the type) = untyped dict, no field coercion
        - dict instance = typed nested schema with recursive field coercion
    """
    if resource_name and resource_name in RESOURCE_OVERRIDES:
        if field in RESOURCE_OVERRIDES[resource_name]:
            return RESOURCE_OVERRIDES[resource_name][field]

    return FIELD_TYPES.get(field)
