# Facebook Marketing API Field Type Registry
# Derived from Airbyte connector schemas to ensure 1:1 type matching
# Common fields have consistent types across all resources (111 fields)
COMMON_FIELD_TYPES: dict[str, type] = {
    "account_id": str,
    "account_status": int,
    "actor_id": str,
    "actor_name": str,
    "ad_breaks": list,
    "adlabels": list,
    "adset_id": str,
    "age": float,
    "application_id": str,
    "application_name": str,
    "amount_spent": str,
    "applink_treatment": str,
    "asset_feed_spec": dict,
    "backdated_time": str,
    "backdated_time_granularity": str,
    "balance": str,
    "bid_amount": float,
    "bid_constraints": dict,
    "bid_info": dict,
    "bid_strategy": str,
    "bid_type": str,
    "body": str,
    "budget_rebalance_flag": bool,
    "budget_remaining": float,
    "business_city": str,
    "business_country_code": str,
    "business_name": str,
    "business_state": str,
    "business_street": str,
    "business_street2": str,
    "business_zip": str,
    "buying_type": str,
    "call_to_action_type": str,
    "campaign_id": str,
    "can_create_brand_lift_study": bool,
    "capabilities": list,
    "content_category": str,
    "content_tags": list,
    "conversion_specs": list,
    "created_time": str,
    "creation_time": str,
    "creative": dict,
    "creatives": list,
    "currency": str,
    "custom_event_type": str,
    "custom_labels": list,
    "daily_budget": float,
    "data_sources": list,
    "date_time_in_timezone": str,
    "default_conversion_value": float,
    "description": str,
    "disable_reason": float,
    "effective_instagram_story_id": str,
    "effective_object_story_id": str,
    "effective_status": str,
    "embed_html": str,
    "embeddable": bool,
    "end_advertiser": float,
    "end_advertiser_name": str,
    "end_time": str,
    "event_source_type": str,
    "event_time": str,
    "event_type": str,
    "extra_data": str,
    "extended_credit_invoice_group": dict,
    "failed_delivery_checks": list,
    "fb_entity": float,
    "filename": str,
    "first_fired_time": str,
    "format": list,
    "funding_source": float,
    "funding_source_details": dict,
    "hash": str,
    "has_migrated_permissions": bool,
    "height": int,
    "icon": str,
    "id": str,
    "image_crops": dict,
    "image_hash": str,
    "image_url": str,
    "instagram_actor_id": str,
    "instagram_permalink_url": str,
    "instagram_story_id": str,
    "io_number": float,
    "is_archived": bool,
    "is_associated_creatives_in_adgroups": bool,
    "is_attribution_spec_system_default": bool,
    "is_crosspost_video": bool,
    "is_crossposting_eligible": bool,
    "is_direct_deals_enabled": bool,
    "is_episode": bool,
    "is_in_3ds_authorization_enabled_market": bool,
    "is_instagram_eligible": bool,
    "is_notifications_enabled": bool,
    "is_personal": float,
    "is_prepay_account": bool,
    "is_tax_id_required": bool,
    "is_unavailable": bool,
    "issues_info": list,
    "last_fired_time": str,
    "last_updated_by_app_id": str,
    "length": float,
    "lifetime_budget": float,
    "line_numbers": float,
    "link_og_id": str,
    "link_url": str,
    "live_status": str,
    "media_agency": float,
    "min_campaign_group_spend_cap": float,
    "min_daily_budget": float,
    "name": str,
    "object_id": str,
    "object_name": str,
    "object_story_id": str,
    "object_story_spec": dict,
    "object_type": str,
    "object_url": str,
    "objective": str,
    "offline_conversion_data_set": str,
    "offsite_pixels_tos_accepted": bool,
    "original_height": int,
    "original_width": int,
    "owner": float,
    "partner": float,
    "permalink_url": str,
    "post_views": int,
    "premiere_living_room_status": bool,
    "product_set_id": str,
    "promoted_object": dict,
    "published": bool,
    "recommendations": list,
    "retention_days": float,
    "rf_spec": dict,
    "rule": str,
    "scheduled_publish_time": str,
    "smart_promotion_type": str,
    "source": str,
    "source_ad_id": str,
    "source_campaign_id": float,
    "special_ad_category": str,
    "special_ad_category_country": list,
    "start_time": str,
    "status": str,
    "stop_time": str,
    "targeting": dict,
    "tax_id": str,
    "tax_id_status": float,
    "tax_id_type": str,
    "template_url": str,
    "template_url_spec": dict,
    "thumbnail_data_url": str,
    "thumbnail_url": str,
    "timezone_id": float,
    "timezone_name": str,
    "timezone_offset_hours_utc": float,
    "title": str,
    "tos_accepted": dict,
    "tracking_specs": list,
    "translated_event_type": str,
    "universal_video_id": str,
    "updated_time": str,
    "url": str,
    "url_128": str,
    "url_tags": str,
    "user_tasks": list,
    "user_tos_accepted": dict,
    "video_id": str,
    "views": int,
    "width": int,
}

# Resource-specific field type overrides
# Handle cases where same field name has different types in different resources
RESOURCE_FIELD_TYPES: dict[str, dict[str, type]] = {
    "ad_account": {
        "business": dict,
        "spend_cap": str,
    },
    "ads": {
        "bid_amount": int,  # int in ads, float in ad_sets
    },
    "campaigns": {
        "spend_cap": float,
    },
    "custom_conversions": {
        "business": str,
    },
    "ads_insights": {
        "age": str,
        "gender": str,
    }
}

# Nested object field type definitions
# Maps object field names to their nested field schemas for recursive coercion
# Extracted from Airbyte schemas - handles 1-2 levels of nesting
NESTED_OBJECT_SCHEMAS: dict[str, dict[str, type]] = {
    "bid_constraints": {
        "roas_average_floor": int,
    },
    "bid_info": {
        "CLICKS": int,
        "ACTIONS": int,
        "IMPRESSIONS": int,
        "REACH": int,
        "SOCIAL": int,  # Only in ads, not in ad_sets
    },
    "business": {
        "id": str,
        "name": str,
    },
    "creative": {
        "creative_id": str,
        "id": str,
    },
    "extended_credit_invoice_group": {
        "id": str,
        "auto_enroll": bool,
        "customer_po_number": str,
        "email": str,
        "emails": list,
        "name": str,
    },
    "funding_source_details": {
        "display_string": str,
        "id": str,
        "type": int,
    },
    "tos_accepted": {
        "web_custom_audience_tos": int,
    },
    "user_tos_accepted": {
        "web_custom_audience_tos": int,
    },
    "rf_spec": {
        "countries": list,
        "global_io_max_campaign_duration": int,
        # Note: Deeper nested fields (max_campaign_duration, etc.) kept as dict
    },
    "asset_feed_spec": {
        "ad_formats": list,
        "autotranslate": str,
        "bodies": list,
        "call_to_action_types": list,
        "call_to_actions": list,
        "captions": list,
        "descriptions": list,
        "groups": list,
        "images": list,
        "link_urls": list,
        "titles": list,
        "videos": list,
        # Note: additional_data and asset_customization_rules kept as dict/list
    },
    "object_story_spec": {
        "page_id": str,
        "instagram_actor_id": str,
        # Note: link_data, photo_data, etc. are deeply nested, kept as dict
    },
    "promoted_object": {
        "custom_event_type": str,
        "pixel_id": str,
        "pixel_rule": str,
        "page_id": str,
        "object_store_url": str,
        "application_id": str,
        "product_set_id": str,
        "offer_id": str,
    },
    "template_url_spec": {
        # Note: Nested platform configs (android, ios, etc.) kept as dict
        # Each has 2-3 fields but adds too much complexity
    },
}

AD_INSIGHTS_VALID_FIELDS = [
    "account_currency",
    "account_id",
    "account_name",
    "action_values",
    "actions",
    "ad_click_actions",
    "ad_id",
    "ad_impression_actions",
    "ad_name",
    "adset_end",
    "adset_id",
    "adset_name",
    "adset_start",
    "age_targeting",
    "attribution_setting",
    "auction_bid",
    "auction_competitiveness",
    "auction_max_competitor_bid",
    "average_purchases_conversion_value",
    "buying_type",
    "campaign_id",
    "campaign_name",
    "canvas_avg_view_percent",
    "canvas_avg_view_time",
    "catalog_segment_actions",
    "catalog_segment_value",
    "catalog_segment_value_mobile_purchase_roas",
    "catalog_segment_value_omni_purchase_roas",
    "catalog_segment_value_website_purchase_roas",
    "clicks",
    "conversion_lead_rate",
    "conversion_leads",
    "conversion_rate_ranking",
    "conversion_values",
    "conversions",
    "converted_product_app_custom_event_fb_mobile_purchase",
    "converted_product_app_custom_event_fb_mobile_purchase_value",
    "converted_product_offline_purchase",
    "converted_product_offline_purchase_value",
    "converted_product_omni_purchase",
    "converted_product_omni_purchase_values",
    "converted_product_quantity",
    "converted_product_value",
    "converted_product_website_pixel_purchase",
    "converted_product_website_pixel_purchase_value",
    "converted_promoted_product_app_custom_event_fb_mobile_purchase",
    "converted_promoted_product_app_custom_event_fb_mobile_purchase_value",
    "converted_promoted_product_offline_purchase",
    "converted_promoted_product_offline_purchase_value",
    "converted_promoted_product_omni_purchase",
    "converted_promoted_product_omni_purchase_values",
    "converted_promoted_product_quantity",
    "converted_promoted_product_value",
    "converted_promoted_product_website_pixel_purchase",
    "converted_promoted_product_website_pixel_purchase_value",
    "cost_per_15_sec_video_view",
    "cost_per_2_sec_continuous_video_view",
    "cost_per_action_type",
    "cost_per_ad_click",
    "cost_per_conversion",
    "cost_per_conversion_lead",
    "cost_per_dda_countby_convs",
    "cost_per_estimated_ad_recallers",
    "cost_per_inline_link_click",
    "cost_per_inline_post_engagement",
    "cost_per_objective_result",
    "cost_per_one_thousand_ad_impression",
    "cost_per_outbound_click",
    "cost_per_result",
    "cost_per_thruplay",
    "cost_per_unique_action_type",
    "cost_per_unique_click",
    "cost_per_unique_conversion",
    "cost_per_unique_inline_link_click",
    "cost_per_unique_outbound_click",
    "cpc",
    "cpm",
    "cpp",
    "created_time",
    "creative_media_type",
    "ctr",
    "date_start",
    "date_stop",
    "dda_countby_convs",
    "dda_results",
    "engagement_rate_ranking",
    "estimated_ad_recall_rate",
    "estimated_ad_recall_rate_lower_bound",
    "estimated_ad_recall_rate_upper_bound",
    "estimated_ad_recallers",
    "estimated_ad_recallers_lower_bound",
    "estimated_ad_recallers_upper_bound",
    "frequency",
    "full_view_impressions",
    "full_view_reach",
    "gender_targeting",
    "impressions",
    "inline_link_click_ctr",
    "inline_link_clicks",
    "inline_post_engagement",
    "instagram_upcoming_event_reminders_set",
    "instant_experience_clicks_to_open",
    "instant_experience_clicks_to_start",
    "instant_experience_outbound_clicks",
    "interactive_component_tap",
    "labels",
    "landing_page_view_actions_per_link_click",
    "landing_page_view_per_link_click",
    "landing_page_view_per_purchase_rate",
    "location",
    "marketing_messages_click_rate_benchmark",
    "marketing_messages_cost_per_delivered",
    "marketing_messages_cost_per_link_btn_click",
    "marketing_messages_delivered",
    "marketing_messages_delivery_rate",
    "marketing_messages_link_btn_click",
    "marketing_messages_link_btn_click_rate",
    "marketing_messages_media_view_rate",
    "marketing_messages_phone_call_btn_click_rate",
    "marketing_messages_quick_reply_btn_click",
    "marketing_messages_quick_reply_btn_click_rate",
    "marketing_messages_read",
    "marketing_messages_read_rate",
    "marketing_messages_read_rate_benchmark",
    "marketing_messages_sent",
    "marketing_messages_spend",
    "marketing_messages_spend_currency",
    "marketing_messages_website_add_to_cart",
    "marketing_messages_website_initiate_checkout",
    "marketing_messages_website_purchase",
    "marketing_messages_website_purchase_values",
    "mobile_app_purchase_roas",
    "objective",
    "objective_result_rate",
    "objective_results",
    "onsite_conversion_messaging_detected_purchase_deduped",
    "optimization_goal",
    "outbound_clicks",
    "outbound_clicks_ctr",
    "place_page_name",
    "product_brand",
    "product_category",
    "product_content_id",
    "product_custom_label_0",
    "product_custom_label_1",
    "product_custom_label_2",
    "product_custom_label_3",
    "product_custom_label_4",
    "product_group_content_id",
    "product_group_retailer_id",
    "product_name",
    "product_retailer_id",
    "purchase_per_landing_page_view",
    "purchase_roas",
    "purchases_per_link_click",
    "qualifying_question_qualify_answer_rate",
    "quality_ranking",
    "reach",
    "result_rate",
    "result_values_performance_indicator",
    "results",
    "shops_assisted_purchases",
    "social_spend",
    "spend",
    "total_postbacks",
    "total_postbacks_detailed",
    "total_postbacks_detailed_v4",
    "unique_actions",
    "unique_clicks",
    "unique_conversions",
    "unique_ctr",
    "unique_inline_link_click_ctr",
    "unique_inline_link_clicks",
    "unique_link_clicks_ctr",
    "unique_outbound_clicks",
    "unique_outbound_clicks_ctr",
    "unique_video_continuous_2_sec_watched_actions",
    "unique_video_view_15_sec",
    "updated_time",
    "video_15_sec_watched_actions",
    "video_30_sec_watched_actions",
    "video_avg_time_watched_actions",
    "video_continuous_2_sec_watched_actions",
    "video_p100_watched_actions",
    "video_p25_watched_actions",
    "video_p50_watched_actions",
    "video_p75_watched_actions",
    "video_p95_watched_actions",
    "video_play_actions",
    "video_play_curve_actions",
    "video_play_retention_0_to_15s_actions",
    "video_play_retention_20_to_60s_actions",
    "video_play_retention_graph_actions",
    "video_thruplay_watched_actions",
    "video_time_watched_actions",
    "video_view_per_impression",
    "website_ctr",
    "website_purchase_roas",
    "wish_bid",
]

AD_INSIGHTS_VALID_BREAKDOWNS = [
    "ad_extension_domain",
    "ad_extension_url",
    "ad_format_asset",
    "age",
    "app_id",
    "body_asset",
    "breakdown_ad_objective",
    "breakdown_reporting_ad_id",
    "call_to_action_asset",
    "coarse_conversion_value",
    "comscore_market",
    "comscore_market_code",
    "conversion_destination",
    "country",
    "creative_relaxation_asset_type",
    "description_asset",
    "device_platform",
    "dma",
    "fidelity_type",
    "flexible_format_asset_type",
    "frequency_value",
    "gen_ai_asset_type",
    "gender",
    "hourly_stats_aggregated_by_advertiser_time_zone",
    "hourly_stats_aggregated_by_audience_time_zone",
    "hsid",
    "image_asset",
    "impression_device",
    "impression_view_time_advertiser_hour_v2",
    "is_auto_advance",
    "is_conversion_id_modeled",
    "is_rendered_as_delayed_skip_ad",
    "landing_destination",
    "link_url_asset",
    "marketing_messages_btn_name",
    "mdsa_landing_destination",
    "media_asset_url",
    "media_creator",
    "media_destination_url",
    "media_format",
    "media_origin_url",
    "media_text_content",
    "media_type",
    "mmm",
    "place_page_id",
    "platform_position",
    "postback_sequence_index",
    "product_id",
    "publisher_platform",
    "redownload",
    "region",
    "signal_source_bucket",
    "skan_campaign_id",
    "skan_conversion_id",
    "skan_version",
    "sot_attribution_model_type",
    "sot_attribution_window",
    "sot_channel",
    "sot_event_type",
    "sot_source",
    "standard_event_content_type",
    "title_asset",
    "user_persona_id",
    "user_persona_name",
    "video_asset",
]

AD_INSIGHTS_VALID_ACTION_BREAKDOWNS = [
    "1d_click",
    "1d_ev",
    "1d_view",
    "28d_click",
    "28d_view",
    "28d_view_all_conversions",
    "28d_view_first_conversion",
    "7d_click",
    "7d_view",
    "7d_view_all_conversions",
    "7d_view_first_conversion",
    "dda",
    "default",
    "skan_click",
    "skan_click_second_postback",
    "skan_click_third_postback",
    "skan_view",
    "skan_view_second_postback",
    "skan_view_third_postback",
]

DELIVERY_INFO_FIELDS = [
    "active",
    "archived",
    "completed",
    "limited",
    "not_delivering",
    "deleted",
    "not_published",
    "pending_review",
    "permanently_deleted",
    "recently_completed",
    "recently_rejected",
    "rejected",
    "scheduled",
    "inactive",
]
