credentials:
    credentials_title: Private App Credentials
    access_token_sops: ENC[AES256_GCM,data:oWD2ayun7Xo49L7D15rOgBwa4WUgb7hPYtH3WYLMinHwV675Zq5femcz9r5ElzoKpONg08792QOk6ZRzm6EQzzhzAswHGg6jXEguX7w8BVyGf+IkJPHtqS9yqfn1WVFV8Unz9LtVWf+JQXFB6ZPUkc2cudodhZIdGDRJMTHBh1k7dH91wOAFGQr48H4j9qxr186YQRWi48nOybyfeCp4l4FqTznNhfEYwEG0zIBR0Wy/rzELUOJ7/UA/OQvFC1i5E+nUyfv8dbtd7PpGrbaa3wxos6Z74auchAAo/gpiTDAEHT1PHComm4fmJgKmOYWGiPolZg5M9C36YeU4RVJteVdqAqfxYqHPM9qKh8F6H1Nx1P50KHgklDO/J7vLG+tNOuhshBfZXAlymewd4bKtpyQZVLfu20Ey/A1WoRhE4P8FXaaxCZu34g==,iv:AnCjrHe/KfL6t6lE96+VXGUw+JnI1I8HOH1UyOA0U9c=,tag:Oc4jQXdVdLBwirE7JMLC4g==,type:str]
subdomain: estuarydev
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/estuary-theatre/locations/us-central1/keyRings/connector-keyring/cryptoKeys/connector-repository
          created_at: "2025-02-13T13:40:25Z"
          enc: CiQAdmEdwspp00bTS+9+Y8Is4MNy3vcfVdf+ijefPiqC9n3PGAMSSQCtUdBGuijriK6CDg9x5jNzlXU0warWUt96Zf9Clj4yvGRt/VEnHfiwvvc4iKX2e2NYWeaatalx0fCxJEAekEMm5p/SiMO34/k=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-13T13:40:25Z"
    mac: ENC[AES256_GCM,data:SgX3Kbs8u/PgddZxI/UCSdRj7JnP1UyTPQNGCNjOVzRa4ETPy1fLWs37gfuzpZN7dh6aRHEW3Ahhz+AKJDQR+kkPF8MEcfttRPlnY89NlsuATD31PLrLD7rwLvxZiHOt08jnJIqw/ow/+cyWv8Ud0VvLP/nA9TFJBZaI836THUk=,iv:1jAIlcJZtk/zns5b/OyJKWvbYvxAMC+BVHZ+4yce6lM=,tag:q/+Jq3dPknw4bVPlNWiRjg==,type:str]
    pgp: []
    encrypted_suffix: _sops
    version: 3.9.4
