credentials:
    credentials_title: Private App Credentials
    access_token: eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjQ3MTU4Mjg2MSwiYWFpIjo0MTA3MjAsInVpZCI6NzE5ODU0MTYsImlhZCI6IjIwMjUtMDItMTJUMTQ6NTI6MzQuMDY5WiIsInBlciI6ImJvYXJkczpyZWFkLHVzZXJzOnJlYWQsdGFnczpyZWFkLHRlYW1zOnJlYWQiLCJhY3RpZCI6Mjc5MjU2ODcsInJnbiI6InVzZTEifQ.ryCp_WKKt2vqd2qSPqV5uG19B1MGF4BgpQ3aGk5gnlA
subdomain: estuarydev
