name: Go Materialization Connectors

on:
  push:
    branches: [main]
    paths:
      - "filesink/**"
      - "go/**"
      - "materialize-boilerplate/**"
      - "materialize-sql/**"
      - "materialize-motherduck/**"

  pull_request:
    branches: [main]
    paths:
      - "filesink/**"
      - "go/**"
      - "materialize-boilerplate/**"
      - "materialize-sql/**"
      - "materialize-motherduck/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_connectors:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        connector:
          - materialize-motherduck

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Common Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          gcp_service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Prepare
        id: prep
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          echo ::set-output name=tag::${TAG}
          VERSION=$(cat ${{ matrix.connector }}/VERSION | tr -d '\n')
          echo ::set-output name=version::${VERSION}
          VARIANTS="${{ matrix.connector }} $(cat ${{ matrix.connector }}/VARIANTS 2>/dev/null || true)"
          echo ::set-output name=variants::${VARIANTS}

      - name: Download latest Flow release binaries and add them to $PATH
        run: |
          ./fetch-flow.sh
          echo "${PWD}/flow-bin" >> $GITHUB_PATH

      - name: Run common Go tests
        run: |
          cd go && go test -v ./...
          cd ../materialize-boilerplate && go test -v ./...
          cd ../materialize-sql && go test -v ./...
          cd ../filesink && go test -v ./...

      - name: Run connector Go tests
        run: |
          cd ${{ matrix.connector }} && go test -v ./...